/*
ZLayer API

Testing AuditAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zlayer

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/BlackLeafDigital/ZLayer/clients/go"
)

func Test_zlayer_AuditAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuditAPIService ListAudit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuditAPI.ListAudit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
