name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for artifacts'
        required: true
        type: string
      sha:
        description: 'Commit SHA to build'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  # ===========================================
  # Build Linux amd64 (native) - FIRST
  # Required for image-build pipeline
  # ===========================================
  build-linux-amd64:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install system deps
        run: apt-get update && apt-get install -y protobuf-compiler libseccomp-dev cmake build-essential pkg-config libssl-dev clang git
      - name: Build
        run: cargo build --release --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-linux-amd64
          path: zlayer-linux-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-linux-amd64
          path: zlayer-build-linux-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-cli
        run: cargo build --release --package zlayer-cli
      - name: Package zlayer-cli
        run: tar czf "zlayer-cli-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer-cli
      - name: Upload zlayer-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-cli-linux-amd64
          path: zlayer-cli-linux-amd64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-linux-amd64.tar.gz zlayer-build-linux-amd64.tar.gz zlayer-cli-linux-amd64.tar.gz

  # ===========================================
  # Build container images using pipeline - EARLY
  # Runs after linux-amd64, gates all other builds
  # ===========================================
  image-build:
    name: Image Build (Pipeline)
    needs: [build-linux-amd64]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - name: Install buildah
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Download zlayer-build
        uses: actions/download-artifact@v3
        with:
          name: zlayer-build-linux-amd64
      - name: Install zlayer-build
        run: tar xzf zlayer-build-linux-amd64.tar.gz && chmod +x zlayer-build && sudo mv zlayer-build /usr/local/bin/
      - name: Download zlayer binary (for zlayer-node image)
        uses: actions/download-artifact@v3
        with:
          name: zlayer-linux-amd64
      - name: Prepare zlayer binary for node image
        run: |
          mkdir -p target/release
          tar xzf zlayer-linux-amd64.tar.gz -C target/release/
      - name: Build all images with pipeline
        run: |
          sudo zlayer-build pipeline \
            -f ZPipeline.yaml \
            --no-tui \
            --set VERSION=build-${{ github.run_id }} \
            --set REGISTRY=zlayer

      - name: Export images as OCI archives
        run: |
          for img in zlayer-node zlayer-web zlayer-manager; do
            echo "Exporting ${img}..."
            sudo buildah push zlayer/${img}:build-${{ github.run_id }} \
              oci-archive:${img}-oci.tar
          done

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: container-images
          path: |
            zlayer-node-oci.tar
            zlayer-web-oci.tar
            zlayer-manager-oci.tar
          retention-days: 1

  # ===========================================
  # Build Linux arm64 (cross-compile)
  # Runs after image-build succeeds
  # ===========================================
  build-linux-arm64:
    needs: [image-build]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CROSS_TARGET_DIR: ${{ github.workspace }}/cross-target
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install cross
        run: cargo install cross
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Create target directory
        run: mkdir -p $CROSS_TARGET_DIR
      - name: Build
        run: cross build --release --target aarch64-unknown-linux-gnu --package runtime --features "docker,wasm" --target-dir $CROSS_TARGET_DIR
      - name: Package
        run: tar czf "zlayer-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-linux-arm64
          path: zlayer-linux-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cross build --release --target aarch64-unknown-linux-gnu --package zlayer-build --target-dir $CROSS_TARGET_DIR
      - name: Package zlayer-build
        run: tar czf "zlayer-build-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-linux-arm64
          path: zlayer-build-linux-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-cli
        run: cross build --release --target aarch64-unknown-linux-gnu --package zlayer-cli --target-dir $CROSS_TARGET_DIR
      - name: Package zlayer-cli
        run: tar czf "zlayer-cli-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer-cli
      - name: Upload zlayer-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-cli-linux-arm64
          path: zlayer-cli-linux-arm64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CROSS_TARGET_DIR zlayer-linux-arm64.tar.gz zlayer-build-linux-arm64.tar.gz zlayer-cli-linux-arm64.tar.gz

  # ===========================================
  # Build macOS amd64
  # Runs after image-build succeeds
  # ===========================================
  build-macos-amd64:
    needs: [image-build]
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: x86_64-apple-darwin
      - name: Ensure target installed
        run: rustup target add x86_64-apple-darwin
      - name: Debug - Show environment
        run: |
          echo "=== Rust/Cargo versions ==="
          rustc --version
          cargo --version
          echo "=== Installed targets ==="
          rustup target list --installed
          echo "=== CARGO_HOME / RUSTUP_HOME ==="
          echo "CARGO_HOME=$CARGO_HOME"
          echo "RUSTUP_HOME=$RUSTUP_HOME"
          echo "=== Feature resolution for x86_64-apple-darwin ==="
          cargo tree -p runtime --features "docker,wasm" --target x86_64-apple-darwin 2>&1 | grep -E "(zlayer-agent|bollard|wasmtime|futures-util)" | head -30 || true
          echo "=== Full zlayer-agent deps ==="
          cargo tree -p zlayer-agent --features "docker,wasm" --target x86_64-apple-darwin 2>&1 | head -50 || true
      - name: Install protobuf
        run: brew install protobuf
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-darwin-amd64
          path: zlayer-darwin-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --target x86_64-apple-darwin --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-darwin-amd64
          path: zlayer-build-darwin-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-cli
        run: cargo build --release --target x86_64-apple-darwin --package zlayer-cli
      - name: Package zlayer-cli
        run: tar czf "zlayer-cli-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer-cli
      - name: Upload zlayer-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-cli-darwin-amd64
          path: zlayer-cli-darwin-amd64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-darwin-amd64.tar.gz zlayer-build-darwin-amd64.tar.gz zlayer-cli-darwin-amd64.tar.gz

  # ===========================================
  # Build macOS arm64
  # Runs after image-build succeeds
  # ===========================================
  build-macos-arm64:
    needs: [image-build]
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: aarch64-apple-darwin
      - name: Ensure target installed
        run: rustup target add aarch64-apple-darwin
      - name: Clean build state
        run: cargo clean
      - name: Install protobuf
        run: brew install protobuf
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-darwin-arm64
          path: zlayer-darwin-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --target aarch64-apple-darwin --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-darwin-arm64
          path: zlayer-build-darwin-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-cli
        run: cargo build --release --target aarch64-apple-darwin --package zlayer-cli
      - name: Package zlayer-cli
        run: tar czf "zlayer-cli-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer-cli
      - name: Upload zlayer-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-cli-darwin-arm64
          path: zlayer-cli-darwin-arm64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-darwin-arm64.tar.gz zlayer-build-darwin-arm64.tar.gz zlayer-cli-darwin-arm64.tar.gz

  # ===========================================
  # Verify all builds passed
  # ===========================================
  verify:
    needs: [build-linux-amd64, build-linux-arm64, build-macos-amd64, build-macos-arm64, image-build]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      success: ${{ steps.check.outputs.success }}
    steps:
      - name: Check all builds
        id: check
        run: echo "success=true" >> $GITHUB_OUTPUT

  # ===========================================
  # Upload artifacts to temp Forgejo Packages
  # ===========================================
  upload-temp-packages:
    needs: [verify]
    if: needs.verify.outputs.success == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      package_base_url: ${{ steps.upload.outputs.package_base_url }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List artifacts for debugging
        run: |
          echo "=== Downloaded artifacts ==="
          find artifacts -type f -ls

      - name: Upload to temp packages
        id: upload
        run: |
          RUN_ID="${{ github.run_id }}"
          VERSION="${{ inputs.version }}"
          BASE_URL="https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer-temp/${RUN_ID}"
          AUTH="zachhandley:${{ secrets.FORGEJO_ACTIONS_TOKEN }}"

          # Resilient upload function with retry, timeout, and conflict handling
          upload_with_retry() {
            local file="$1"
            local url="$2"
            local max_retries=5
            local retry=0
            local backoff=5

            while [ $retry -lt $max_retries ]; do
              echo "Uploading $(basename "$file") (attempt $((retry + 1))/$max_retries)..."

              # Try upload with timeout (5 min for large files)
              http_code=$(curl -s -o /dev/null -w "%{http_code}" \
                --max-time 300 \
                --connect-timeout 30 \
                --retry 3 \
                --retry-delay 5 \
                --user "$AUTH" \
                --upload-file "$file" \
                "$url" 2>/dev/null) || http_code="000"

              case "$http_code" in
                200|201)
                  echo "✓ Successfully uploaded $(basename "$file")"
                  return 0
                  ;;
                409)
                  echo "File already exists (409), attempting to delete and re-upload..."
                  # Try to delete existing file
                  curl -s -X DELETE --user "$AUTH" "$url" || true
                  sleep 2
                  # Retry upload after delete
                  http_code=$(curl -s -o /dev/null -w "%{http_code}" \
                    --max-time 300 \
                    --connect-timeout 30 \
                    --user "$AUTH" \
                    --upload-file "$file" \
                    "$url" 2>/dev/null) || http_code="000"

                  if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
                    echo "✓ Successfully uploaded $(basename "$file") after delete"
                    return 0
                  fi
                  ;;
                000)
                  echo "Connection failed or timed out"
                  ;;
                *)
                  echo "Upload failed with HTTP $http_code"
                  ;;
              esac

              retry=$((retry + 1))
              if [ $retry -lt $max_retries ]; then
                echo "Retrying in ${backoff}s..."
                sleep $backoff
                backoff=$((backoff * 2))
              fi
            done

            echo "✗ Failed to upload $(basename "$file") after $max_retries attempts"
            return 1
          }

          failed=0

          # Upload binary artifacts
          for artifact in artifacts/zlayer-*/*.tar.gz; do
            [ -f "$artifact" ] || continue
            filename=$(basename "$artifact")
            if ! upload_with_retry "$artifact" "${BASE_URL}/${filename}"; then
              failed=1
            fi
          done

          # Upload container image archives
          for archive in artifacts/container-images/*.tar; do
            [ -f "$archive" ] || continue
            filename=$(basename "$archive")
            if ! upload_with_retry "$archive" "${BASE_URL}/${filename}"; then
              failed=1
            fi
          done

          if [ $failed -ne 0 ]; then
            echo "::error::Some uploads failed"
            exit 1
          fi

          echo "package_base_url=${BASE_URL}" >> $GITHUB_OUTPUT

  # ===========================================
  # Dispatch Release workflow
  # ===========================================
  dispatch-release:
    needs: [verify, upload-temp-packages]
    if: needs.verify.outputs.success == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches" \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "version": "${{ inputs.version }}",
                "sha": "${{ inputs.sha || github.sha }}",
                "artifact_base_url": "${{ needs.upload-temp-packages.outputs.package_base_url }}"
              }
            }'

      - name: Summary
        run: |
          echo "## Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA**: ${{ inputs.sha || github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifacts**: ${{ needs.upload-temp-packages.outputs.package_base_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Release workflow dispatched." >> $GITHUB_STEP_SUMMARY
