name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for artifacts'
        required: true
        type: string
      sha:
        description: 'Commit SHA to build'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  # ===========================================
  # Build Linux amd64 (native) - FIRST
  # Required for image-build pipeline
  # ===========================================
  build-linux-amd64:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container: node:20-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install system deps
        run: apt-get update && apt-get install -y protobuf-compiler libseccomp-dev cmake build-essential pkg-config libssl-dev clang git
      - name: Build
        run: cargo build --release --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-runtime-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-runtime-linux-amd64
          path: zlayer-runtime-linux-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-linux-amd64
          path: zlayer-build-linux-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer
        run: cargo build --release --package zlayer
      - name: Package zlayer
        run: tar czf "zlayer-linux-amd64.tar.gz" -C $CARGO_TARGET_DIR/release zlayer
      - name: Upload zlayer artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-linux-amd64
          path: zlayer-linux-amd64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-runtime-linux-amd64.tar.gz zlayer-build-linux-amd64.tar.gz zlayer-linux-amd64.tar.gz

  # ===========================================
  # Build container images using pipeline - EARLY
  # Runs after linux-amd64, gates all other builds
  # ===========================================
  image-build:
    name: Image Build (Pipeline)
    needs: [build-linux-amd64]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - name: Install buildah
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Download zlayer-build
        uses: actions/download-artifact@v3
        with:
          name: zlayer-build-linux-amd64
      - name: Install zlayer-build
        run: tar xzf zlayer-build-linux-amd64.tar.gz && chmod +x zlayer-build && sudo mv zlayer-build /usr/local/bin/
      - name: Download zlayer-runtime binary (for zlayer-node image)
        uses: actions/download-artifact@v3
        with:
          name: zlayer-runtime-linux-amd64
      - name: Prepare zlayer-runtime binary for node image
        run: |
          mkdir -p target/release
          tar xzf zlayer-runtime-linux-amd64.tar.gz -C target/release/
      - name: Build all images with pipeline
        run: |
          sudo zlayer-build pipeline \
            -f ZPipeline.yaml \
            --no-tui \
            --set VERSION=build-${{ github.run_id }} \
            --set REGISTRY=zlayer

      - name: Export images as OCI archives
        run: |
          for img in zlayer-node zlayer-web zlayer-manager; do
            echo "Exporting ${img}..."
            sudo buildah push zlayer/${img}:build-${{ github.run_id }} \
              oci-archive:${img}-oci.tar
          done

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: container-images
          path: |
            zlayer-node-oci.tar
            zlayer-web-oci.tar
            zlayer-manager-oci.tar
          retention-days: 1

  # ===========================================
  # Build Linux arm64 (cross-compile)
  # Runs after image-build succeeds
  # ===========================================
  build-linux-arm64:
    needs: [image-build]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CROSS_TARGET_DIR: ${{ github.workspace }}/cross-target
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install cross
        run: cargo install cross
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Create target directory
        run: mkdir -p $CROSS_TARGET_DIR
      - name: Build
        run: cross build --release --target aarch64-unknown-linux-gnu --package runtime --features "docker,wasm" --target-dir $CROSS_TARGET_DIR
      - name: Package
        run: tar czf "zlayer-runtime-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-runtime-linux-arm64
          path: zlayer-runtime-linux-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cross build --release --target aarch64-unknown-linux-gnu --package zlayer-build --target-dir $CROSS_TARGET_DIR
      - name: Package zlayer-build
        run: tar czf "zlayer-build-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-linux-arm64
          path: zlayer-build-linux-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer
        run: cross build --release --target aarch64-unknown-linux-gnu --package zlayer --target-dir $CROSS_TARGET_DIR
      - name: Package zlayer
        run: tar czf "zlayer-linux-arm64.tar.gz" -C $CROSS_TARGET_DIR/aarch64-unknown-linux-gnu/release zlayer
      - name: Upload zlayer artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-linux-arm64
          path: zlayer-linux-arm64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CROSS_TARGET_DIR zlayer-runtime-linux-arm64.tar.gz zlayer-build-linux-arm64.tar.gz zlayer-linux-arm64.tar.gz

  # ===========================================
  # Build macOS amd64
  # Runs after image-build succeeds
  # ===========================================
  build-macos-amd64:
    needs: [image-build]
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: x86_64-apple-darwin
      - name: Ensure target installed
        run: rustup target add x86_64-apple-darwin
      - name: Debug - Show environment
        run: |
          echo "=== Rust/Cargo versions ==="
          rustc --version
          cargo --version
          echo "=== Installed targets ==="
          rustup target list --installed
          echo "=== CARGO_HOME / RUSTUP_HOME ==="
          echo "CARGO_HOME=$CARGO_HOME"
          echo "RUSTUP_HOME=$RUSTUP_HOME"
          echo "=== Feature resolution for x86_64-apple-darwin ==="
          cargo tree -p runtime --features "docker,wasm" --target x86_64-apple-darwin 2>&1 | grep -E "(zlayer-agent|bollard|wasmtime|futures-util)" | head -30 || true
          echo "=== Full zlayer-agent deps ==="
          cargo tree -p zlayer-agent --features "docker,wasm" --target x86_64-apple-darwin 2>&1 | head -50 || true
      - name: Install protobuf
        run: brew install protobuf
      - name: Build
        run: cargo build --release --target x86_64-apple-darwin --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-runtime-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-runtime-darwin-amd64
          path: zlayer-runtime-darwin-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --target x86_64-apple-darwin --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-darwin-amd64
          path: zlayer-build-darwin-amd64.tar.gz
          retention-days: 1
      - name: Build zlayer
        run: cargo build --release --target x86_64-apple-darwin --package zlayer
      - name: Package zlayer
        run: tar czf "zlayer-darwin-amd64.tar.gz" -C $CARGO_TARGET_DIR/x86_64-apple-darwin/release zlayer
      - name: Upload zlayer artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-darwin-amd64
          path: zlayer-darwin-amd64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-runtime-darwin-amd64.tar.gz zlayer-build-darwin-amd64.tar.gz zlayer-darwin-amd64.tar.gz

  # ===========================================
  # Build macOS arm64
  # Runs after image-build succeeds
  # ===========================================
  build-macos-arm64:
    needs: [image-build]
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: aarch64-apple-darwin
      - name: Ensure target installed
        run: rustup target add aarch64-apple-darwin
      - name: Clean build state
        run: cargo clean
      - name: Install protobuf
        run: brew install protobuf
      - name: Build
        run: cargo build --release --target aarch64-apple-darwin --package runtime --features "docker,wasm"
      - name: Package
        run: tar czf "zlayer-runtime-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-runtime-darwin-arm64
          path: zlayer-runtime-darwin-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer-build
        run: cargo build --release --target aarch64-apple-darwin --package zlayer-build
      - name: Package zlayer-build
        run: tar czf "zlayer-build-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer-build
      - name: Upload zlayer-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-build-darwin-arm64
          path: zlayer-build-darwin-arm64.tar.gz
          retention-days: 1
      - name: Build zlayer
        run: cargo build --release --target aarch64-apple-darwin --package zlayer
      - name: Package zlayer
        run: tar czf "zlayer-darwin-arm64.tar.gz" -C $CARGO_TARGET_DIR/aarch64-apple-darwin/release zlayer
      - name: Upload zlayer artifact
        uses: actions/upload-artifact@v3
        with:
          name: zlayer-darwin-arm64
          path: zlayer-darwin-arm64.tar.gz
          retention-days: 1
      - name: Cleanup
        run: rm -rf $CARGO_TARGET_DIR zlayer-runtime-darwin-arm64.tar.gz zlayer-build-darwin-arm64.tar.gz zlayer-darwin-arm64.tar.gz

  # ===========================================
  # Verify all builds passed
  # ===========================================
  verify:
    needs: [build-linux-amd64, build-linux-arm64, build-macos-amd64, build-macos-arm64, image-build]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      success: ${{ steps.check.outputs.success }}
    steps:
      - name: Check all builds
        id: check
        run: echo "success=true" >> $GITHUB_OUTPUT

  # ===========================================
  # Upload artifacts to temp Forgejo Packages
  # ===========================================
  upload-temp-packages:
    needs: [verify]
    if: needs.verify.outputs.success == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      package_base_url: ${{ steps.upload.outputs.package_base_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}
          sparse-checkout: scripts/upload-packages.sh

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List artifacts for debugging
        run: |
          echo "=== Downloaded artifacts ==="
          find artifacts -type f -ls

      - name: Upload to temp packages
        id: upload
        shell: bash
        run: |
          BASE_URL="https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer-temp/${{ github.run_id }}"
          chmod +x scripts/upload-packages.sh
          ./scripts/upload-packages.sh "$BASE_URL" "zachhandley:${{ secrets.FORGEJO_ACTIONS_TOKEN }}" artifacts
          echo "package_base_url=${BASE_URL}" >> $GITHUB_OUTPUT

  # ===========================================
  # Dispatch Release workflow
  # ===========================================
  dispatch-release:
    needs: [verify, upload-temp-packages]
    if: needs.verify.outputs.success == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches" \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "version": "${{ inputs.version }}",
                "sha": "${{ inputs.sha || github.sha }}",
                "artifact_base_url": "${{ needs.upload-temp-packages.outputs.package_base_url }}"
              }
            }'

      - name: Summary
        run: |
          echo "## Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA**: ${{ inputs.sha || github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifacts**: ${{ needs.upload-temp-packages.outputs.package_base_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Release workflow dispatched." >> $GITHUB_STEP_SUMMARY
