name: CI

on:
  push:
    branches: [main, dev]
    tags:
      - 'v*'
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v1.0.0)'
        required: false
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "0"

jobs:
  # ===========================================
  # Check (fmt, clippy)
  # ===========================================
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          components: rustfmt, clippy

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Test
  # ===========================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

      - name: Run integration tests
        run: |
          # Scheduler tests need test-skip-http feature to skip agent HTTP calls
          cargo test -p zlayer-scheduler --features test-skip-http --test '*'
          # Run all other integration tests
          cargo test --workspace --test '*' --exclude zlayer-scheduler

      - name: Run doc tests
        run: cargo test --workspace --doc

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Build Release
  # ===========================================
  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build release binaries
        run: |
          cargo build --release --package runtime

      - name: Upload artifacts
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: binaries
          path: |
            target/release/zlayer
          retention-days: 7

  # ===========================================
  # Feature Matrix Tests
  # ===========================================
  feature-tests:
    name: Feature Tests
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        features:
          - "--no-default-features --features join"
          - "--no-default-features --features serve"
          - "--no-default-features --features deploy"
          - "--features full"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build with features
        run: cargo build --package runtime ${{ matrix.features }}

      - name: Test with features
        run: cargo test --package runtime ${{ matrix.features }}

  # ===========================================
  # Trigger E2E Tests
  # ===========================================
  trigger-e2e:
    name: Trigger E2E
    runs-on: ubuntu-latest
    needs: [build, feature-tests]
    steps:
      - name: Determine version
        id: version
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Trigger E2E workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/e2e.yml/dispatches" \
            -d '{"ref": "${{ github.ref }}", "inputs": {"version": "${{ steps.version.outputs.version }}", "sha": "${{ github.sha }}"}}'

  # ===========================================
  # Cache Cleanup
  # ===========================================
  cache-cleanup:
    name: Cleanup Old Caches
    runs-on: ubuntu-latest
    needs: [build, feature-tests]
    if: always()
    steps:
      - name: Cleanup old caches
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: cleanup
          max-age-days: '30'
          keep-latest: '5'
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}
