name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-features -- -D warnings

      - name: Test
        run: cargo test --workspace --all-features
