name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

      - name: Run integration tests
        run: cargo test --workspace --test '*'

      - name: Run doc tests
        run: cargo test --workspace --doc

  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-

      - name: Build release binaries
        run: |
          cargo build --release --package runtime
          cargo build --release --package devctl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            target/release/zlayer
            target/release/devctl
          retention-days: 7

  # Feature matrix test
  feature-tests:
    name: Feature Tests
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        features:
          - "--no-default-features --features join"
          - "--no-default-features --features serve"
          - "--no-default-features --features deploy"
          - "--features full"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-features-${{ hashFiles('**/Cargo.lock') }}

      - name: Build with features
        run: cargo build --package runtime ${{ matrix.features }}

      - name: Test with features
        run: cargo test --package runtime ${{ matrix.features }}

  # E2E tests with real containerd
  e2e-tests:
    name: E2E Tests (Containerd)
    runs-on: ubuntu-latest
    needs: test
    # Only run on main branch or explicit trigger (expensive)
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[e2e]')
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-e2e-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-e2e-
            ${{ runner.os }}-cargo-

      - name: Install containerd
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd runc
          sudo systemctl start containerd
          sudo systemctl status containerd

      - name: Verify containerd is running
        run: |
          sudo ctr version
          sudo ctr namespace ls

      - name: Create test namespace
        run: |
          sudo ctr namespace create zlayer-e2e-test || true

      - name: Pull test images
        run: |
          sudo ctr -n zlayer-e2e-test image pull docker.io/library/alpine:latest
          sudo ctr -n zlayer-e2e-test image pull docker.io/library/nginx:alpine

      - name: Run E2E tests
        run: |
          # Run with sudo since containerd socket requires root
          sudo -E env "PATH=$PATH" $(which cargo) test --package agent --test containerd_e2e -- --test-threads=1
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

      - name: Cleanup test namespace
        if: always()
        run: |
          sudo ctr -n zlayer-e2e-test containers rm $(sudo ctr -n zlayer-e2e-test containers ls -q) 2>/dev/null || true
          sudo ctr -n zlayer-e2e-test tasks rm $(sudo ctr -n zlayer-e2e-test tasks ls -q) 2>/dev/null || true
          sudo ctr namespace remove zlayer-e2e-test 2>/dev/null || true
