name: CI

on:
  push:
    branches: [main, dev]
    tags:
      - 'v*'
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v1.0.0)'
        required: false
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "0"

jobs:
  # ===========================================
  # Check (fmt, clippy) — skipped for tags
  # (tagged commits already passed CI on their branch)
  # ===========================================
  check:
    name: Check
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          components: rustfmt, clippy

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Check macOS (check, clippy) — skipped for tags
  # Runs in parallel with Linux check to catch macOS-specific
  # compilation errors in #[cfg(target_os = "macos")] code
  # ===========================================
  check-macos:
    name: Check (macOS)
    runs-on: macos-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: brew install protobuf python3

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          components: clippy

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

  # ===========================================
  # Test — skipped for tags
  # ===========================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: check
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

      - name: Run integration tests
        run: |
          # Scheduler tests need test-skip-http feature to skip agent HTTP calls
          cargo test -p zlayer-scheduler --features test-skip-http --test '*'
          # Run all other integration tests
          cargo test --workspace --test '*' --exclude zlayer-scheduler

      - name: Run doc tests
        run: cargo test --workspace --doc

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Test macOS — skipped for tags
  # Runs unit and doc tests on macOS. Integration tests
  # requiring root/containers are auto-skipped via cfg(target_os).
  # ===========================================
  test-macos:
    name: Test (macOS)
    runs-on: macos-latest
    needs: check-macos
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: brew install protobuf python3

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

      - name: Run doc tests
        run: cargo test --workspace --doc

  # ===========================================
  # Build Release (Linux)
  # For tags: runs directly (tests already passed on the branch)
  # For branches: waits for test + feature-tests
  # ===========================================
  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: [test, feature-tests]
    if: |-
      ${{
        always() &&
        (startsWith(github.ref, 'refs/tags/') ||
         (needs.test.result == 'success' && needs.feature-tests.result == 'success'))
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build release binary
        run: cargo build --release --package zlayer

      - name: Upload artifacts
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: binaries
          path: |
            target/release/zlayer
          retention-days: 7

  # ===========================================
  # Build Release (macOS ARM64)
  # For tags: runs directly (tests already passed on the branch)
  # For branches: waits for test-macos
  # ===========================================
  build-macos:
    name: Build Release (macOS)
    runs-on: macos-latest
    needs: [test-macos]
    if: |-
      ${{
        always() &&
        (startsWith(github.ref, 'refs/tags/') ||
         needs.test-macos.result == 'success')
      }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: brew install protobuf

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Build release binary
        run: cargo build --release --package zlayer

      - name: Upload artifacts
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: binaries-macos-arm64
          path: |
            target/release/zlayer
          retention-days: 7

  # ===========================================
  # Feature Matrix Tests — skipped for tags
  # ===========================================
  feature-tests:
    name: Feature Tests
    runs-on: ubuntu-latest
    needs: check
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        features:
          - "--no-default-features"
          - "--features full"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build with features
        run: cargo build --package zlayer ${{ matrix.features }}

      - name: Test with features
        run: cargo test --package zlayer ${{ matrix.features }}

  # ===========================================
  # Trigger E2E Tests
  # For tags: runs after build (tests were skipped)
  # For branches: runs after build + feature-tests
  # ===========================================
  trigger-e2e:
    name: Trigger E2E
    runs-on: ubuntu-latest
    needs: [build, build-macos, feature-tests]
    if: |-
      ${{
        always() && needs.build.result == 'success'
      }}
    steps:
      - name: Determine version
        id: version
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Trigger E2E workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/e2e.yml/dispatches" \
            -d '{"ref": "${{ github.ref }}", "inputs": {"version": "${{ steps.version.outputs.version }}", "sha": "${{ github.sha }}"}}'

  # ===========================================
  # Cache Cleanup
  # ===========================================
  cache-cleanup:
    name: Cleanup Old Caches
    runs-on: ubuntu-latest
    needs: [build, build-macos, feature-tests]
    if: always()
    steps:
      - name: Cleanup old caches
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: cleanup
          max-age-days: '30'
          keep-latest: '5'
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}
