name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0) - triggers release if provided'
        required: false
        type: string
      sha:
        description: 'Commit SHA to test'
        required: false
        type: string

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "0"

jobs:
  # ===========================================
  # E2E Tests (Youki/libcontainer)
  # ===========================================
  e2e-tests:
    name: E2E Tests (Youki)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u zachhandley --password-stdin

      - name: Setup E2E environment
        run: |
          # Clean up any leftover state from previous runs
          sudo rm -rf /tmp/zlayer-youki-e2e-test 2>/dev/null || true
          # Create test directories (must match E2E_TEST_DIR in youki_e2e.rs)
          mkdir -p /tmp/zlayer-youki-e2e-test/{state,rootfs,bundles,cache}

      - name: Run E2E tests
        run: sudo -E env "PATH=$PATH" cargo test --package zlayer-agent --test youki_e2e -- --nocapture
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

      - name: Fix permissions after sudo test
        if: always()
        run: |
          # sudo cargo test creates root-owned files in CARGO_HOME and CARGO_TARGET_DIR
          # The runner's cache mechanism can't tar them up without this
          sudo chown -R "$(id -u):$(id -g)" "${CARGO_HOME}" 2>/dev/null || true
          sudo chown -R "$(id -u):$(id -g)" "${CARGO_TARGET_DIR}" 2>/dev/null || true

      - name: Cleanup
        if: always()
        run: |
          sudo rm -rf /var/lib/zlayer/* 2>/dev/null || true
          rm -rf /tmp/zlayer-youki-e2e-test 2>/dev/null || true

  # ===========================================
  # E2E Tests (WASM)
  # ===========================================
  wasm-e2e-tests:
    name: E2E Tests (WASM)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Run WASM E2E tests
        run: cargo test --package zlayer-agent --features wasm --test wasm_e2e_test -- --nocapture
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

  # ===========================================
  # E2E Tests (Docker)
  # ===========================================
  docker-e2e-tests:
    name: E2E Tests (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u zachhandley --password-stdin

      - name: Run Docker E2E tests
        run: cargo test --package zlayer-agent --features docker --test docker_runtime_test -- --nocapture
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

  # ===========================================
  # E2E Tests (Manager UI)
  # ===========================================
  manager-tests:
    name: E2E Tests (Manager)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Run Manager tests
        run: cargo test --package zlayer-manager --lib --features ssr -- --nocapture
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug

  # ===========================================
  # Trigger Build (if version provided)
  # ===========================================
  trigger-build:
    name: Trigger Build
    runs-on: ubuntu-latest
    needs: [e2e-tests, wasm-e2e-tests, docker-e2e-tests, manager-tests]
    if: inputs.version != ''
    steps:
      - name: Trigger Build workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches" \
            -d '{"ref": "${{ github.ref }}", "inputs": {"version": "${{ inputs.version }}", "sha": "${{ inputs.sha || github.sha }}"}}'

      - name: Summary
        run: |
          echo "## E2E Tests Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA**: ${{ inputs.sha || github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Build workflow triggered." >> $GITHUB_STEP_SUMMARY
