name: Merge Dev to Main

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git merge origin/dev --no-ff -X theirs -m "Merge dev into main"
          git push origin main
