name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-amd64:
    name: Build Release (linux-amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev libssl-dev pkg-config

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build release binaries
        run: |
          cargo build --release --package runtime

      - name: Create release archive
        run: |
          mkdir -p release
          cp "${CARGO_TARGET_DIR}/release/zlayer" release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-amd64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz

  build-arm64:
    name: Build Release (linux-arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build in Docker container
        run: |
          docker build --platform linux/arm64 -f docker/Dockerfile.arm64-builder -t zlayer-arm64-build .
          # Extract binaries from the image
          CONTAINER=$(docker create zlayer-arm64-build)
          mkdir -p target/release
          docker cp "${CONTAINER}:/output/zlayer" target/release/
          docker rm "${CONTAINER}"

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/release/zlayer release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-arm64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz

  # ===========================================
  # Publish Crates to crates.io
  # ===========================================
  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev libssl-dev pkg-config

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      # Tier 1: No internal dependencies
      # First crate has no continue-on-error - if this fails, the whole job fails
      # (likely a token issue or network problem that would affect all publishes)
      - name: Publish zlayer-spec
        run: cargo publish -p zlayer-spec --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-builder
        continue-on-error: true
        run: cargo publish -p zlayer-builder --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-storage
        continue-on-error: true
        run: cargo publish -p zlayer-storage --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update (tier 1)
        run: sleep 30

      # Tier 2: Depends on tier 1
      - name: Publish zlayer-core
        continue-on-error: true
        run: cargo publish -p zlayer-core --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-registry
        continue-on-error: true
        run: cargo publish -p zlayer-registry --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-observability
        continue-on-error: true
        run: cargo publish -p zlayer-observability --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-init-actions
        continue-on-error: true
        run: cargo publish -p zlayer-init-actions --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update (tier 2)
        run: sleep 30

      # Tier 3: Depends on tier 1 and 2
      - name: Publish zlayer-overlay
        continue-on-error: true
        run: cargo publish -p zlayer-overlay --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-scheduler
        continue-on-error: true
        run: cargo publish -p zlayer-scheduler --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-proxy
        continue-on-error: true
        run: cargo publish -p zlayer-proxy --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update (tier 3)
        run: sleep 30

      # Tier 4: Depends on many crates
      - name: Publish zlayer-agent
        continue-on-error: true
        run: cargo publish -p zlayer-agent --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update (tier 4)
        run: sleep 30

      # Tier 5: Depends on agent
      - name: Publish zlayer-api
        continue-on-error: true
        run: cargo publish -p zlayer-api --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zlayer-web
        continue-on-error: true
        run: cargo publish -p zlayer-web --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index update (tier 5)
        run: sleep 30

      # Tier 6: Python bindings (depends on agent, spec, builder)
      - name: Publish zlayer-py
        continue-on-error: true
        run: cargo publish -p zlayer-py --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64, publish-crates]
    env:
      VERSION: ${{ inputs.version || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag if manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Only create tag if it doesn't already exist
          if ! git rev-parse "${{ inputs.version }}" >/dev/null 2>&1; then
            git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}"
            git push origin "${{ inputs.version }}"
          else
            echo "Tag ${{ inputs.version }} already exists, skipping tag creation"
          fi

      - name: Download all artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Publish to Package Registry
        run: |
          BASE_URL="https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer"
          AUTH_HEADER="Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}"

          for arch in amd64 arm64; do
            FILE="artifacts/zlayer-linux-${arch}/zlayer-${VERSION}-linux-${arch}.tar.gz"

            # Versioned release - delete if exists, then upload
            curl -X DELETE -H "$AUTH_HEADER" "${BASE_URL}/${VERSION}/zlayer-linux-${arch}.tar.gz" || true
            curl --fail -X PUT -H "$AUTH_HEADER" --upload-file "$FILE" "${BASE_URL}/${VERSION}/zlayer-linux-${arch}.tar.gz"

            # Latest - delete if exists, then upload
            curl -X DELETE -H "$AUTH_HEADER" "${BASE_URL}/latest/zlayer-linux-${arch}.tar.gz" || true
            curl --fail -X PUT -H "$AUTH_HEADER" --upload-file "$FILE" "${BASE_URL}/latest/zlayer-linux-${arch}.tar.gz"
          done

      - name: Delete existing Forgejo release if exists
        env:
          VERSION: ${{ inputs.version || github.ref_name }}
        run: |
          # Get release ID by tag
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://forge.blackleafdigital.com/api/v1/repos/BlackLeafDigital/ZLayer/releases/tags/${VERSION}" \
            | jq -r '.id // empty')

          if [ -n "$RELEASE_ID" ]; then
            echo "Deleting existing release ${VERSION} (ID: ${RELEASE_ID})"
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://forge.blackleafdigital.com/api/v1/repos/BlackLeafDigital/ZLayer/releases/${RELEASE_ID}"
          else
            echo "No existing release found for ${VERSION}"
          fi

      - name: Create Forgejo Release
        uses: https://github.com/softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version || github.ref_name }}
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          VERSION: ${{ inputs.version || github.ref_name }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GH_TOKEN}" \
            "https://api.github.com/repos/BlackLeafDigital/ZLayer/actions/workflows/release.yml/dispatches" \
            -d "{\"ref\":\"main\",\"inputs\":{\"version\":\"${VERSION}\"}}"
