name: Release

on:
  push:
    tags:
      # Crate-specific releases (direct tag push is fine)
      - 'spec-v*'
      - 'core-v*'
      - 'registry-v*'
      - 'obs-v*'
      - 'builder-v*'
      - 'overlay-v*'
      - 'init-v*'
      - 'scheduler-v*'
      - 'storage-v*'
      - 'rust-sdk-v*'
      - 'py-sdk-v*'
      - 'ts-sdk-v*'
      - 'go-sdk-v*'
      - 'c-sdk-v*'
      - 'docker-v*'
      # General version tags
      - 'v[0-9]*'
      - 'major-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      sha:
        description: 'Commit SHA for the release'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      binary: ${{ steps.check.outputs.binary }}
      crate_name: ${{ steps.check.outputs.crate_name }}
      sdk_name: ${{ steps.check.outputs.sdk_name }}
      docker: ${{ steps.check.outputs.docker }}
      is_major: ${{ steps.check.outputs.is_major }}
      is_general: ${{ steps.check.outputs.is_general }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - name: Detect release type
        id: check
        run: |
          # Use inputs.version for workflow_dispatch, otherwise use tag name
          if [[ -n "${{ inputs.version }}" ]]; then
            TAG="${{ inputs.version }}"
          else
            TAG="${{ github.ref_name }}"
          fi
          VERSION=$(echo "$TAG" | grep -oP '\d+\.\d+\.\d+' || echo "0.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [[ "$TAG" == major-v* ]]; then
            echo "is_major=true" >> $GITHUB_OUTPUT
            echo "is_general=true" >> $GITHUB_OUTPUT
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == v[0-9]* ]]; then
            echo "is_general=true" >> $GITHUB_OUTPUT
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == docker-v* ]]; then
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == spec-v* ]]; then
            echo "crate_name=zlayer-spec" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == core-v* ]]; then
            echo "crate_name=zlayer-core" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == registry-v* ]]; then
            echo "crate_name=zlayer-registry" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == obs-v* ]]; then
            echo "crate_name=zlayer-observability" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == builder-v* ]]; then
            echo "crate_name=zlayer-builder" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == overlay-v* ]]; then
            echo "crate_name=zlayer-overlay" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == init-v* ]]; then
            echo "crate_name=zlayer-init-actions" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == scheduler-v* ]]; then
            echo "crate_name=zlayer-scheduler" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == storage-v* ]]; then
            echo "crate_name=zlayer-storage" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == rust-sdk-v* ]]; then
            echo "sdk_name=rust" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == py-sdk-v* ]]; then
            echo "sdk_name=python" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == ts-sdk-v* ]]; then
            echo "sdk_name=typescript" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == go-sdk-v* ]]; then
            echo "sdk_name=go" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == c-sdk-v* ]]; then
            echo "sdk_name=c" >> $GITHUB_OUTPUT
          fi

  # ===========================================
  # Build binaries (sequential, fail-fast)
  # ===========================================
  build-linux:
    needs: detect
    if: needs.detect.outputs.binary == 'true'
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - arch: amd64
            target: x86_64-unknown-linux-gnu
          - arch: arm64
            target: aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install cross
        run: cargo install cross
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Build (with docker + wasm features)
        run: cross build --release --target ${{ matrix.target }} --package runtime --features "docker,wasm"
      - name: Package
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          tar czf "zlayer-linux-${{ matrix.arch }}.tar.gz" -C target/${{ matrix.target }}/release zlayer
      - name: Upload to Forgejo Packages
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          curl --fail --user "${{ secrets.FORGEJO_USER }}:${{ secrets.FORGEJO_TOKEN }}" \
            --upload-file "zlayer-linux-${{ matrix.arch }}.tar.gz" \
            "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer/${VERSION}/zlayer-linux-${{ matrix.arch }}.tar.gz"

  build-macos:
    needs: [detect, build-linux]
    if: needs.detect.outputs.binary == 'true'
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - target: x86_64-apple-darwin
            artifact: darwin-amd64
          - target: aarch64-apple-darwin
            artifact: darwin-arm64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: ${{ matrix.target }}
      - name: Install protobuf
        run: brew install protobuf
      - name: Build (with docker + wasm features)
        run: cargo build --release --target ${{ matrix.target }} --package runtime --features "docker,wasm"
      - name: Package and upload
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          tar czf "zlayer-${{ matrix.artifact }}.tar.gz" -C target/${{ matrix.target }}/release zlayer
          curl --fail --user "${{ secrets.FORGEJO_USER }}:${{ secrets.FORGEJO_TOKEN }}" \
            --upload-file "zlayer-${{ matrix.artifact }}.tar.gz" \
            "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer/${VERSION}/zlayer-${{ matrix.artifact }}.tar.gz"

  # ===========================================
  # Merge to main (AFTER builds succeed)
  # ===========================================
  merge-to-main:
    needs: [detect, build-linux, build-macos]
    if: needs.detect.outputs.binary == 'true' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git merge origin/dev --no-ff -m "Merge dev into main for release ${{ github.ref_name }}"
          git push origin main

  # ===========================================
  # Publish single crate (specific tag)
  # ===========================================
  publish-crate:
    needs: detect
    if: needs.detect.outputs.crate_name != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p ${{ needs.detect.outputs.crate_name }} --allow-dirty

  # ===========================================
  # Smart publish all crates (general tag)
  # Checks each crate's tag vs input version
  # ===========================================
  publish-all-crates:
    needs: detect
    if: needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish crates that need updating
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"

          # Function to compare semver (returns 0 if $1 > $2)
          version_gt() {
            test "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" != "$1"
          }

          # Function to get latest tag version for a crate prefix
          get_latest_tag_version() {
            local prefix="$1"
            git tag -l "${prefix}-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0"
          }

          # Crate name -> tag prefix mapping
          declare -A CRATE_TAGS=(
            ["zlayer-spec"]="spec"
            ["zlayer-observability"]="obs"
            ["zlayer-overlay"]="overlay"
            ["zlayer-storage"]="storage"
            ["zlayer-core"]="core"
            ["zlayer-builder"]="builder"
            ["zlayer-init-actions"]="init"
            ["zlayer-registry"]="registry"
            ["zlayer-scheduler"]="scheduler"
          )

          # Publish order (dependency order)
          CRATES="zlayer-spec zlayer-observability zlayer-overlay zlayer-storage zlayer-core zlayer-builder zlayer-init-actions zlayer-registry zlayer-scheduler"

          for crate in $CRATES; do
            prefix="${CRATE_TAGS[$crate]}"
            latest_tag=$(get_latest_tag_version "$prefix")

            echo "Checking $crate: latest tag=$latest_tag, input=$INPUT_VERSION"

            if [[ "$latest_tag" == "0.0.0" ]] || version_gt "$INPUT_VERSION" "$latest_tag"; then
              echo "Publishing $crate (tag $latest_tag < input $INPUT_VERSION)..."
              if cargo publish -p "$crate" --allow-dirty; then
                echo "Successfully published $crate"
                # Create tag for this crate
                git tag "${prefix}-v${INPUT_VERSION}"
                git push origin "${prefix}-v${INPUT_VERSION}" || true
              else
                echo "Failed to publish $crate (may already exist)"
              fi
              sleep 30
            else
              echo "Skipping $crate (tag $latest_tag >= input $INPUT_VERSION)"
            fi
          done

  # ===========================================
  # SDK Publishing
  # ===========================================
  publish-rust-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'rust' || needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Check and publish
        working-directory: clients/zlayer-sdk/rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "rust-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")

          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing rust-sdk (tag $LATEST_TAG < input $INPUT_VERSION)..."
            cargo publish --allow-dirty || echo "May already exist"
          else
            echo "Skipping rust-sdk (tag $LATEST_TAG >= input $INPUT_VERSION)"
          fi

  publish-python-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'python' || needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check and publish
        working-directory: clients/zlayer-sdk/python
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "py-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")

          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing python-sdk (tag $LATEST_TAG < input $INPUT_VERSION)..."
            pip install build twine
            python -m build
            twine upload dist/* || echo "May already exist"
          else
            echo "Skipping python-sdk (tag $LATEST_TAG >= input $INPUT_VERSION)"
          fi

  publish-typescript-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'typescript' || needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Check and publish
        working-directory: clients/zlayer-sdk/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "ts-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")

          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing typescript-sdk (tag $LATEST_TAG < input $INPUT_VERSION)..."
            npm ci
            npm run build
            npm publish --access public || echo "May already exist"
          else
            echo "Skipping typescript-sdk (tag $LATEST_TAG >= input $INPUT_VERSION)"
          fi

  publish-go-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'go' || needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Verify Go module
        working-directory: clients/zlayer-sdk/go
        run: go mod verify

  publish-c-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'c' || needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      - name: Verify C SDK builds
        working-directory: clients/zlayer-sdk/c
        run: |
          cmake -B build
          cmake --build build

  # ===========================================
  # Docker (after merge)
  # ===========================================
  docker:
    needs: [detect, merge-to-main]
    if: needs.detect.outputs.docker == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.zlayer-node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zlayer/zlayer-node:${{ needs.detect.outputs.version }}
            zlayer/zlayer-node:latest
            ghcr.io/blackleafdigital/zlayer-node:${{ needs.detect.outputs.version }}
            ghcr.io/blackleafdigital/zlayer-node:latest

  # ===========================================
  # Trigger GitHub mirror
  # ===========================================
  trigger-github:
    needs: [detect, build-linux, build-macos, docker, publish-crate, publish-all-crates, publish-rust-sdk, publish-python-sdk, publish-typescript-sdk, publish-go-sdk, publish-c-sdk]
    if: always() && (needs.build-linux.result == 'success' && needs.build-macos.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Actions
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/BlackLeafDigital/ZLayer/actions/workflows/release.yml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{ github.ref_name }}"}}'
