name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
      sha:
        description: 'Commit SHA for the release'
        required: false
        type: string
      artifact_base_url:
        description: 'Base URL for temp artifact packages from build workflow'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  # ===========================================
  # Detect release type
  # ===========================================
  detect:
    runs-on: ubuntu-latest
    outputs:
      binary: ${{ steps.check.outputs.binary }}
      crate_name: ${{ steps.check.outputs.crate_name }}
      sdk_name: ${{ steps.check.outputs.sdk_name }}
      docker: ${{ steps.check.outputs.docker }}
      is_major: ${{ steps.check.outputs.is_major }}
      is_general: ${{ steps.check.outputs.is_general }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - name: Detect release type
        id: check
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
            TAG="${{ inputs.version }}"
          else
            TAG="${{ github.ref_name }}"
          fi
          VERSION=$(echo "$TAG" | grep -oP '\d+\.\d+\.\d+' || echo "0.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [[ "$TAG" == major-v* ]]; then
            echo "is_major=true" >> $GITHUB_OUTPUT
            echo "is_general=true" >> $GITHUB_OUTPUT
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == v[0-9]* ]]; then
            echo "is_general=true" >> $GITHUB_OUTPUT
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == docker-v* ]]; then
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == spec-v* ]]; then
            echo "crate_name=zlayer-spec" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == core-v* ]]; then
            echo "crate_name=zlayer-core" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == registry-v* ]]; then
            echo "crate_name=zlayer-registry" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == obs-v* ]]; then
            echo "crate_name=zlayer-observability" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == builder-v* ]]; then
            echo "crate_name=zlayer-builder" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == overlay-v* ]]; then
            echo "crate_name=zlayer-overlay" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == init-v* ]]; then
            echo "crate_name=zlayer-init-actions" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == scheduler-v* ]]; then
            echo "crate_name=zlayer-scheduler" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == storage-v* ]]; then
            echo "crate_name=zlayer-storage" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == tunnel-v* ]]; then
            echo "crate_name=zlayer-tunnel" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == rust-sdk-v* ]]; then
            echo "sdk_name=rust" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == py-sdk-v* ]]; then
            echo "sdk_name=python" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == ts-sdk-v*  ]]; then
            echo "sdk_name=typescript" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == go-sdk-v* ]]; then
            echo "sdk_name=go" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == c-sdk-v* ]]; then
            echo "sdk_name=c" >> $GITHUB_OUTPUT
          fi

  # ===========================================
  # Upload binaries to registry (download from temp packages)
  # ===========================================
  upload-binaries:
    needs: [detect]
    if: needs.detect.outputs.binary == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from temp storage
        run: |
          BASE_URL="${{ inputs.artifact_base_url }}"
          mkdir -p artifacts

          for name in zlayer-linux-amd64 zlayer-linux-arm64 zlayer-darwin-amd64 zlayer-darwin-arm64; do
            echo "Downloading ${name}.tar.gz from temp storage..."
            curl -L --fail \
              --user "zachhandley:${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
              -o "artifacts/${name}.tar.gz" \
              "${BASE_URL}/${name}.tar.gz"
          done

      - name: Upload to Forgejo Packages
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          for artifact in artifacts/*.tar.gz; do
            filename=$(basename "$artifact")
            echo "Uploading $filename to final location..."
            curl --fail --user "zachhandley:${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
              --upload-file "$artifact" \
              "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer/${VERSION}/${filename}"
          done

      - name: Cleanup temp packages
        if: always()
        run: |
          # Extract run_id from the artifact URL and delete temp packages
          RUN_ID=$(echo "${{ inputs.artifact_base_url }}" | grep -oP 'zlayer-temp/\K[^/]+')
          echo "Cleaning up temp packages for run_id: ${RUN_ID}"
          curl -X DELETE \
            --user "zachhandley:${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer-temp/${RUN_ID}" || true

  # ===========================================
  # Merge to main (after binaries uploaded)
  # ===========================================
  merge-to-main:
    needs: [detect, upload-binaries]
    if: needs.detect.outputs.binary == 'true' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

      - name: Merge dev into main
        run: |
          git checkout main
          # Use -X theirs to prefer dev changes on conflicts
          git merge origin/dev --no-ff -X theirs -m "Merge dev into main for release ${{ github.ref_name }}"
          git push origin main

  # ===========================================
  # Publish single crate (specific crate tag only)
  # ===========================================
  publish-crate:
    needs: detect
    if: needs.detect.outputs.crate_name != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p ${{ needs.detect.outputs.crate_name }} --allow-dirty

  # ===========================================
  # Publish all crates (general release, after merge)
  # ===========================================
  publish-all-crates:
    needs: [detect, upload-binaries, merge-to-main]
    if: needs.detect.outputs.is_general == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish crates that need updating
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"

          version_gt() {
            test "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" != "$1"
          }

          get_latest_tag_version() {
            local prefix="$1"
            git tag -l "${prefix}-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0"
          }

          declare -A CRATE_TAGS=(
            ["zlayer-spec"]="spec"
            ["zlayer-observability"]="obs"
            ["zlayer-overlay"]="overlay"
            ["zlayer-storage"]="storage"
            ["zlayer-core"]="core"
            ["zlayer-builder"]="builder"
            ["zlayer-init-actions"]="init"
            ["zlayer-registry"]="registry"
            ["zlayer-scheduler"]="scheduler"
            ["zlayer-tunnel"]="tunnel"
          )

          CRATES="zlayer-spec zlayer-observability zlayer-overlay zlayer-storage zlayer-core zlayer-builder zlayer-init-actions zlayer-registry zlayer-scheduler zlayer-tunnel"

          for crate in $CRATES; do
            prefix="${CRATE_TAGS[$crate]}"
            latest_tag=$(get_latest_tag_version "$prefix")

            echo "Checking $crate: latest tag=$latest_tag, input=$INPUT_VERSION"

            if [[ "$latest_tag" == "0.0.0" ]] || version_gt "$INPUT_VERSION" "$latest_tag"; then
              echo "Publishing $crate..."
              if cargo publish -p "$crate" --allow-dirty; then
                echo "Successfully published $crate"
                git tag "${prefix}-v${INPUT_VERSION}"
                git push origin "${prefix}-v${INPUT_VERSION}" || true
              else
                echo "Failed to publish $crate (may already exist)"
              fi
              sleep 30
            else
              echo "Skipping $crate (already at or above $INPUT_VERSION)"
            fi
          done

  # ===========================================
  # SDK Publishing
  # ===========================================
  publish-rust-sdk:
    needs: [detect, upload-binaries, merge-to-main]
    if: |
      needs.detect.outputs.sdk_name == 'rust' ||
      (needs.detect.outputs.is_general == 'true' && needs.merge-to-main.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
      - name: Check and publish
        working-directory: clients/zlayer-sdk/rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "rust-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")
          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing rust-sdk..."
            cargo publish --allow-dirty || echo "May already exist"
          else
            echo "Skipping rust-sdk (already at or above $INPUT_VERSION)"
          fi

  publish-python-sdk:
    needs: [detect, upload-binaries, merge-to-main]
    if: |
      needs.detect.outputs.sdk_name == 'python' ||
      (needs.detect.outputs.is_general == 'true' && needs.merge-to-main.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check and publish
        working-directory: clients/zlayer-sdk/python
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "py-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")
          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing python-sdk..."
            # Update version in pyproject.toml and __init__.py
            sed -i "s/^version = .*/version = \"$INPUT_VERSION\"/" pyproject.toml
            sed -i "s/__version__ = .*/__version__ = \"$INPUT_VERSION\"/" zlayer/__init__.py
            pip install build twine
            python -m build
            twine upload dist/* || echo "May already exist"
          else
            echo "Skipping python-sdk (already at or above $INPUT_VERSION)"
          fi

  publish-typescript-sdk:
    needs: [detect, upload-binaries, merge-to-main]
    if: |
      needs.detect.outputs.sdk_name == 'typescript' ||
      (needs.detect.outputs.is_general == 'true' && needs.merge-to-main.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Check and publish
        working-directory: clients/zlayer-sdk/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          INPUT_VERSION="${{ needs.detect.outputs.version }}"
          LATEST_TAG=$(git tag -l "ts-sdk-v*" | grep -oP '\d+\.\d+\.\d+' | sort -V | tail -n1 || echo "0.0.0")
          if [[ "$LATEST_TAG" == "" ]] || [[ "$(printf '%s\n' "$INPUT_VERSION" "$LATEST_TAG" | sort -V | head -n1)" != "$INPUT_VERSION" ]]; then
            echo "Publishing typescript-sdk..."
            # Update version in package.json
            npm version "$INPUT_VERSION" --no-git-tag-version
            npm ci
            npm run build
            npm publish --access public || echo "May already exist"
          else
            echo "Skipping typescript-sdk (already at or above $INPUT_VERSION)"
          fi

  publish-go-sdk:
    needs: [detect, upload-binaries, merge-to-main]
    if: |
      needs.detect.outputs.sdk_name == 'go' ||
      (needs.detect.outputs.is_general == 'true' && needs.merge-to-main.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Verify Go module
        working-directory: clients/zlayer-sdk/go
        run: go mod verify

  publish-c-sdk:
    needs: [detect, upload-binaries, merge-to-main]
    if: |
      needs.detect.outputs.sdk_name == 'c' ||
      (needs.detect.outputs.is_general == 'true' && needs.merge-to-main.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.ref }}
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      - name: Verify C SDK builds
        working-directory: clients/zlayer-sdk/c
        run: |
          cmake -B build
          cmake --build build

  # ===========================================
  # Docker (after merge)
  # ===========================================
  docker:
    needs: [detect, merge-to-main]
    if: needs.detect.outputs.docker == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.zlayer-node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zlayer/zlayer-node:${{ needs.detect.outputs.version }}
            zlayer/zlayer-node:latest
            ghcr.io/blackleafdigital/zlayer-node:${{ needs.detect.outputs.version }}
            ghcr.io/blackleafdigital/zlayer-node:latest

  # ===========================================
  # Trigger GitHub release
  # ===========================================
  trigger-github:
    needs: [detect, upload-binaries, merge-to-main, docker, publish-all-crates]
    if: always() && needs.detect.outputs.is_general == 'true' && needs.upload-binaries.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Actions
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/BlackLeafDigital/ZLayer/actions/workflows/release.yml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{ needs.detect.outputs.version }}"}}'
