name: Release

on:
  push:
    tags:
      - 'v*'
      - 'spec-v*'
      - 'core-v*'
      - 'registry-v*'
      - 'obs-v*'
      - 'builder-v*'
      - 'overlay-v*'
      - 'init-v*'
      - 'scheduler-v*'
      - 'storage-v*'
      - 'rust-sdk-v*'
      - 'py-sdk-v*'
      - 'ts-sdk-v*'
      - 'go-sdk-v*'
      - 'c-sdk-v*'
      - 'docker-v*'
      - 'major-v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      binary: ${{ steps.check.outputs.binary }}
      crate_name: ${{ steps.check.outputs.crate_name }}
      sdk_name: ${{ steps.check.outputs.sdk_name }}
      docker: ${{ steps.check.outputs.docker }}
      is_major: ${{ steps.check.outputs.is_major }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - id: check
        run: |
          TAG="${{ github.ref_name }}"
          VERSION=$(echo "$TAG" | grep -oP '\d+\.\d+\.\d+' || echo "0.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [[ "$TAG" == major-v* ]]; then
            echo "is_major=true" >> $GITHUB_OUTPUT
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == v[0-9]* ]]; then
            echo "binary=true" >> $GITHUB_OUTPUT
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == docker-v* ]]; then
            echo "docker=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == spec-v* ]]; then
            echo "crate_name=zlayer-spec" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == core-v* ]]; then
            echo "crate_name=zlayer-core" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == registry-v* ]]; then
            echo "crate_name=zlayer-registry" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == obs-v* ]]; then
            echo "crate_name=zlayer-observability" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == builder-v* ]]; then
            echo "crate_name=zlayer-builder" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == overlay-v* ]]; then
            echo "crate_name=zlayer-overlay" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == init-v* ]]; then
            echo "crate_name=zlayer-init-actions" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == scheduler-v* ]]; then
            echo "crate_name=zlayer-scheduler" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == storage-v* ]]; then
            echo "crate_name=zlayer-storage" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == rust-sdk-v* ]]; then
            echo "sdk_name=rust" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == py-sdk-v* ]]; then
            echo "sdk_name=python" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == ts-sdk-v* ]]; then
            echo "sdk_name=typescript" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == go-sdk-v* ]]; then
            echo "sdk_name=go" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == c-sdk-v* ]]; then
            echo "sdk_name=c" >> $GITHUB_OUTPUT
          fi

  merge-to-main:
    needs: detect
    if: needs.detect.outputs.binary == 'true' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev --no-ff -m "Merge dev into main for release ${{ github.ref_name }}"
          git push origin main

  build-linux:
    needs: [detect, merge-to-main]
    if: needs.detect.outputs.binary == 'true'
    strategy:
      matrix:
        include:
          - arch: amd64
            target: x86_64-unknown-linux-gnu
          - arch: arm64
            target: aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
      - name: Install cross
        run: cargo install cross
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libseccomp-dev
      - name: Build (with docker + wasm features)
        run: cross build --release --target ${{ matrix.target }} --package runtime --features "docker,wasm"
      - name: Package
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          tar czf "zlayer-linux-${{ matrix.arch }}.tar.gz" -C target/${{ matrix.target }}/release zlayer
      - name: Upload to Forgejo Packages
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          curl --user "${{ secrets.FORGEJO_USER }}:${{ secrets.FORGEJO_TOKEN }}" \
            --upload-file "zlayer-linux-${{ matrix.arch }}.tar.gz" \
            "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer/${VERSION}/zlayer-linux-${{ matrix.arch }}.tar.gz"

  build-macos:
    needs: [detect, merge-to-main]
    if: needs.detect.outputs.binary == 'true'
    strategy:
      matrix:
        include:
          - os: macos-13
            target: x86_64-apple-darwin
            artifact: darwin-amd64
          - os: macos-14
            target: aarch64-apple-darwin
            artifact: darwin-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Install protobuf
        run: brew install protobuf
      - name: Build (with docker + wasm features)
        run: cargo build --release --target ${{ matrix.target }} --package runtime --features "docker,wasm"
      - name: Package and upload
        run: |
          VERSION="${{ needs.detect.outputs.version }}"
          tar czf "zlayer-${{ matrix.artifact }}.tar.gz" -C target/${{ matrix.target }}/release zlayer
          curl --user "${{ secrets.FORGEJO_USER }}:${{ secrets.FORGEJO_TOKEN }}" \
            --upload-file "zlayer-${{ matrix.artifact }}.tar.gz" \
            "https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer/${VERSION}/zlayer-${{ matrix.artifact }}.tar.gz"

  publish-crate:
    needs: detect
    if: needs.detect.outputs.crate_name != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p ${{ needs.detect.outputs.crate_name }} --allow-dirty

  publish-all-crates:
    needs: detect
    if: needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libseccomp-dev protobuf-compiler
      - name: Publish all in dependency order
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          CRATES="zlayer-spec zlayer-observability zlayer-overlay zlayer-storage zlayer-core zlayer-builder zlayer-init-actions zlayer-registry zlayer-scheduler"
          for crate in $CRATES; do
            echo "Publishing $crate..."
            cargo publish -p $crate --allow-dirty || true
            sleep 30
          done

  publish-rust-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'rust' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          toolchain: stable
      - name: Publish
        working-directory: clients/zlayer-sdk/rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --allow-dirty

  publish-python-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'python' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build and publish
        working-directory: clients/zlayer-sdk/python
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install build twine
          python -m build
          twine upload dist/*

  publish-typescript-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'typescript' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        working-directory: clients/zlayer-sdk/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish --access public

  publish-go-sdk:
    needs: detect
    if: needs.detect.outputs.sdk_name == 'go' || needs.detect.outputs.is_major == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Verify Go module
        working-directory: clients/zlayer-sdk/go
        run: go mod verify

  docker:
    needs: [detect, merge-to-main, build-linux]
    if: needs.detect.outputs.docker == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.zlayer-node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zlayer/zlayer-node:${{ needs.detect.outputs.version }}
            zlayer/zlayer-node:latest
            ghcr.io/blackleafdigital/zlayer-node:${{ needs.detect.outputs.version }}
            ghcr.io/blackleafdigital/zlayer-node:latest

  trigger-github:
    needs: [build-linux, build-macos, docker, publish-crate, publish-all-crates, publish-rust-sdk, publish-python-sdk, publish-typescript-sdk, publish-go-sdk]
    if: always() && (needs.build-linux.result == 'success' || needs.build-macos.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Actions
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/BlackLeafDigital/ZLayer/actions/workflows/release.yml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{ github.ref_name }}"}}'
