name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            name: linux-amd64
            cross: false
          - target: aarch64-unknown-linux-gnu
            name: linux-arm64
            cross: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev

      - name: Install cross-compilation tools
        if: matrix.cross
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          # For libseccomp cross-compilation
          sudo apt-get install -y libseccomp-dev:arm64 || true

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main
        with:
          targets: ${{ matrix.target }}

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Configure cross-compilation
        if: matrix.cross
        run: |
          mkdir -p .cargo
          cat >> .cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build release binaries
        run: |
          cargo build --release --target ${{ matrix.target }} --package runtime
          cargo build --release --target ${{ matrix.target }} --package devctl

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/zlayer release/
          cp target/${{ matrix.target }}/release/devctl release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ github.ref_name }}-${{ matrix.name }}.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-${{ matrix.name }}
          path: zlayer-${{ github.ref_name }}-${{ matrix.name }}.tar.gz

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Download all artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: https://github.com/softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
