name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-amd64:
    name: Build Release (linux-amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev libssl-dev pkg-config

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build release binaries
        run: |
          cargo build --release --package runtime
          cargo build --release --package devctl

      - name: Create release archive
        run: |
          echo "PWD: $(pwd)"
          echo "Looking for binaries..."
          find . -name "zlayer" -type f 2>/dev/null || echo "zlayer not found"
          find . -name "devctl" -type f 2>/dev/null || echo "devctl not found"
          ls -la target/release/ || echo "target/release not found"
          mkdir -p release
          cp target/release/zlayer release/
          cp target/release/devctl release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-amd64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz

  build-arm64:
    name: Build Release (linux-arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build in Docker container
        run: |
          echo "Building in: $GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE"
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/workspace \
            -w /workspace \
            --platform linux/arm64 \
            rust:latest bash -c "
              ls -la /workspace
              apt-get update && apt-get install -y protobuf-compiler libseccomp-dev libssl-dev pkg-config
              cargo build --release --package runtime
              cargo build --release --package devctl
            "
          # Fix permissions on target dir (Docker runs as root)
          sudo chown -R $(id -u):$(id -g) target 2>/dev/null || true

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/release/zlayer release/
          cp target/release/devctl release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-arm64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Download all artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: https://github.com/softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
