name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-amd64:
    name: Build Release (linux-amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libseccomp-dev libssl-dev pkg-config

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build release binaries
        run: |
          cargo build --release --package runtime

      - name: Create release archive
        run: |
          mkdir -p release
          cp "${CARGO_TARGET_DIR}/release/zlayer" release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-amd64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-amd64.tar.gz

  build-arm64:
    name: Build Release (linux-arm64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build in Docker container
        run: |
          docker build --platform linux/arm64 -f docker/Dockerfile.arm64-builder -t zlayer-arm64-build .
          # Extract binaries from the image
          CONTAINER=$(docker create zlayer-arm64-build)
          mkdir -p target/release
          docker cp "${CONTAINER}:/output/zlayer" target/release/
          docker rm "${CONTAINER}"

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/release/zlayer release/
          cp README.md release/ 2>/dev/null || true
          cp LICENSE* release/ 2>/dev/null || true
          cd release && tar -czvf ../zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz *

      - name: Upload artifact
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: zlayer-linux-arm64
          path: zlayer-${{ inputs.version || github.ref_name }}-linux-arm64.tar.gz

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    env:
      VERSION: ${{ inputs.version || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag if manual dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Download all artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Publish to Package Registry
        run: |
          BASE_URL="https://forge.blackleafdigital.com/api/packages/BlackLeafDigital/generic/zlayer"
          AUTH_HEADER="Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}"

          for arch in amd64 arm64; do
            FILE="artifacts/zlayer-linux-${arch}/zlayer-${VERSION}-linux-${arch}.tar.gz"

            # Versioned release - delete if exists, then upload
            curl -X DELETE -H "$AUTH_HEADER" "${BASE_URL}/${VERSION}/zlayer-linux-${arch}.tar.gz" || true
            curl --fail -X PUT -H "$AUTH_HEADER" --upload-file "$FILE" "${BASE_URL}/${VERSION}/zlayer-linux-${arch}.tar.gz"

            # Latest - delete if exists, then upload
            curl -X DELETE -H "$AUTH_HEADER" "${BASE_URL}/latest/zlayer-linux-${arch}.tar.gz" || true
            curl --fail -X PUT -H "$AUTH_HEADER" --upload-file "$FILE" "${BASE_URL}/latest/zlayer-linux-${arch}.tar.gz"
          done

      - name: Create Release
        uses: https://github.com/softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version || github.ref_name }}
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
