/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncApplyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncApplyResponse{}

// SyncApplyResponse Response for a real apply. Reports per-resource outcomes, the current commit SHA the sync was applied at (when known), and a short human-readable summary for CLI display.  NOTE: This is a breaking change from the previous dry-run-only `{ diff, message }` shape. Clients inspecting the apply response directly must be updated — callers that only consumed the HTTP status stay working.
type SyncApplyResponse struct {
	// Commit SHA the sync was applied against (when resolvable).
	AppliedSha NullableString `json:"applied_sha,omitempty"`
	// Per-resource reconcile results.
	Results []SyncResourceResult `json:"results"`
	// Aggregate summary suitable for CLI output, e.g. `\"3 created, 2 updated, 1 deleted, 0 skipped\"`.
	Summary string `json:"summary"`
}

type _SyncApplyResponse SyncApplyResponse

// NewSyncApplyResponse instantiates a new SyncApplyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncApplyResponse(results []SyncResourceResult, summary string) *SyncApplyResponse {
	this := SyncApplyResponse{}
	this.Results = results
	this.Summary = summary
	return &this
}

// NewSyncApplyResponseWithDefaults instantiates a new SyncApplyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncApplyResponseWithDefaults() *SyncApplyResponse {
	this := SyncApplyResponse{}
	return &this
}

// GetAppliedSha returns the AppliedSha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SyncApplyResponse) GetAppliedSha() string {
	if o == nil || IsNil(o.AppliedSha.Get()) {
		var ret string
		return ret
	}
	return *o.AppliedSha.Get()
}

// GetAppliedShaOk returns a tuple with the AppliedSha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SyncApplyResponse) GetAppliedShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppliedSha.Get(), o.AppliedSha.IsSet()
}

// HasAppliedSha returns a boolean if a field has been set.
func (o *SyncApplyResponse) HasAppliedSha() bool {
	if o != nil && o.AppliedSha.IsSet() {
		return true
	}

	return false
}

// SetAppliedSha gets a reference to the given NullableString and assigns it to the AppliedSha field.
func (o *SyncApplyResponse) SetAppliedSha(v string) {
	o.AppliedSha.Set(&v)
}
// SetAppliedShaNil sets the value for AppliedSha to be an explicit nil
func (o *SyncApplyResponse) SetAppliedShaNil() {
	o.AppliedSha.Set(nil)
}

// UnsetAppliedSha ensures that no value is present for AppliedSha, not even an explicit nil
func (o *SyncApplyResponse) UnsetAppliedSha() {
	o.AppliedSha.Unset()
}

// GetResults returns the Results field value
func (o *SyncApplyResponse) GetResults() []SyncResourceResult {
	if o == nil {
		var ret []SyncResourceResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *SyncApplyResponse) GetResultsOk() ([]SyncResourceResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *SyncApplyResponse) SetResults(v []SyncResourceResult) {
	o.Results = v
}

// GetSummary returns the Summary field value
func (o *SyncApplyResponse) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *SyncApplyResponse) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *SyncApplyResponse) SetSummary(v string) {
	o.Summary = v
}

func (o SyncApplyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncApplyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AppliedSha.IsSet() {
		toSerialize["applied_sha"] = o.AppliedSha.Get()
	}
	toSerialize["results"] = o.Results
	toSerialize["summary"] = o.Summary
	return toSerialize, nil
}

func (o *SyncApplyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncApplyResponse := _SyncApplyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncApplyResponse)

	if err != nil {
		return err
	}

	*o = SyncApplyResponse(varSyncApplyResponse)

	return err
}

type NullableSyncApplyResponse struct {
	value *SyncApplyResponse
	isSet bool
}

func (v NullableSyncApplyResponse) Get() *SyncApplyResponse {
	return v.value
}

func (v *NullableSyncApplyResponse) Set(val *SyncApplyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncApplyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncApplyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncApplyResponse(val *SyncApplyResponse) *NullableSyncApplyResponse {
	return &NullableSyncApplyResponse{value: val, isSet: true}
}

func (v NullableSyncApplyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncApplyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


