/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"fmt"
)

// VolumeMountType Volume mount kind discriminator.  Selects which [`zlayer_spec::StorageSpec`] variant [`VolumeMount`] is translated into by [`build_service_spec`]. When omitted on the wire, defaults to [`VolumeMountType::Bind`] (legacy behavior).
type VolumeMountType string

// List of VolumeMountType
const (
	VOLUMEMOUNTTYPE_BIND VolumeMountType = "bind"
	VOLUMEMOUNTTYPE_VOLUME VolumeMountType = "volume"
	VOLUMEMOUNTTYPE_TMPFS VolumeMountType = "tmpfs"
)

// All allowed values of VolumeMountType enum
var AllowedVolumeMountTypeEnumValues = []VolumeMountType{
	"bind",
	"volume",
	"tmpfs",
}

func (v *VolumeMountType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VolumeMountType(value)
	for _, existing := range AllowedVolumeMountTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VolumeMountType", value)
}

// NewVolumeMountTypeFromValue returns a pointer to a valid VolumeMountType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVolumeMountTypeFromValue(v string) (*VolumeMountType, error) {
	ev := VolumeMountType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VolumeMountType: valid values are %v", v, AllowedVolumeMountTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VolumeMountType) IsValid() bool {
	for _, existing := range AllowedVolumeMountTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VolumeMountType value
func (v VolumeMountType) Ptr() *VolumeMountType {
	return &v
}

type NullableVolumeMountType struct {
	value *VolumeMountType
	isSet bool
}

func (v NullableVolumeMountType) Get() *VolumeMountType {
	return v.value
}

func (v *NullableVolumeMountType) Set(val *VolumeMountType) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeMountType) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeMountType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeMountType(val *VolumeMountType) *NullableVolumeMountType {
	return &NullableVolumeMountType{value: val, isSet: true}
}

func (v NullableVolumeMountType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeMountType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

