/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForceLeaderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForceLeaderRequest{}

// ForceLeaderRequest Request body for force-leader operation.
type ForceLeaderRequest struct {
	// Confirmation string -- must be `\"CONFIRM_FORCE_LEADER\"` to prevent accidents
	Confirm string `json:"confirm"`
}

type _ForceLeaderRequest ForceLeaderRequest

// NewForceLeaderRequest instantiates a new ForceLeaderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForceLeaderRequest(confirm string) *ForceLeaderRequest {
	this := ForceLeaderRequest{}
	this.Confirm = confirm
	return &this
}

// NewForceLeaderRequestWithDefaults instantiates a new ForceLeaderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForceLeaderRequestWithDefaults() *ForceLeaderRequest {
	this := ForceLeaderRequest{}
	return &this
}

// GetConfirm returns the Confirm field value
func (o *ForceLeaderRequest) GetConfirm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Confirm
}

// GetConfirmOk returns a tuple with the Confirm field value
// and a boolean to check if the value has been set.
func (o *ForceLeaderRequest) GetConfirmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confirm, true
}

// SetConfirm sets field value
func (o *ForceLeaderRequest) SetConfirm(v string) {
	o.Confirm = v
}

func (o ForceLeaderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForceLeaderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["confirm"] = o.Confirm
	return toSerialize, nil
}

func (o *ForceLeaderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"confirm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForceLeaderRequest := _ForceLeaderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForceLeaderRequest)

	if err != nil {
		return err
	}

	*o = ForceLeaderRequest(varForceLeaderRequest)

	return err
}

type NullableForceLeaderRequest struct {
	value *ForceLeaderRequest
	isSet bool
}

func (v NullableForceLeaderRequest) Get() *ForceLeaderRequest {
	return v.value
}

func (v *NullableForceLeaderRequest) Set(val *ForceLeaderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableForceLeaderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableForceLeaderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForceLeaderRequest(val *ForceLeaderRequest) *NullableForceLeaderRequest {
	return &NullableForceLeaderRequest{value: val, isSet: true}
}

func (v NullableForceLeaderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForceLeaderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


