/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthCheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheckRequest{}

// HealthCheckRequest Container health check request.  Mirrors the on-disk `HealthCheck` enum (see `zlayer_spec::HealthCheck`) as a discriminated union keyed on `type`. Translated to `zlayer_spec::HealthSpec` by `HealthCheckRequest::to_health_spec`. Durations are humantime strings (for example `\"10s\"`, `\"500ms\"`, `\"1m\"`).  ## Variants - `type: \"tcp\"` — requires `port` (1-65535). - `type: \"http\"` — requires `url`; `expect_status` defaults to 200. - `type: \"command\"` — requires `command` (array of argv tokens; joined with   spaces and passed to `sh -c` by the health monitor, matching the existing   compose-to-ZLayer conversion in `zlayer-docker`).
type HealthCheckRequest struct {
	// Command argv (required when `type == \"command\"`). Joined with spaces and passed to `sh -c`.
	Command []string `json:"command,omitempty"`
	// HTTP status code expected from `url` (defaults to 200).
	ExpectStatus NullableInt32 `json:"expect_status,omitempty"`
	// Interval between checks, humantime format (e.g. `\"30s\"`). Defaults to 30s.
	Interval NullableString `json:"interval,omitempty"`
	// TCP port (required when `type == \"tcp\"`).
	Port NullableInt32 `json:"port,omitempty"`
	// Number of consecutive failures before marking unhealthy. Defaults to 3.
	Retries NullableInt32 `json:"retries,omitempty"`
	// Grace period before the first check runs, humantime format. Maps to `HealthSpec::start_grace`.
	StartPeriod NullableString `json:"start_period,omitempty"`
	// Timeout per individual check, humantime format.
	Timeout NullableString `json:"timeout,omitempty"`
	// Check variant: `\"tcp\"`, `\"http\"`, or `\"command\"`.
	Type string `json:"type"`
	// HTTP URL (required when `type == \"http\"`).
	Url NullableString `json:"url,omitempty"`
}

type _HealthCheckRequest HealthCheckRequest

// NewHealthCheckRequest instantiates a new HealthCheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckRequest(type_ string) *HealthCheckRequest {
	this := HealthCheckRequest{}
	this.Type = type_
	return &this
}

// NewHealthCheckRequestWithDefaults instantiates a new HealthCheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckRequestWithDefaults() *HealthCheckRequest {
	this := HealthCheckRequest{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *HealthCheckRequest) SetCommand(v []string) {
	o.Command = v
}

// GetExpectStatus returns the ExpectStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetExpectStatus() int32 {
	if o == nil || IsNil(o.ExpectStatus.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpectStatus.Get()
}

// GetExpectStatusOk returns a tuple with the ExpectStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetExpectStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectStatus.Get(), o.ExpectStatus.IsSet()
}

// HasExpectStatus returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasExpectStatus() bool {
	if o != nil && o.ExpectStatus.IsSet() {
		return true
	}

	return false
}

// SetExpectStatus gets a reference to the given NullableInt32 and assigns it to the ExpectStatus field.
func (o *HealthCheckRequest) SetExpectStatus(v int32) {
	o.ExpectStatus.Set(&v)
}
// SetExpectStatusNil sets the value for ExpectStatus to be an explicit nil
func (o *HealthCheckRequest) SetExpectStatusNil() {
	o.ExpectStatus.Set(nil)
}

// UnsetExpectStatus ensures that no value is present for ExpectStatus, not even an explicit nil
func (o *HealthCheckRequest) UnsetExpectStatus() {
	o.ExpectStatus.Unset()
}

// GetInterval returns the Interval field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetInterval() string {
	if o == nil || IsNil(o.Interval.Get()) {
		var ret string
		return ret
	}
	return *o.Interval.Get()
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Interval.Get(), o.Interval.IsSet()
}

// HasInterval returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasInterval() bool {
	if o != nil && o.Interval.IsSet() {
		return true
	}

	return false
}

// SetInterval gets a reference to the given NullableString and assigns it to the Interval field.
func (o *HealthCheckRequest) SetInterval(v string) {
	o.Interval.Set(&v)
}
// SetIntervalNil sets the value for Interval to be an explicit nil
func (o *HealthCheckRequest) SetIntervalNil() {
	o.Interval.Set(nil)
}

// UnsetInterval ensures that no value is present for Interval, not even an explicit nil
func (o *HealthCheckRequest) UnsetInterval() {
	o.Interval.Unset()
}

// GetPort returns the Port field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetPort() int32 {
	if o == nil || IsNil(o.Port.Get()) {
		var ret int32
		return ret
	}
	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// HasPort returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasPort() bool {
	if o != nil && o.Port.IsSet() {
		return true
	}

	return false
}

// SetPort gets a reference to the given NullableInt32 and assigns it to the Port field.
func (o *HealthCheckRequest) SetPort(v int32) {
	o.Port.Set(&v)
}
// SetPortNil sets the value for Port to be an explicit nil
func (o *HealthCheckRequest) SetPortNil() {
	o.Port.Set(nil)
}

// UnsetPort ensures that no value is present for Port, not even an explicit nil
func (o *HealthCheckRequest) UnsetPort() {
	o.Port.Unset()
}

// GetRetries returns the Retries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetRetries() int32 {
	if o == nil || IsNil(o.Retries.Get()) {
		var ret int32
		return ret
	}
	return *o.Retries.Get()
}

// GetRetriesOk returns a tuple with the Retries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetRetriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retries.Get(), o.Retries.IsSet()
}

// HasRetries returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasRetries() bool {
	if o != nil && o.Retries.IsSet() {
		return true
	}

	return false
}

// SetRetries gets a reference to the given NullableInt32 and assigns it to the Retries field.
func (o *HealthCheckRequest) SetRetries(v int32) {
	o.Retries.Set(&v)
}
// SetRetriesNil sets the value for Retries to be an explicit nil
func (o *HealthCheckRequest) SetRetriesNil() {
	o.Retries.Set(nil)
}

// UnsetRetries ensures that no value is present for Retries, not even an explicit nil
func (o *HealthCheckRequest) UnsetRetries() {
	o.Retries.Unset()
}

// GetStartPeriod returns the StartPeriod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetStartPeriod() string {
	if o == nil || IsNil(o.StartPeriod.Get()) {
		var ret string
		return ret
	}
	return *o.StartPeriod.Get()
}

// GetStartPeriodOk returns a tuple with the StartPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetStartPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartPeriod.Get(), o.StartPeriod.IsSet()
}

// HasStartPeriod returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasStartPeriod() bool {
	if o != nil && o.StartPeriod.IsSet() {
		return true
	}

	return false
}

// SetStartPeriod gets a reference to the given NullableString and assigns it to the StartPeriod field.
func (o *HealthCheckRequest) SetStartPeriod(v string) {
	o.StartPeriod.Set(&v)
}
// SetStartPeriodNil sets the value for StartPeriod to be an explicit nil
func (o *HealthCheckRequest) SetStartPeriodNil() {
	o.StartPeriod.Set(nil)
}

// UnsetStartPeriod ensures that no value is present for StartPeriod, not even an explicit nil
func (o *HealthCheckRequest) UnsetStartPeriod() {
	o.StartPeriod.Unset()
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetTimeout() string {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret string
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableString and assigns it to the Timeout field.
func (o *HealthCheckRequest) SetTimeout(v string) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *HealthCheckRequest) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *HealthCheckRequest) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetType returns the Type field value
func (o *HealthCheckRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HealthCheckRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HealthCheckRequest) SetType(v string) {
	o.Type = v
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HealthCheckRequest) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HealthCheckRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *HealthCheckRequest) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *HealthCheckRequest) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *HealthCheckRequest) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *HealthCheckRequest) UnsetUrl() {
	o.Url.Unset()
}

func (o HealthCheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Command != nil {
		toSerialize["command"] = o.Command
	}
	if o.ExpectStatus.IsSet() {
		toSerialize["expect_status"] = o.ExpectStatus.Get()
	}
	if o.Interval.IsSet() {
		toSerialize["interval"] = o.Interval.Get()
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	if o.Retries.IsSet() {
		toSerialize["retries"] = o.Retries.Get()
	}
	if o.StartPeriod.IsSet() {
		toSerialize["start_period"] = o.StartPeriod.Get()
	}
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	toSerialize["type"] = o.Type
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	return toSerialize, nil
}

func (o *HealthCheckRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthCheckRequest := _HealthCheckRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthCheckRequest)

	if err != nil {
		return err
	}

	*o = HealthCheckRequest(varHealthCheckRequest)

	return err
}

type NullableHealthCheckRequest struct {
	value *HealthCheckRequest
	isSet bool
}

func (v NullableHealthCheckRequest) Get() *HealthCheckRequest {
	return v.value
}

func (v *NullableHealthCheckRequest) Set(val *HealthCheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckRequest(val *HealthCheckRequest) *NullableHealthCheckRequest {
	return &NullableHealthCheckRequest{value: val, isSet: true}
}

func (v NullableHealthCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


