/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ContainerEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerEvent{}

// ContainerEvent A container lifecycle event published on the bus.
type ContainerEvent struct {
	// Wall-clock time the event was emitted.  Serialized as an RFC 3339 string on the wire.
	At time.Time `json:"at"`
	// Exit code, when known. Populated for `Die` events where a wait has already resolved; otherwise `None`.
	ExitCode NullableInt32 `json:"exit_code,omitempty"`
	// Container identifier (the API's id string, not the raw runtime id).
	Id string `json:"id"`
	// What kind of transition this event represents.
	Kind ContainerEventKind `json:"kind"`
	// Labels on the container at the time of the event. Used by subscribers to filter via the `label=k=v` query param (AND semantics).
	Labels map[string]string `json:"labels,omitempty"`
	// Free-form human-readable reason. For `Die`, may indicate \"stopped\", \"killed\", \"oom-killed\"; for `Oom`, the OOM detail; for `Health`, may echo the probe failure message.
	Reason NullableString `json:"reason,omitempty"`
	// Health status, only populated for `Health` events (e.g. \"healthy\", \"unhealthy\", \"starting\").
	Status NullableString `json:"status,omitempty"`
}

type _ContainerEvent ContainerEvent

// NewContainerEvent instantiates a new ContainerEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerEvent(at time.Time, id string, kind ContainerEventKind) *ContainerEvent {
	this := ContainerEvent{}
	this.At = at
	this.Id = id
	this.Kind = kind
	return &this
}

// NewContainerEventWithDefaults instantiates a new ContainerEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerEventWithDefaults() *ContainerEvent {
	this := ContainerEvent{}
	return &this
}

// GetAt returns the At field value
func (o *ContainerEvent) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *ContainerEvent) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *ContainerEvent) SetAt(v time.Time) {
	o.At = v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerEvent) GetExitCode() int32 {
	if o == nil || IsNil(o.ExitCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ExitCode.Get()
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerEvent) GetExitCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExitCode.Get(), o.ExitCode.IsSet()
}

// HasExitCode returns a boolean if a field has been set.
func (o *ContainerEvent) HasExitCode() bool {
	if o != nil && o.ExitCode.IsSet() {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given NullableInt32 and assigns it to the ExitCode field.
func (o *ContainerEvent) SetExitCode(v int32) {
	o.ExitCode.Set(&v)
}
// SetExitCodeNil sets the value for ExitCode to be an explicit nil
func (o *ContainerEvent) SetExitCodeNil() {
	o.ExitCode.Set(nil)
}

// UnsetExitCode ensures that no value is present for ExitCode, not even an explicit nil
func (o *ContainerEvent) UnsetExitCode() {
	o.ExitCode.Unset()
}

// GetId returns the Id field value
func (o *ContainerEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ContainerEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContainerEvent) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *ContainerEvent) GetKind() ContainerEventKind {
	if o == nil {
		var ret ContainerEventKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ContainerEvent) GetKindOk() (*ContainerEventKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ContainerEvent) SetKind(v ContainerEventKind) {
	o.Kind = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ContainerEvent) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerEvent) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ContainerEvent) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ContainerEvent) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerEvent) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerEvent) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *ContainerEvent) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *ContainerEvent) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *ContainerEvent) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *ContainerEvent) UnsetReason() {
	o.Reason.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerEvent) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerEvent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ContainerEvent) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *ContainerEvent) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *ContainerEvent) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ContainerEvent) UnsetStatus() {
	o.Status.Unset()
}

func (o ContainerEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["at"] = o.At
	if o.ExitCode.IsSet() {
		toSerialize["exit_code"] = o.ExitCode.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	return toSerialize, nil
}

func (o *ContainerEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"at",
		"id",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerEvent := _ContainerEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerEvent)

	if err != nil {
		return err
	}

	*o = ContainerEvent(varContainerEvent)

	return err
}

type NullableContainerEvent struct {
	value *ContainerEvent
	isSet bool
}

func (v NullableContainerEvent) Get() *ContainerEvent {
	return v.value
}

func (v *NullableContainerEvent) Set(val *ContainerEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerEvent(val *ContainerEvent) *NullableContainerEvent {
	return &NullableContainerEvent{value: val, isSet: true}
}

func (v NullableContainerEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


