/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IpAllocationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpAllocationResponse{}

// IpAllocationResponse IP allocation status response
type IpAllocationResponse struct {
	// Number of allocated IPs
	AllocatedCount int32 `json:"allocated_count"`
	// List of allocated IP addresses (only included if requested)
	AllocatedIps []string `json:"allocated_ips,omitempty"`
	// Number of available IPs
	AvailableCount int32 `json:"available_count"`
	// Overlay network CIDR
	Cidr string `json:"cidr"`
	// Total available IPs in the range
	TotalIps int32 `json:"total_ips"`
	// Utilization percentage (0.0 - 100.0)
	UtilizationPercent float64 `json:"utilization_percent"`
}

type _IpAllocationResponse IpAllocationResponse

// NewIpAllocationResponse instantiates a new IpAllocationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpAllocationResponse(allocatedCount int32, availableCount int32, cidr string, totalIps int32, utilizationPercent float64) *IpAllocationResponse {
	this := IpAllocationResponse{}
	this.AllocatedCount = allocatedCount
	this.AvailableCount = availableCount
	this.Cidr = cidr
	this.TotalIps = totalIps
	this.UtilizationPercent = utilizationPercent
	return &this
}

// NewIpAllocationResponseWithDefaults instantiates a new IpAllocationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpAllocationResponseWithDefaults() *IpAllocationResponse {
	this := IpAllocationResponse{}
	return &this
}

// GetAllocatedCount returns the AllocatedCount field value
func (o *IpAllocationResponse) GetAllocatedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AllocatedCount
}

// GetAllocatedCountOk returns a tuple with the AllocatedCount field value
// and a boolean to check if the value has been set.
func (o *IpAllocationResponse) GetAllocatedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllocatedCount, true
}

// SetAllocatedCount sets field value
func (o *IpAllocationResponse) SetAllocatedCount(v int32) {
	o.AllocatedCount = v
}

// GetAllocatedIps returns the AllocatedIps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IpAllocationResponse) GetAllocatedIps() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllocatedIps
}

// GetAllocatedIpsOk returns a tuple with the AllocatedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IpAllocationResponse) GetAllocatedIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllocatedIps) {
		return nil, false
	}
	return o.AllocatedIps, true
}

// HasAllocatedIps returns a boolean if a field has been set.
func (o *IpAllocationResponse) HasAllocatedIps() bool {
	if o != nil && !IsNil(o.AllocatedIps) {
		return true
	}

	return false
}

// SetAllocatedIps gets a reference to the given []string and assigns it to the AllocatedIps field.
func (o *IpAllocationResponse) SetAllocatedIps(v []string) {
	o.AllocatedIps = v
}

// GetAvailableCount returns the AvailableCount field value
func (o *IpAllocationResponse) GetAvailableCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AvailableCount
}

// GetAvailableCountOk returns a tuple with the AvailableCount field value
// and a boolean to check if the value has been set.
func (o *IpAllocationResponse) GetAvailableCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableCount, true
}

// SetAvailableCount sets field value
func (o *IpAllocationResponse) SetAvailableCount(v int32) {
	o.AvailableCount = v
}

// GetCidr returns the Cidr field value
func (o *IpAllocationResponse) GetCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value
// and a boolean to check if the value has been set.
func (o *IpAllocationResponse) GetCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cidr, true
}

// SetCidr sets field value
func (o *IpAllocationResponse) SetCidr(v string) {
	o.Cidr = v
}

// GetTotalIps returns the TotalIps field value
func (o *IpAllocationResponse) GetTotalIps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalIps
}

// GetTotalIpsOk returns a tuple with the TotalIps field value
// and a boolean to check if the value has been set.
func (o *IpAllocationResponse) GetTotalIpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalIps, true
}

// SetTotalIps sets field value
func (o *IpAllocationResponse) SetTotalIps(v int32) {
	o.TotalIps = v
}

// GetUtilizationPercent returns the UtilizationPercent field value
func (o *IpAllocationResponse) GetUtilizationPercent() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.UtilizationPercent
}

// GetUtilizationPercentOk returns a tuple with the UtilizationPercent field value
// and a boolean to check if the value has been set.
func (o *IpAllocationResponse) GetUtilizationPercentOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UtilizationPercent, true
}

// SetUtilizationPercent sets field value
func (o *IpAllocationResponse) SetUtilizationPercent(v float64) {
	o.UtilizationPercent = v
}

func (o IpAllocationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpAllocationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allocated_count"] = o.AllocatedCount
	if o.AllocatedIps != nil {
		toSerialize["allocated_ips"] = o.AllocatedIps
	}
	toSerialize["available_count"] = o.AvailableCount
	toSerialize["cidr"] = o.Cidr
	toSerialize["total_ips"] = o.TotalIps
	toSerialize["utilization_percent"] = o.UtilizationPercent
	return toSerialize, nil
}

func (o *IpAllocationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allocated_count",
		"available_count",
		"cidr",
		"total_ips",
		"utilization_percent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpAllocationResponse := _IpAllocationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpAllocationResponse)

	if err != nil {
		return err
	}

	*o = IpAllocationResponse(varIpAllocationResponse)

	return err
}

type NullableIpAllocationResponse struct {
	value *IpAllocationResponse
	isSet bool
}

func (v NullableIpAllocationResponse) Get() *IpAllocationResponse {
	return v.value
}

func (v *NullableIpAllocationResponse) Set(val *IpAllocationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIpAllocationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIpAllocationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpAllocationResponse(val *IpAllocationResponse) *NullableIpAllocationResponse {
	return &NullableIpAllocationResponse{value: val, isSet: true}
}

func (v NullableIpAllocationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpAllocationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


