/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerExecRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerExecRequest{}

// ContainerExecRequest Exec request for running a command in a container
type ContainerExecRequest struct {
	// Command and arguments to execute
	Command []string `json:"command"`
}

type _ContainerExecRequest ContainerExecRequest

// NewContainerExecRequest instantiates a new ContainerExecRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerExecRequest(command []string) *ContainerExecRequest {
	this := ContainerExecRequest{}
	this.Command = command
	return &this
}

// NewContainerExecRequestWithDefaults instantiates a new ContainerExecRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerExecRequestWithDefaults() *ContainerExecRequest {
	this := ContainerExecRequest{}
	return &this
}

// GetCommand returns the Command field value
func (o *ContainerExecRequest) GetCommand() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *ContainerExecRequest) GetCommandOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command, true
}

// SetCommand sets field value
func (o *ContainerExecRequest) SetCommand(v []string) {
	o.Command = v
}

func (o ContainerExecRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerExecRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	return toSerialize, nil
}

func (o *ContainerExecRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerExecRequest := _ContainerExecRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerExecRequest)

	if err != nil {
		return err
	}

	*o = ContainerExecRequest(varContainerExecRequest)

	return err
}

type NullableContainerExecRequest struct {
	value *ContainerExecRequest
	isSet bool
}

func (v NullableContainerExecRequest) Get() *ContainerExecRequest {
	return v.value
}

func (v *NullableContainerExecRequest) Set(val *ContainerExecRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerExecRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerExecRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerExecRequest(val *ContainerExecRequest) *NullableContainerExecRequest {
	return &NullableContainerExecRequest{value: val, isSet: true}
}

func (v NullableContainerExecRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerExecRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


