/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateVolumeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVolumeRequest{}

// CreateVolumeRequest Request body for `POST /api/v1/volumes`.
type CreateVolumeRequest struct {
	// Optional labels to attach to the volume.
	Labels map[string]string `json:"labels,omitempty"`
	// Volume name. Required. Must match `^[a-z0-9][a-z0-9_-]{0,63}$`.
	Name string `json:"name"`
	// Optional size hint (humansize format: `\"512Mi\"`, `\"10Gi\"`). Recorded in the sidecar for display and future quota enforcement.
	Size NullableString `json:"size,omitempty"`
	// Optional storage tier. Accepts `\"local\"` (default), `\"cached\"`, `\"network\"`, matching `zlayer_spec::StorageTier`.
	Tier NullableString `json:"tier,omitempty"`
}

type _CreateVolumeRequest CreateVolumeRequest

// NewCreateVolumeRequest instantiates a new CreateVolumeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVolumeRequest(name string) *CreateVolumeRequest {
	this := CreateVolumeRequest{}
	this.Name = name
	return &this
}

// NewCreateVolumeRequestWithDefaults instantiates a new CreateVolumeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVolumeRequestWithDefaults() *CreateVolumeRequest {
	this := CreateVolumeRequest{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateVolumeRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVolumeRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateVolumeRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *CreateVolumeRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetName returns the Name field value
func (o *CreateVolumeRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateVolumeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateVolumeRequest) SetName(v string) {
	o.Name = v
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateVolumeRequest) GetSize() string {
	if o == nil || IsNil(o.Size.Get()) {
		var ret string
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateVolumeRequest) GetSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *CreateVolumeRequest) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableString and assigns it to the Size field.
func (o *CreateVolumeRequest) SetSize(v string) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *CreateVolumeRequest) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *CreateVolumeRequest) UnsetSize() {
	o.Size.Unset()
}

// GetTier returns the Tier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateVolumeRequest) GetTier() string {
	if o == nil || IsNil(o.Tier.Get()) {
		var ret string
		return ret
	}
	return *o.Tier.Get()
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateVolumeRequest) GetTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tier.Get(), o.Tier.IsSet()
}

// HasTier returns a boolean if a field has been set.
func (o *CreateVolumeRequest) HasTier() bool {
	if o != nil && o.Tier.IsSet() {
		return true
	}

	return false
}

// SetTier gets a reference to the given NullableString and assigns it to the Tier field.
func (o *CreateVolumeRequest) SetTier(v string) {
	o.Tier.Set(&v)
}
// SetTierNil sets the value for Tier to be an explicit nil
func (o *CreateVolumeRequest) SetTierNil() {
	o.Tier.Set(nil)
}

// UnsetTier ensures that no value is present for Tier, not even an explicit nil
func (o *CreateVolumeRequest) UnsetTier() {
	o.Tier.Unset()
}

func (o CreateVolumeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVolumeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["name"] = o.Name
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	if o.Tier.IsSet() {
		toSerialize["tier"] = o.Tier.Get()
	}
	return toSerialize, nil
}

func (o *CreateVolumeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateVolumeRequest := _CreateVolumeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateVolumeRequest)

	if err != nil {
		return err
	}

	*o = CreateVolumeRequest(varCreateVolumeRequest)

	return err
}

type NullableCreateVolumeRequest struct {
	value *CreateVolumeRequest
	isSet bool
}

func (v NullableCreateVolumeRequest) Get() *CreateVolumeRequest {
	return v.value
}

func (v *NullableCreateVolumeRequest) Set(val *CreateVolumeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVolumeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVolumeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVolumeRequest(val *CreateVolumeRequest) *NullableCreateVolumeRequest {
	return &NullableCreateVolumeRequest{value: val, isSet: true}
}

func (v NullableCreateVolumeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVolumeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


