/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"fmt"
)

// UpgradeStatus Lifecycle of a daemon-binary upgrade job, tracked in-memory on the node being upgraded.
type UpgradeStatus string

// List of UpgradeStatus
const (
	UPGRADESTATUS_PENDING UpgradeStatus = "pending"
	UPGRADESTATUS_DOWNLOADING UpgradeStatus = "downloading"
	UPGRADESTATUS_APPLYING UpgradeStatus = "applying"
	UPGRADESTATUS_RESTARTING UpgradeStatus = "restarting"
	UPGRADESTATUS_FAILED UpgradeStatus = "failed"
)

// All allowed values of UpgradeStatus enum
var AllowedUpgradeStatusEnumValues = []UpgradeStatus{
	"pending",
	"downloading",
	"applying",
	"restarting",
	"failed",
}

func (v *UpgradeStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UpgradeStatus(value)
	for _, existing := range AllowedUpgradeStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UpgradeStatus", value)
}

// NewUpgradeStatusFromValue returns a pointer to a valid UpgradeStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUpgradeStatusFromValue(v string) (*UpgradeStatus, error) {
	ev := UpgradeStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UpgradeStatus: valid values are %v", v, AllowedUpgradeStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UpgradeStatus) IsValid() bool {
	for _, existing := range AllowedUpgradeStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UpgradeStatus value
func (v UpgradeStatus) Ptr() *UpgradeStatus {
	return &v
}

type NullableUpgradeStatus struct {
	value *UpgradeStatus
	isSet bool
}

func (v NullableUpgradeStatus) Get() *UpgradeStatus {
	return v.value
}

func (v *NullableUpgradeStatus) Set(val *UpgradeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeStatus(val *UpgradeStatus) *NullableUpgradeStatus {
	return &NullableUpgradeStatus{value: val, isSet: true}
}

func (v NullableUpgradeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

