/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NetworkEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkEvent{}

// NetworkEvent A network lifecycle event.
type NetworkEvent struct {
	// Wall-clock time.
	At time.Time `json:"at"`
	// Container id, populated for `Connect`/`Disconnect`.
	ContainerId NullableString `json:"container_id,omitempty"`
	// Network driver (e.g. `bridge`, `overlay`).
	Driver *string `json:"driver,omitempty"`
	// Network identifier (registry id).
	Id string `json:"id"`
	Kind NetworkEventKind `json:"kind"`
	// Human-readable network name.
	Name string `json:"name"`
}

type _NetworkEvent NetworkEvent

// NewNetworkEvent instantiates a new NetworkEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkEvent(at time.Time, id string, kind NetworkEventKind, name string) *NetworkEvent {
	this := NetworkEvent{}
	this.At = at
	this.Id = id
	this.Kind = kind
	this.Name = name
	return &this
}

// NewNetworkEventWithDefaults instantiates a new NetworkEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkEventWithDefaults() *NetworkEvent {
	this := NetworkEvent{}
	return &this
}

// GetAt returns the At field value
func (o *NetworkEvent) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *NetworkEvent) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *NetworkEvent) SetAt(v time.Time) {
	o.At = v
}

// GetContainerId returns the ContainerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkEvent) GetContainerId() string {
	if o == nil || IsNil(o.ContainerId.Get()) {
		var ret string
		return ret
	}
	return *o.ContainerId.Get()
}

// GetContainerIdOk returns a tuple with the ContainerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkEvent) GetContainerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContainerId.Get(), o.ContainerId.IsSet()
}

// HasContainerId returns a boolean if a field has been set.
func (o *NetworkEvent) HasContainerId() bool {
	if o != nil && o.ContainerId.IsSet() {
		return true
	}

	return false
}

// SetContainerId gets a reference to the given NullableString and assigns it to the ContainerId field.
func (o *NetworkEvent) SetContainerId(v string) {
	o.ContainerId.Set(&v)
}
// SetContainerIdNil sets the value for ContainerId to be an explicit nil
func (o *NetworkEvent) SetContainerIdNil() {
	o.ContainerId.Set(nil)
}

// UnsetContainerId ensures that no value is present for ContainerId, not even an explicit nil
func (o *NetworkEvent) UnsetContainerId() {
	o.ContainerId.Unset()
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *NetworkEvent) GetDriver() string {
	if o == nil || IsNil(o.Driver) {
		var ret string
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkEvent) GetDriverOk() (*string, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *NetworkEvent) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given string and assigns it to the Driver field.
func (o *NetworkEvent) SetDriver(v string) {
	o.Driver = &v
}

// GetId returns the Id field value
func (o *NetworkEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkEvent) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *NetworkEvent) GetKind() NetworkEventKind {
	if o == nil {
		var ret NetworkEventKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *NetworkEvent) GetKindOk() (*NetworkEventKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *NetworkEvent) SetKind(v NetworkEventKind) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *NetworkEvent) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkEvent) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkEvent) SetName(v string) {
	o.Name = v
}

func (o NetworkEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["at"] = o.At
	if o.ContainerId.IsSet() {
		toSerialize["container_id"] = o.ContainerId.Get()
	}
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *NetworkEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"at",
		"id",
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkEvent := _NetworkEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkEvent)

	if err != nil {
		return err
	}

	*o = NetworkEvent(varNetworkEvent)

	return err
}

type NullableNetworkEvent struct {
	value *NetworkEvent
	isSet bool
}

func (v NullableNetworkEvent) Get() *NetworkEvent {
	return v.value
}

func (v *NullableNetworkEvent) Set(val *NetworkEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkEvent(val *NetworkEvent) *NullableNetworkEvent {
	return &NullableNetworkEvent{value: val, isSet: true}
}

func (v NullableNetworkEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


