/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoredPermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoredPermission{}

// StoredPermission A stored permission grant binding a subject (user or group) to a resource with a specific access level.  Canonical `resource_kind` strings (kept here for grep-ability): - `\"environment\"` — a `StoredEnvironment` row. - `\"deployment\"` — a `StoredDeployment` row. - `\"project\"` — a `StoredProject` row. - `\"secret\"` — a row in the secrets store (`{scope}:{name}` keyed). - `\"node\"` — a cluster member identified by `NodeIdentity::node_id`.
type StoredPermission struct {
	// When the permission was created.
	CreatedAt string `json:"created_at"`
	// UUID identifier of this permission grant.
	Id string `json:"id"`
	// The granted access level.
	Level PermissionLevel `json:"level"`
	// A specific resource id, or `None` for a wildcard (all resources of that kind).
	ResourceId NullableString `json:"resource_id,omitempty"`
	// The kind of resource (e.g. `\"deployment\"`, `\"project\"`, `\"secret\"`).
	ResourceKind string `json:"resource_kind"`
	// The user or group id.
	SubjectId string `json:"subject_id"`
	// Whether the subject is a user or a group.
	SubjectKind SubjectKind `json:"subject_kind"`
}

type _StoredPermission StoredPermission

// NewStoredPermission instantiates a new StoredPermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoredPermission(createdAt string, id string, level PermissionLevel, resourceKind string, subjectId string, subjectKind SubjectKind) *StoredPermission {
	this := StoredPermission{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Level = level
	this.ResourceKind = resourceKind
	this.SubjectId = subjectId
	this.SubjectKind = subjectKind
	return &this
}

// NewStoredPermissionWithDefaults instantiates a new StoredPermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoredPermissionWithDefaults() *StoredPermission {
	this := StoredPermission{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *StoredPermission) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *StoredPermission) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *StoredPermission) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *StoredPermission) SetId(v string) {
	o.Id = v
}

// GetLevel returns the Level field value
func (o *StoredPermission) GetLevel() PermissionLevel {
	if o == nil {
		var ret PermissionLevel
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetLevelOk() (*PermissionLevel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *StoredPermission) SetLevel(v PermissionLevel) {
	o.Level = v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StoredPermission) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId.Get()) {
		var ret string
		return ret
	}
	return *o.ResourceId.Get()
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoredPermission) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceId.Get(), o.ResourceId.IsSet()
}

// HasResourceId returns a boolean if a field has been set.
func (o *StoredPermission) HasResourceId() bool {
	if o != nil && o.ResourceId.IsSet() {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given NullableString and assigns it to the ResourceId field.
func (o *StoredPermission) SetResourceId(v string) {
	o.ResourceId.Set(&v)
}
// SetResourceIdNil sets the value for ResourceId to be an explicit nil
func (o *StoredPermission) SetResourceIdNil() {
	o.ResourceId.Set(nil)
}

// UnsetResourceId ensures that no value is present for ResourceId, not even an explicit nil
func (o *StoredPermission) UnsetResourceId() {
	o.ResourceId.Unset()
}

// GetResourceKind returns the ResourceKind field value
func (o *StoredPermission) GetResourceKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceKind
}

// GetResourceKindOk returns a tuple with the ResourceKind field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetResourceKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceKind, true
}

// SetResourceKind sets field value
func (o *StoredPermission) SetResourceKind(v string) {
	o.ResourceKind = v
}

// GetSubjectId returns the SubjectId field value
func (o *StoredPermission) GetSubjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubjectId
}

// GetSubjectIdOk returns a tuple with the SubjectId field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetSubjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectId, true
}

// SetSubjectId sets field value
func (o *StoredPermission) SetSubjectId(v string) {
	o.SubjectId = v
}

// GetSubjectKind returns the SubjectKind field value
func (o *StoredPermission) GetSubjectKind() SubjectKind {
	if o == nil {
		var ret SubjectKind
		return ret
	}

	return o.SubjectKind
}

// GetSubjectKindOk returns a tuple with the SubjectKind field value
// and a boolean to check if the value has been set.
func (o *StoredPermission) GetSubjectKindOk() (*SubjectKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectKind, true
}

// SetSubjectKind sets field value
func (o *StoredPermission) SetSubjectKind(v SubjectKind) {
	o.SubjectKind = v
}

func (o StoredPermission) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoredPermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["level"] = o.Level
	if o.ResourceId.IsSet() {
		toSerialize["resource_id"] = o.ResourceId.Get()
	}
	toSerialize["resource_kind"] = o.ResourceKind
	toSerialize["subject_id"] = o.SubjectId
	toSerialize["subject_kind"] = o.SubjectKind
	return toSerialize, nil
}

func (o *StoredPermission) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"level",
		"resource_kind",
		"subject_id",
		"subject_kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoredPermission := _StoredPermission{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoredPermission)

	if err != nil {
		return err
	}

	*o = StoredPermission(varStoredPermission)

	return err
}

type NullableStoredPermission struct {
	value *StoredPermission
	isSet bool
}

func (v NullableStoredPermission) Get() *StoredPermission {
	return v.value
}

func (v *NullableStoredPermission) Set(val *StoredPermission) {
	v.value = val
	v.isSet = true
}

func (v NullableStoredPermission) IsSet() bool {
	return v.isSet
}

func (v *NullableStoredPermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoredPermission(val *StoredPermission) *NullableStoredPermission {
	return &NullableStoredPermission{value: val, isSet: true}
}

func (v NullableStoredPermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoredPermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


