/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentRequest{}

// CreateEnvironmentRequest Body for `POST /api/v1/environments`.
type CreateEnvironmentRequest struct {
	// Free-form description shown in the UI.
	Description NullableString `json:"description,omitempty"`
	// Display name. Must be unique within the chosen `project_id` namespace.
	Name string `json:"name"`
	// Owning project id. `None` = global environment.
	ProjectId NullableString `json:"project_id,omitempty"`
}

type _CreateEnvironmentRequest CreateEnvironmentRequest

// NewCreateEnvironmentRequest instantiates a new CreateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentRequest(name string) *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	this.Name = name
	return &this
}

// NewCreateEnvironmentRequestWithDefaults instantiates a new CreateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentRequestWithDefaults() *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnvironmentRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnvironmentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateEnvironmentRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateEnvironmentRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateEnvironmentRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetName returns the Name field value
func (o *CreateEnvironmentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEnvironmentRequest) SetName(v string) {
	o.Name = v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEnvironmentRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId.Get()) {
		var ret string
		return ret
	}
	return *o.ProjectId.Get()
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEnvironmentRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectId.Get(), o.ProjectId.IsSet()
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasProjectId() bool {
	if o != nil && o.ProjectId.IsSet() {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given NullableString and assigns it to the ProjectId field.
func (o *CreateEnvironmentRequest) SetProjectId(v string) {
	o.ProjectId.Set(&v)
}
// SetProjectIdNil sets the value for ProjectId to be an explicit nil
func (o *CreateEnvironmentRequest) SetProjectIdNil() {
	o.ProjectId.Set(nil)
}

// UnsetProjectId ensures that no value is present for ProjectId, not even an explicit nil
func (o *CreateEnvironmentRequest) UnsetProjectId() {
	o.ProjectId.Unset()
}

func (o CreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["name"] = o.Name
	if o.ProjectId.IsSet() {
		toSerialize["project_id"] = o.ProjectId.Get()
	}
	return toSerialize, nil
}

func (o *CreateEnvironmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEnvironmentRequest := _CreateEnvironmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEnvironmentRequest)

	if err != nil {
		return err
	}

	*o = CreateEnvironmentRequest(varCreateEnvironmentRequest)

	return err
}

type NullableCreateEnvironmentRequest struct {
	value *CreateEnvironmentRequest
	isSet bool
}

func (v NullableCreateEnvironmentRequest) Get() *CreateEnvironmentRequest {
	return v.value
}

func (v *NullableCreateEnvironmentRequest) Set(val *CreateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentRequest(val *CreateEnvironmentRequest) *NullableCreateEnvironmentRequest {
	return &NullableCreateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


