/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TriggerBuildResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerBuildResponse{}

// TriggerBuildResponse Trigger build response
type TriggerBuildResponse struct {
	// Unique build ID for tracking
	BuildId string `json:"build_id"`
	// Human-readable message
	Message string `json:"message"`
}

type _TriggerBuildResponse TriggerBuildResponse

// NewTriggerBuildResponse instantiates a new TriggerBuildResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerBuildResponse(buildId string, message string) *TriggerBuildResponse {
	this := TriggerBuildResponse{}
	this.BuildId = buildId
	this.Message = message
	return &this
}

// NewTriggerBuildResponseWithDefaults instantiates a new TriggerBuildResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerBuildResponseWithDefaults() *TriggerBuildResponse {
	this := TriggerBuildResponse{}
	return &this
}

// GetBuildId returns the BuildId field value
func (o *TriggerBuildResponse) GetBuildId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildId
}

// GetBuildIdOk returns a tuple with the BuildId field value
// and a boolean to check if the value has been set.
func (o *TriggerBuildResponse) GetBuildIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildId, true
}

// SetBuildId sets field value
func (o *TriggerBuildResponse) SetBuildId(v string) {
	o.BuildId = v
}

// GetMessage returns the Message field value
func (o *TriggerBuildResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TriggerBuildResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TriggerBuildResponse) SetMessage(v string) {
	o.Message = v
}

func (o TriggerBuildResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerBuildResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["build_id"] = o.BuildId
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TriggerBuildResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"build_id",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerBuildResponse := _TriggerBuildResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTriggerBuildResponse)

	if err != nil {
		return err
	}

	*o = TriggerBuildResponse(varTriggerBuildResponse)

	return err
}

type NullableTriggerBuildResponse struct {
	value *TriggerBuildResponse
	isSet bool
}

func (v NullableTriggerBuildResponse) Get() *TriggerBuildResponse {
	return v.value
}

func (v *NullableTriggerBuildResponse) Set(val *TriggerBuildResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerBuildResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerBuildResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerBuildResponse(val *TriggerBuildResponse) *NullableTriggerBuildResponse {
	return &NullableTriggerBuildResponse{value: val, isSet: true}
}

func (v NullableTriggerBuildResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerBuildResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


