/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncResourceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncResourceResponse{}

// SyncResourceResponse A single resource in the diff output.
type SyncResourceResponse struct {
	// Source file name.
	FilePath string `json:"file_path"`
	// Resource kind.
	Kind string `json:"kind"`
	// Resource name.
	Name string `json:"name"`
}

type _SyncResourceResponse SyncResourceResponse

// NewSyncResourceResponse instantiates a new SyncResourceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncResourceResponse(filePath string, kind string, name string) *SyncResourceResponse {
	this := SyncResourceResponse{}
	this.FilePath = filePath
	this.Kind = kind
	this.Name = name
	return &this
}

// NewSyncResourceResponseWithDefaults instantiates a new SyncResourceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncResourceResponseWithDefaults() *SyncResourceResponse {
	this := SyncResourceResponse{}
	return &this
}

// GetFilePath returns the FilePath field value
func (o *SyncResourceResponse) GetFilePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value
// and a boolean to check if the value has been set.
func (o *SyncResourceResponse) GetFilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilePath, true
}

// SetFilePath sets field value
func (o *SyncResourceResponse) SetFilePath(v string) {
	o.FilePath = v
}

// GetKind returns the Kind field value
func (o *SyncResourceResponse) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SyncResourceResponse) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SyncResourceResponse) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *SyncResourceResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SyncResourceResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SyncResourceResponse) SetName(v string) {
	o.Name = v
}

func (o SyncResourceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncResourceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file_path"] = o.FilePath
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *SyncResourceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_path",
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncResourceResponse := _SyncResourceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncResourceResponse)

	if err != nil {
		return err
	}

	*o = SyncResourceResponse(varSyncResourceResponse)

	return err
}

type NullableSyncResourceResponse struct {
	value *SyncResourceResponse
	isSet bool
}

func (v NullableSyncResourceResponse) Get() *SyncResourceResponse {
	return v.value
}

func (v *NullableSyncResourceResponse) Set(val *SyncResourceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncResourceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncResourceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncResourceResponse(val *SyncResourceResponse) *NullableSyncResourceResponse {
	return &NullableSyncResourceResponse{value: val, isSet: true}
}

func (v NullableSyncResourceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncResourceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


