/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
)

// checks if the RestartContainerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestartContainerRequest{}

// RestartContainerRequest Request body for restarting a container. Matches the Docker-compat `POST /containers/{id}/restart` shape.
type RestartContainerRequest struct {
	// Graceful shutdown timeout in seconds before the runtime force-kills the container. Defaults to 30 seconds when omitted.
	Timeout NullableInt64 `json:"timeout,omitempty"`
}

// NewRestartContainerRequest instantiates a new RestartContainerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestartContainerRequest() *RestartContainerRequest {
	this := RestartContainerRequest{}
	return &this
}

// NewRestartContainerRequestWithDefaults instantiates a new RestartContainerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartContainerRequestWithDefaults() *RestartContainerRequest {
	this := RestartContainerRequest{}
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestartContainerRequest) GetTimeout() int64 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int64
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestartContainerRequest) GetTimeoutOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *RestartContainerRequest) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt64 and assigns it to the Timeout field.
func (o *RestartContainerRequest) SetTimeout(v int64) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *RestartContainerRequest) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *RestartContainerRequest) UnsetTimeout() {
	o.Timeout.Unset()
}

func (o RestartContainerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartContainerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	return toSerialize, nil
}

type NullableRestartContainerRequest struct {
	value *RestartContainerRequest
	isSet bool
}

func (v NullableRestartContainerRequest) Get() *RestartContainerRequest {
	return v.value
}

func (v *NullableRestartContainerRequest) Set(val *RestartContainerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartContainerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartContainerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartContainerRequest(val *RestartContainerRequest) *NullableRestartContainerRequest {
	return &NullableRestartContainerRequest{value: val, isSet: true}
}

func (v NullableRestartContainerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartContainerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


