/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GossipPeerSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GossipPeerSummary{}

// GossipPeerSummary Snapshot of one gossip-pool peer, returned by `GET /api/v1/cluster/gossip/peers`.
type GossipPeerSummary struct {
	// Free-form labels advertised by the peer.
	Labels map[string]string `json:"labels,omitempty"`
	// Worker (or peer) node id.
	NodeId int64 `json:"node_id"`
	// Overlay IP assigned to this peer, if known.
	OverlayIp NullableString `json:"overlay_ip,omitempty"`
	// `WireGuard` UDP endpoint (host:port), if known.
	WgEndpoint NullableString `json:"wg_endpoint,omitempty"`
	// `WireGuard` public key (base64-url-no-pad), if known.
	WgPubkey NullableString `json:"wg_pubkey,omitempty"`
}

type _GossipPeerSummary GossipPeerSummary

// NewGossipPeerSummary instantiates a new GossipPeerSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGossipPeerSummary(nodeId int64) *GossipPeerSummary {
	this := GossipPeerSummary{}
	this.NodeId = nodeId
	return &this
}

// NewGossipPeerSummaryWithDefaults instantiates a new GossipPeerSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGossipPeerSummaryWithDefaults() *GossipPeerSummary {
	this := GossipPeerSummary{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *GossipPeerSummary) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GossipPeerSummary) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *GossipPeerSummary) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *GossipPeerSummary) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetNodeId returns the NodeId field value
func (o *GossipPeerSummary) GetNodeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *GossipPeerSummary) GetNodeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *GossipPeerSummary) SetNodeId(v int64) {
	o.NodeId = v
}

// GetOverlayIp returns the OverlayIp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GossipPeerSummary) GetOverlayIp() string {
	if o == nil || IsNil(o.OverlayIp.Get()) {
		var ret string
		return ret
	}
	return *o.OverlayIp.Get()
}

// GetOverlayIpOk returns a tuple with the OverlayIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GossipPeerSummary) GetOverlayIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OverlayIp.Get(), o.OverlayIp.IsSet()
}

// HasOverlayIp returns a boolean if a field has been set.
func (o *GossipPeerSummary) HasOverlayIp() bool {
	if o != nil && o.OverlayIp.IsSet() {
		return true
	}

	return false
}

// SetOverlayIp gets a reference to the given NullableString and assigns it to the OverlayIp field.
func (o *GossipPeerSummary) SetOverlayIp(v string) {
	o.OverlayIp.Set(&v)
}
// SetOverlayIpNil sets the value for OverlayIp to be an explicit nil
func (o *GossipPeerSummary) SetOverlayIpNil() {
	o.OverlayIp.Set(nil)
}

// UnsetOverlayIp ensures that no value is present for OverlayIp, not even an explicit nil
func (o *GossipPeerSummary) UnsetOverlayIp() {
	o.OverlayIp.Unset()
}

// GetWgEndpoint returns the WgEndpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GossipPeerSummary) GetWgEndpoint() string {
	if o == nil || IsNil(o.WgEndpoint.Get()) {
		var ret string
		return ret
	}
	return *o.WgEndpoint.Get()
}

// GetWgEndpointOk returns a tuple with the WgEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GossipPeerSummary) GetWgEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WgEndpoint.Get(), o.WgEndpoint.IsSet()
}

// HasWgEndpoint returns a boolean if a field has been set.
func (o *GossipPeerSummary) HasWgEndpoint() bool {
	if o != nil && o.WgEndpoint.IsSet() {
		return true
	}

	return false
}

// SetWgEndpoint gets a reference to the given NullableString and assigns it to the WgEndpoint field.
func (o *GossipPeerSummary) SetWgEndpoint(v string) {
	o.WgEndpoint.Set(&v)
}
// SetWgEndpointNil sets the value for WgEndpoint to be an explicit nil
func (o *GossipPeerSummary) SetWgEndpointNil() {
	o.WgEndpoint.Set(nil)
}

// UnsetWgEndpoint ensures that no value is present for WgEndpoint, not even an explicit nil
func (o *GossipPeerSummary) UnsetWgEndpoint() {
	o.WgEndpoint.Unset()
}

// GetWgPubkey returns the WgPubkey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GossipPeerSummary) GetWgPubkey() string {
	if o == nil || IsNil(o.WgPubkey.Get()) {
		var ret string
		return ret
	}
	return *o.WgPubkey.Get()
}

// GetWgPubkeyOk returns a tuple with the WgPubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GossipPeerSummary) GetWgPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WgPubkey.Get(), o.WgPubkey.IsSet()
}

// HasWgPubkey returns a boolean if a field has been set.
func (o *GossipPeerSummary) HasWgPubkey() bool {
	if o != nil && o.WgPubkey.IsSet() {
		return true
	}

	return false
}

// SetWgPubkey gets a reference to the given NullableString and assigns it to the WgPubkey field.
func (o *GossipPeerSummary) SetWgPubkey(v string) {
	o.WgPubkey.Set(&v)
}
// SetWgPubkeyNil sets the value for WgPubkey to be an explicit nil
func (o *GossipPeerSummary) SetWgPubkeyNil() {
	o.WgPubkey.Set(nil)
}

// UnsetWgPubkey ensures that no value is present for WgPubkey, not even an explicit nil
func (o *GossipPeerSummary) UnsetWgPubkey() {
	o.WgPubkey.Unset()
}

func (o GossipPeerSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GossipPeerSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["node_id"] = o.NodeId
	if o.OverlayIp.IsSet() {
		toSerialize["overlay_ip"] = o.OverlayIp.Get()
	}
	if o.WgEndpoint.IsSet() {
		toSerialize["wg_endpoint"] = o.WgEndpoint.Get()
	}
	if o.WgPubkey.IsSet() {
		toSerialize["wg_pubkey"] = o.WgPubkey.Get()
	}
	return toSerialize, nil
}

func (o *GossipPeerSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGossipPeerSummary := _GossipPeerSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGossipPeerSummary)

	if err != nil {
		return err
	}

	*o = GossipPeerSummary(varGossipPeerSummary)

	return err
}

type NullableGossipPeerSummary struct {
	value *GossipPeerSummary
	isSet bool
}

func (v NullableGossipPeerSummary) Get() *GossipPeerSummary {
	return v.value
}

func (v *NullableGossipPeerSummary) Set(val *GossipPeerSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGossipPeerSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGossipPeerSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGossipPeerSummary(val *GossipPeerSummary) *NullableGossipPeerSummary {
	return &NullableGossipPeerSummary{value: val, isSet: true}
}

func (v NullableGossipPeerSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGossipPeerSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


