/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTunnelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTunnelRequest{}

// CreateTunnelRequest Request to create a new tunnel token
type CreateTunnelRequest struct {
	// Name for this tunnel (for identification)
	Name string `json:"name"`
	// Optional list of services this tunnel is allowed to expose
	Services []string `json:"services,omitempty"`
	// Time-to-live in seconds (default: 24 hours)
	TtlSecs *int64 `json:"ttl_secs,omitempty"`
}

type _CreateTunnelRequest CreateTunnelRequest

// NewCreateTunnelRequest instantiates a new CreateTunnelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTunnelRequest(name string) *CreateTunnelRequest {
	this := CreateTunnelRequest{}
	this.Name = name
	return &this
}

// NewCreateTunnelRequestWithDefaults instantiates a new CreateTunnelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTunnelRequestWithDefaults() *CreateTunnelRequest {
	this := CreateTunnelRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTunnelRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTunnelRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTunnelRequest) SetName(v string) {
	o.Name = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *CreateTunnelRequest) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTunnelRequest) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *CreateTunnelRequest) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *CreateTunnelRequest) SetServices(v []string) {
	o.Services = v
}

// GetTtlSecs returns the TtlSecs field value if set, zero value otherwise.
func (o *CreateTunnelRequest) GetTtlSecs() int64 {
	if o == nil || IsNil(o.TtlSecs) {
		var ret int64
		return ret
	}
	return *o.TtlSecs
}

// GetTtlSecsOk returns a tuple with the TtlSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTunnelRequest) GetTtlSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.TtlSecs) {
		return nil, false
	}
	return o.TtlSecs, true
}

// HasTtlSecs returns a boolean if a field has been set.
func (o *CreateTunnelRequest) HasTtlSecs() bool {
	if o != nil && !IsNil(o.TtlSecs) {
		return true
	}

	return false
}

// SetTtlSecs gets a reference to the given int64 and assigns it to the TtlSecs field.
func (o *CreateTunnelRequest) SetTtlSecs(v int64) {
	o.TtlSecs = &v
}

func (o CreateTunnelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTunnelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.TtlSecs) {
		toSerialize["ttl_secs"] = o.TtlSecs
	}
	return toSerialize, nil
}

func (o *CreateTunnelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTunnelRequest := _CreateTunnelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTunnelRequest)

	if err != nil {
		return err
	}

	*o = CreateTunnelRequest(varCreateTunnelRequest)

	return err
}

type NullableCreateTunnelRequest struct {
	value *CreateTunnelRequest
	isSet bool
}

func (v NullableCreateTunnelRequest) Get() *CreateTunnelRequest {
	return v.value
}

func (v *NullableCreateTunnelRequest) Set(val *CreateTunnelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTunnelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTunnelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTunnelRequest(val *CreateTunnelRequest) *NullableCreateTunnelRequest {
	return &NullableCreateTunnelRequest{value: val, isSet: true}
}

func (v NullableCreateTunnelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTunnelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


