/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAccessSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessSessionRequest{}

// CreateAccessSessionRequest Request to create a temporary access session for an existing tunneled service.  Used by `zlayer tunnel access <endpoint>` to ask the daemon to bind a local TCP listener that proxies to a remote service. The daemon returns the local address so the CLI can either connect directly (when the daemon and CLI share a host) or open a second hop forwarder.
type CreateAccessSessionRequest struct {
	// Service endpoint to access (e.g. \"postgres.service.zlayer\" or \"host:port\"). The daemon resolves this through the overlay network when configured.
	Endpoint string `json:"endpoint"`
	// Optional local port for the daemon to bind. `None` (or `0`) lets the daemon auto-assign an ephemeral port.
	LocalPort NullableInt32 `json:"local_port,omitempty"`
	// Time-to-live in seconds for the session. After this expires the listener is torn down.
	TtlSecs *int64 `json:"ttl_secs,omitempty"`
}

type _CreateAccessSessionRequest CreateAccessSessionRequest

// NewCreateAccessSessionRequest instantiates a new CreateAccessSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessSessionRequest(endpoint string) *CreateAccessSessionRequest {
	this := CreateAccessSessionRequest{}
	this.Endpoint = endpoint
	return &this
}

// NewCreateAccessSessionRequestWithDefaults instantiates a new CreateAccessSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessSessionRequestWithDefaults() *CreateAccessSessionRequest {
	this := CreateAccessSessionRequest{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *CreateAccessSessionRequest) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *CreateAccessSessionRequest) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *CreateAccessSessionRequest) SetEndpoint(v string) {
	o.Endpoint = v
}

// GetLocalPort returns the LocalPort field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccessSessionRequest) GetLocalPort() int32 {
	if o == nil || IsNil(o.LocalPort.Get()) {
		var ret int32
		return ret
	}
	return *o.LocalPort.Get()
}

// GetLocalPortOk returns a tuple with the LocalPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccessSessionRequest) GetLocalPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LocalPort.Get(), o.LocalPort.IsSet()
}

// HasLocalPort returns a boolean if a field has been set.
func (o *CreateAccessSessionRequest) HasLocalPort() bool {
	if o != nil && o.LocalPort.IsSet() {
		return true
	}

	return false
}

// SetLocalPort gets a reference to the given NullableInt32 and assigns it to the LocalPort field.
func (o *CreateAccessSessionRequest) SetLocalPort(v int32) {
	o.LocalPort.Set(&v)
}
// SetLocalPortNil sets the value for LocalPort to be an explicit nil
func (o *CreateAccessSessionRequest) SetLocalPortNil() {
	o.LocalPort.Set(nil)
}

// UnsetLocalPort ensures that no value is present for LocalPort, not even an explicit nil
func (o *CreateAccessSessionRequest) UnsetLocalPort() {
	o.LocalPort.Unset()
}

// GetTtlSecs returns the TtlSecs field value if set, zero value otherwise.
func (o *CreateAccessSessionRequest) GetTtlSecs() int64 {
	if o == nil || IsNil(o.TtlSecs) {
		var ret int64
		return ret
	}
	return *o.TtlSecs
}

// GetTtlSecsOk returns a tuple with the TtlSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccessSessionRequest) GetTtlSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.TtlSecs) {
		return nil, false
	}
	return o.TtlSecs, true
}

// HasTtlSecs returns a boolean if a field has been set.
func (o *CreateAccessSessionRequest) HasTtlSecs() bool {
	if o != nil && !IsNil(o.TtlSecs) {
		return true
	}

	return false
}

// SetTtlSecs gets a reference to the given int64 and assigns it to the TtlSecs field.
func (o *CreateAccessSessionRequest) SetTtlSecs(v int64) {
	o.TtlSecs = &v
}

func (o CreateAccessSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccessSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint"] = o.Endpoint
	if o.LocalPort.IsSet() {
		toSerialize["local_port"] = o.LocalPort.Get()
	}
	if !IsNil(o.TtlSecs) {
		toSerialize["ttl_secs"] = o.TtlSecs
	}
	return toSerialize, nil
}

func (o *CreateAccessSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccessSessionRequest := _CreateAccessSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccessSessionRequest)

	if err != nil {
		return err
	}

	*o = CreateAccessSessionRequest(varCreateAccessSessionRequest)

	return err
}

type NullableCreateAccessSessionRequest struct {
	value *CreateAccessSessionRequest
	isSet bool
}

func (v NullableCreateAccessSessionRequest) Get() *CreateAccessSessionRequest {
	return v.value
}

func (v *NullableCreateAccessSessionRequest) Set(val *CreateAccessSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessSessionRequest(val *CreateAccessSessionRequest) *NullableCreateAccessSessionRequest {
	return &NullableCreateAccessSessionRequest{value: val, isSet: true}
}

func (v NullableCreateAccessSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


