/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerChangeEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerChangeEntry{}

// ContainerChangeEntry One row of `GET /api/v1/containers/{id}/changes` (Docker compat shape).  Mirrors Docker's `{\"Path\": \"/foo\", \"Kind\": 0}` body: `Kind` is a numeric enum where `0 = Modified`, `1 = Added`, `2 = Deleted`.
type ContainerChangeEntry struct {
	// `0` = Modified, `1` = Added, `2` = Deleted (Docker's wire integer).
	Kind int32 `json:"Kind"`
	// Path inside the container that changed (absolute, e.g. `/etc/hosts`).
	Path string `json:"Path"`
}

type _ContainerChangeEntry ContainerChangeEntry

// NewContainerChangeEntry instantiates a new ContainerChangeEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerChangeEntry(kind int32, path string) *ContainerChangeEntry {
	this := ContainerChangeEntry{}
	this.Kind = kind
	this.Path = path
	return &this
}

// NewContainerChangeEntryWithDefaults instantiates a new ContainerChangeEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerChangeEntryWithDefaults() *ContainerChangeEntry {
	this := ContainerChangeEntry{}
	return &this
}

// GetKind returns the Kind field value
func (o *ContainerChangeEntry) GetKind() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ContainerChangeEntry) GetKindOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ContainerChangeEntry) SetKind(v int32) {
	o.Kind = v
}

// GetPath returns the Path field value
func (o *ContainerChangeEntry) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ContainerChangeEntry) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ContainerChangeEntry) SetPath(v string) {
	o.Path = v
}

func (o ContainerChangeEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerChangeEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Kind"] = o.Kind
	toSerialize["Path"] = o.Path
	return toSerialize, nil
}

func (o *ContainerChangeEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Kind",
		"Path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerChangeEntry := _ContainerChangeEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerChangeEntry)

	if err != nil {
		return err
	}

	*o = ContainerChangeEntry(varContainerChangeEntry)

	return err
}

type NullableContainerChangeEntry struct {
	value *ContainerChangeEntry
	isSet bool
}

func (v NullableContainerChangeEntry) Get() *ContainerChangeEntry {
	return v.value
}

func (v *NullableContainerChangeEntry) Set(val *ContainerChangeEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerChangeEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerChangeEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerChangeEntry(val *ContainerChangeEntry) *NullableContainerChangeEntry {
	return &NullableContainerChangeEntry{value: val, isSet: true}
}

func (v NullableContainerChangeEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerChangeEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


