/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotifierConfigOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotifierConfigOneOf1{}

// NotifierConfigOneOf1 Discord webhook configuration.
type NotifierConfigOneOf1 struct {
	Type string `json:"type"`
	// Discord webhook URL.
	WebhookUrl string `json:"webhook_url"`
}

type _NotifierConfigOneOf1 NotifierConfigOneOf1

// NewNotifierConfigOneOf1 instantiates a new NotifierConfigOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotifierConfigOneOf1(type_ string, webhookUrl string) *NotifierConfigOneOf1 {
	this := NotifierConfigOneOf1{}
	this.Type = type_
	this.WebhookUrl = webhookUrl
	return &this
}

// NewNotifierConfigOneOf1WithDefaults instantiates a new NotifierConfigOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotifierConfigOneOf1WithDefaults() *NotifierConfigOneOf1 {
	this := NotifierConfigOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *NotifierConfigOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NotifierConfigOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NotifierConfigOneOf1) SetType(v string) {
	o.Type = v
}

// GetWebhookUrl returns the WebhookUrl field value
func (o *NotifierConfigOneOf1) GetWebhookUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value
// and a boolean to check if the value has been set.
func (o *NotifierConfigOneOf1) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookUrl, true
}

// SetWebhookUrl sets field value
func (o *NotifierConfigOneOf1) SetWebhookUrl(v string) {
	o.WebhookUrl = v
}

func (o NotifierConfigOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotifierConfigOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["webhook_url"] = o.WebhookUrl
	return toSerialize, nil
}

func (o *NotifierConfigOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"webhook_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotifierConfigOneOf1 := _NotifierConfigOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotifierConfigOneOf1)

	if err != nil {
		return err
	}

	*o = NotifierConfigOneOf1(varNotifierConfigOneOf1)

	return err
}

type NullableNotifierConfigOneOf1 struct {
	value *NotifierConfigOneOf1
	isSet bool
}

func (v NullableNotifierConfigOneOf1) Get() *NotifierConfigOneOf1 {
	return v.value
}

func (v *NullableNotifierConfigOneOf1) Set(val *NotifierConfigOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableNotifierConfigOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableNotifierConfigOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotifierConfigOneOf1(val *NotifierConfigOneOf1) *NullableNotifierConfigOneOf1 {
	return &NullableNotifierConfigOneOf1{value: val, isSet: true}
}

func (v NullableNotifierConfigOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotifierConfigOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


