/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagImageRequest{}

// TagImageRequest Request body for the tag-image handler. Matches Docker-compat `docker tag` semantics: create a new reference (`target`) pointing at an already-cached image (`source`).
type TagImageRequest struct {
	// Existing image reference to tag (e.g. `myapp:latest`).
	Source string `json:"source"`
	// New reference to create (e.g. `registry.example.com/myapp:v1`).
	Target string `json:"target"`
}

type _TagImageRequest TagImageRequest

// NewTagImageRequest instantiates a new TagImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagImageRequest(source string, target string) *TagImageRequest {
	this := TagImageRequest{}
	this.Source = source
	this.Target = target
	return &this
}

// NewTagImageRequestWithDefaults instantiates a new TagImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagImageRequestWithDefaults() *TagImageRequest {
	this := TagImageRequest{}
	return &this
}

// GetSource returns the Source field value
func (o *TagImageRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TagImageRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TagImageRequest) SetSource(v string) {
	o.Source = v
}

// GetTarget returns the Target field value
func (o *TagImageRequest) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *TagImageRequest) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *TagImageRequest) SetTarget(v string) {
	o.Target = v
}

func (o TagImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *TagImageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagImageRequest := _TagImageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagImageRequest)

	if err != nil {
		return err
	}

	*o = TagImageRequest(varTagImageRequest)

	return err
}

type NullableTagImageRequest struct {
	value *TagImageRequest
	isSet bool
}

func (v NullableTagImageRequest) Get() *TagImageRequest {
	return v.value
}

func (v *NullableTagImageRequest) Set(val *TagImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTagImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTagImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagImageRequest(val *TagImageRequest) *NullableTagImageRequest {
	return &NullableTagImageRequest{value: val, isSet: true}
}

func (v NullableTagImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


