/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StreamBackendInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamBackendInfo{}

// StreamBackendInfo Information about a single L4 stream proxy backend.
type StreamBackendInfo struct {
	// Backend address (`ip:port`).
	Address string `json:"address"`
}

type _StreamBackendInfo StreamBackendInfo

// NewStreamBackendInfo instantiates a new StreamBackendInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamBackendInfo(address string) *StreamBackendInfo {
	this := StreamBackendInfo{}
	this.Address = address
	return &this
}

// NewStreamBackendInfoWithDefaults instantiates a new StreamBackendInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamBackendInfoWithDefaults() *StreamBackendInfo {
	this := StreamBackendInfo{}
	return &this
}

// GetAddress returns the Address field value
func (o *StreamBackendInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *StreamBackendInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *StreamBackendInfo) SetAddress(v string) {
	o.Address = v
}

func (o StreamBackendInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamBackendInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *StreamBackendInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamBackendInfo := _StreamBackendInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamBackendInfo)

	if err != nil {
		return err
	}

	*o = StreamBackendInfo(varStreamBackendInfo)

	return err
}

type NullableStreamBackendInfo struct {
	value *StreamBackendInfo
	isSet bool
}

func (v NullableStreamBackendInfo) Get() *StreamBackendInfo {
	return v.value
}

func (v *NullableStreamBackendInfo) Set(val *StreamBackendInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamBackendInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamBackendInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamBackendInfo(val *StreamBackendInfo) *NullableStreamBackendInfo {
	return &NullableStreamBackendInfo{value: val, isSet: true}
}

func (v NullableStreamBackendInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamBackendInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


