/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PullImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PullImageResponse{}

// PullImageResponse Response body for the pull-image handler. Reports the pulled reference and, when the backend exposes it via `list_images`, the resolved digest and on-disk size.
type PullImageResponse struct {
	// Content-addressed digest (`sha256:...`) if the runtime reports one.
	Digest NullableString `json:"digest,omitempty"`
	// Canonical reference that was pulled.
	Reference string `json:"reference"`
	// On-disk size in bytes if the runtime reports one.
	SizeBytes NullableInt64 `json:"size_bytes,omitempty"`
}

type _PullImageResponse PullImageResponse

// NewPullImageResponse instantiates a new PullImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPullImageResponse(reference string) *PullImageResponse {
	this := PullImageResponse{}
	this.Reference = reference
	return &this
}

// NewPullImageResponseWithDefaults instantiates a new PullImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullImageResponseWithDefaults() *PullImageResponse {
	this := PullImageResponse{}
	return &this
}

// GetDigest returns the Digest field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PullImageResponse) GetDigest() string {
	if o == nil || IsNil(o.Digest.Get()) {
		var ret string
		return ret
	}
	return *o.Digest.Get()
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PullImageResponse) GetDigestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Digest.Get(), o.Digest.IsSet()
}

// HasDigest returns a boolean if a field has been set.
func (o *PullImageResponse) HasDigest() bool {
	if o != nil && o.Digest.IsSet() {
		return true
	}

	return false
}

// SetDigest gets a reference to the given NullableString and assigns it to the Digest field.
func (o *PullImageResponse) SetDigest(v string) {
	o.Digest.Set(&v)
}
// SetDigestNil sets the value for Digest to be an explicit nil
func (o *PullImageResponse) SetDigestNil() {
	o.Digest.Set(nil)
}

// UnsetDigest ensures that no value is present for Digest, not even an explicit nil
func (o *PullImageResponse) UnsetDigest() {
	o.Digest.Unset()
}

// GetReference returns the Reference field value
func (o *PullImageResponse) GetReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value
// and a boolean to check if the value has been set.
func (o *PullImageResponse) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reference, true
}

// SetReference sets field value
func (o *PullImageResponse) SetReference(v string) {
	o.Reference = v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PullImageResponse) GetSizeBytes() int64 {
	if o == nil || IsNil(o.SizeBytes.Get()) {
		var ret int64
		return ret
	}
	return *o.SizeBytes.Get()
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PullImageResponse) GetSizeBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SizeBytes.Get(), o.SizeBytes.IsSet()
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *PullImageResponse) HasSizeBytes() bool {
	if o != nil && o.SizeBytes.IsSet() {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given NullableInt64 and assigns it to the SizeBytes field.
func (o *PullImageResponse) SetSizeBytes(v int64) {
	o.SizeBytes.Set(&v)
}
// SetSizeBytesNil sets the value for SizeBytes to be an explicit nil
func (o *PullImageResponse) SetSizeBytesNil() {
	o.SizeBytes.Set(nil)
}

// UnsetSizeBytes ensures that no value is present for SizeBytes, not even an explicit nil
func (o *PullImageResponse) UnsetSizeBytes() {
	o.SizeBytes.Unset()
}

func (o PullImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PullImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Digest.IsSet() {
		toSerialize["digest"] = o.Digest.Get()
	}
	toSerialize["reference"] = o.Reference
	if o.SizeBytes.IsSet() {
		toSerialize["size_bytes"] = o.SizeBytes.Get()
	}
	return toSerialize, nil
}

func (o *PullImageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reference",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPullImageResponse := _PullImageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPullImageResponse)

	if err != nil {
		return err
	}

	*o = PullImageResponse(varPullImageResponse)

	return err
}

type NullablePullImageResponse struct {
	value *PullImageResponse
	isSet bool
}

func (v NullablePullImageResponse) Get() *PullImageResponse {
	return v.value
}

func (v *NullablePullImageResponse) Set(val *PullImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePullImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePullImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePullImageResponse(val *PullImageResponse) *NullablePullImageResponse {
	return &NullablePullImageResponse{value: val, isSet: true}
}

func (v NullablePullImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePullImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


