/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"fmt"
)

// GitCredentialKindSchema Kind of git credential (`OpenAPI` schema).
type GitCredentialKindSchema string

// List of GitCredentialKindSchema
const (
	GITCREDENTIALKINDSCHEMA_PAT GitCredentialKindSchema = "pat"
	GITCREDENTIALKINDSCHEMA_SSH_KEY GitCredentialKindSchema = "ssh_key"
)

// All allowed values of GitCredentialKindSchema enum
var AllowedGitCredentialKindSchemaEnumValues = []GitCredentialKindSchema{
	"pat",
	"ssh_key",
}

func (v *GitCredentialKindSchema) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitCredentialKindSchema(value)
	for _, existing := range AllowedGitCredentialKindSchemaEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitCredentialKindSchema", value)
}

// NewGitCredentialKindSchemaFromValue returns a pointer to a valid GitCredentialKindSchema
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitCredentialKindSchemaFromValue(v string) (*GitCredentialKindSchema, error) {
	ev := GitCredentialKindSchema(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitCredentialKindSchema: valid values are %v", v, AllowedGitCredentialKindSchemaEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitCredentialKindSchema) IsValid() bool {
	for _, existing := range AllowedGitCredentialKindSchemaEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GitCredentialKindSchema value
func (v GitCredentialKindSchema) Ptr() *GitCredentialKindSchema {
	return &v
}

type NullableGitCredentialKindSchema struct {
	value *GitCredentialKindSchema
	isSet bool
}

func (v NullableGitCredentialKindSchema) Get() *GitCredentialKindSchema {
	return v.value
}

func (v *NullableGitCredentialKindSchema) Set(val *GitCredentialKindSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGitCredentialKindSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGitCredentialKindSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitCredentialKindSchema(val *GitCredentialKindSchema) *NullableGitCredentialKindSchema {
	return &NullableGitCredentialKindSchema{value: val, isSet: true}
}

func (v NullableGitCredentialKindSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitCredentialKindSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

