/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeploymentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentSummary{}

// DeploymentSummary Deployment summary
type DeploymentSummary struct {
	// Created timestamp
	CreatedAt string `json:"created_at"`
	// Deployment name
	Name string `json:"name"`
	// Number of services
	ServiceCount int32 `json:"service_count"`
	// Deployment status
	Status string `json:"status"`
}

type _DeploymentSummary DeploymentSummary

// NewDeploymentSummary instantiates a new DeploymentSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentSummary(createdAt string, name string, serviceCount int32, status string) *DeploymentSummary {
	this := DeploymentSummary{}
	this.CreatedAt = createdAt
	this.Name = name
	this.ServiceCount = serviceCount
	this.Status = status
	return &this
}

// NewDeploymentSummaryWithDefaults instantiates a new DeploymentSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentSummaryWithDefaults() *DeploymentSummary {
	this := DeploymentSummary{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *DeploymentSummary) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DeploymentSummary) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetName returns the Name field value
func (o *DeploymentSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeploymentSummary) SetName(v string) {
	o.Name = v
}

// GetServiceCount returns the ServiceCount field value
func (o *DeploymentSummary) GetServiceCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceCount
}

// GetServiceCountOk returns a tuple with the ServiceCount field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetServiceCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceCount, true
}

// SetServiceCount sets field value
func (o *DeploymentSummary) SetServiceCount(v int32) {
	o.ServiceCount = v
}

// GetStatus returns the Status field value
func (o *DeploymentSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeploymentSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeploymentSummary) SetStatus(v string) {
	o.Status = v
}

func (o DeploymentSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["name"] = o.Name
	toSerialize["service_count"] = o.ServiceCount
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *DeploymentSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"name",
		"service_count",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentSummary := _DeploymentSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentSummary)

	if err != nil {
		return err
	}

	*o = DeploymentSummary(varDeploymentSummary)

	return err
}

type NullableDeploymentSummary struct {
	value *DeploymentSummary
	isSet bool
}

func (v NullableDeploymentSummary) Get() *DeploymentSummary {
	return v.value
}

func (v *NullableDeploymentSummary) Set(val *DeploymentSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentSummary(val *DeploymentSummary) *NullableDeploymentSummary {
	return &NullableDeploymentSummary{value: val, isSet: true}
}

func (v NullableDeploymentSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


