/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistryAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryAuth{}

// RegistryAuth Inline Docker/OCI registry credentials attached to a single pull request.  Prefer persistent credentials via `/api/v1/credentials/registry` for long-lived services. Use this inline form for one-off pulls (e.g. CI runners fetching a private image for a single job) where persisting a credential is undesirable.
type RegistryAuth struct {
	// Which authentication scheme to use against the registry.
	AuthType *RegistryAuthType `json:"auth_type,omitempty"`
	// Password or bearer token. **Never** logged or returned on any response — consumed once and dropped.
	Password string `json:"password"`
	// Username for the registry (for basic auth) or a placeholder identifier when `auth_type == Token`.
	Username string `json:"username"`
}

type _RegistryAuth RegistryAuth

// NewRegistryAuth instantiates a new RegistryAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryAuth(password string, username string) *RegistryAuth {
	this := RegistryAuth{}
	this.Password = password
	this.Username = username
	return &this
}

// NewRegistryAuthWithDefaults instantiates a new RegistryAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryAuthWithDefaults() *RegistryAuth {
	this := RegistryAuth{}
	return &this
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *RegistryAuth) GetAuthType() RegistryAuthType {
	if o == nil || IsNil(o.AuthType) {
		var ret RegistryAuthType
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryAuth) GetAuthTypeOk() (*RegistryAuthType, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *RegistryAuth) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given RegistryAuthType and assigns it to the AuthType field.
func (o *RegistryAuth) SetAuthType(v RegistryAuthType) {
	o.AuthType = &v
}

// GetPassword returns the Password field value
func (o *RegistryAuth) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegistryAuth) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegistryAuth) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value
func (o *RegistryAuth) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RegistryAuth) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RegistryAuth) SetUsername(v string) {
	o.Username = v
}

func (o RegistryAuth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthType) {
		toSerialize["auth_type"] = o.AuthType
	}
	toSerialize["password"] = o.Password
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *RegistryAuth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistryAuth := _RegistryAuth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistryAuth)

	if err != nil {
		return err
	}

	*o = RegistryAuth(varRegistryAuth)

	return err
}

type NullableRegistryAuth struct {
	value *RegistryAuth
	isSet bool
}

func (v NullableRegistryAuth) Get() *RegistryAuth {
	return v.value
}

func (v *NullableRegistryAuth) Set(val *RegistryAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryAuth(val *RegistryAuth) *NullableRegistryAuth {
	return &NullableRegistryAuth{value: val, isSet: true}
}

func (v NullableRegistryAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


