/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JoinTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JoinTokenResponse{}

// JoinTokenResponse Join token response for cluster joining
type JoinTokenResponse struct {
	// Allocated IP address for the joining node
	AllocatedIp string `json:"allocated_ip"`
	// Token expiration timestamp (Unix timestamp)
	ExpiresAt int64 `json:"expires_at"`
	// Leader endpoint to connect to
	LeaderEndpoint string `json:"leader_endpoint"`
	// Leader's public key for secure communication
	LeaderPublicKey string `json:"leader_public_key"`
	// Overlay network CIDR
	OverlayCidr string `json:"overlay_cidr"`
	// Join token for authenticating the new node
	Token string `json:"token"`
}

type _JoinTokenResponse JoinTokenResponse

// NewJoinTokenResponse instantiates a new JoinTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJoinTokenResponse(allocatedIp string, expiresAt int64, leaderEndpoint string, leaderPublicKey string, overlayCidr string, token string) *JoinTokenResponse {
	this := JoinTokenResponse{}
	this.AllocatedIp = allocatedIp
	this.ExpiresAt = expiresAt
	this.LeaderEndpoint = leaderEndpoint
	this.LeaderPublicKey = leaderPublicKey
	this.OverlayCidr = overlayCidr
	this.Token = token
	return &this
}

// NewJoinTokenResponseWithDefaults instantiates a new JoinTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJoinTokenResponseWithDefaults() *JoinTokenResponse {
	this := JoinTokenResponse{}
	return &this
}

// GetAllocatedIp returns the AllocatedIp field value
func (o *JoinTokenResponse) GetAllocatedIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AllocatedIp
}

// GetAllocatedIpOk returns a tuple with the AllocatedIp field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetAllocatedIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllocatedIp, true
}

// SetAllocatedIp sets field value
func (o *JoinTokenResponse) SetAllocatedIp(v string) {
	o.AllocatedIp = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *JoinTokenResponse) GetExpiresAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *JoinTokenResponse) SetExpiresAt(v int64) {
	o.ExpiresAt = v
}

// GetLeaderEndpoint returns the LeaderEndpoint field value
func (o *JoinTokenResponse) GetLeaderEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaderEndpoint
}

// GetLeaderEndpointOk returns a tuple with the LeaderEndpoint field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetLeaderEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaderEndpoint, true
}

// SetLeaderEndpoint sets field value
func (o *JoinTokenResponse) SetLeaderEndpoint(v string) {
	o.LeaderEndpoint = v
}

// GetLeaderPublicKey returns the LeaderPublicKey field value
func (o *JoinTokenResponse) GetLeaderPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaderPublicKey
}

// GetLeaderPublicKeyOk returns a tuple with the LeaderPublicKey field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetLeaderPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaderPublicKey, true
}

// SetLeaderPublicKey sets field value
func (o *JoinTokenResponse) SetLeaderPublicKey(v string) {
	o.LeaderPublicKey = v
}

// GetOverlayCidr returns the OverlayCidr field value
func (o *JoinTokenResponse) GetOverlayCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OverlayCidr
}

// GetOverlayCidrOk returns a tuple with the OverlayCidr field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetOverlayCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverlayCidr, true
}

// SetOverlayCidr sets field value
func (o *JoinTokenResponse) SetOverlayCidr(v string) {
	o.OverlayCidr = v
}

// GetToken returns the Token field value
func (o *JoinTokenResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *JoinTokenResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *JoinTokenResponse) SetToken(v string) {
	o.Token = v
}

func (o JoinTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JoinTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allocated_ip"] = o.AllocatedIp
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["leader_endpoint"] = o.LeaderEndpoint
	toSerialize["leader_public_key"] = o.LeaderPublicKey
	toSerialize["overlay_cidr"] = o.OverlayCidr
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *JoinTokenResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allocated_ip",
		"expires_at",
		"leader_endpoint",
		"leader_public_key",
		"overlay_cidr",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJoinTokenResponse := _JoinTokenResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJoinTokenResponse)

	if err != nil {
		return err
	}

	*o = JoinTokenResponse(varJoinTokenResponse)

	return err
}

type NullableJoinTokenResponse struct {
	value *JoinTokenResponse
	isSet bool
}

func (v NullableJoinTokenResponse) Get() *JoinTokenResponse {
	return v.value
}

func (v *NullableJoinTokenResponse) Set(val *JoinTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJoinTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJoinTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJoinTokenResponse(val *JoinTokenResponse) *NullableJoinTokenResponse {
	return &NullableJoinTokenResponse{value: val, isSet: true}
}

func (v NullableJoinTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJoinTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


