/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowStep{}

// WorkflowStep A single step in a workflow.
type WorkflowStep struct {
	// The action to perform.
	Action WorkflowAction `json:"action"`
	// Step name (display label).
	Name string `json:"name"`
	// Name of another step (or task id) to run on failure.
	OnFailure NullableString `json:"on_failure,omitempty"`
}

type _WorkflowStep WorkflowStep

// NewWorkflowStep instantiates a new WorkflowStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowStep(action WorkflowAction, name string) *WorkflowStep {
	this := WorkflowStep{}
	this.Action = action
	this.Name = name
	return &this
}

// NewWorkflowStepWithDefaults instantiates a new WorkflowStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowStepWithDefaults() *WorkflowStep {
	this := WorkflowStep{}
	return &this
}

// GetAction returns the Action field value
func (o *WorkflowStep) GetAction() WorkflowAction {
	if o == nil {
		var ret WorkflowAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetActionOk() (*WorkflowAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *WorkflowStep) SetAction(v WorkflowAction) {
	o.Action = v
}

// GetName returns the Name field value
func (o *WorkflowStep) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowStep) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowStep) SetName(v string) {
	o.Name = v
}

// GetOnFailure returns the OnFailure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowStep) GetOnFailure() string {
	if o == nil || IsNil(o.OnFailure.Get()) {
		var ret string
		return ret
	}
	return *o.OnFailure.Get()
}

// GetOnFailureOk returns a tuple with the OnFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowStep) GetOnFailureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OnFailure.Get(), o.OnFailure.IsSet()
}

// HasOnFailure returns a boolean if a field has been set.
func (o *WorkflowStep) HasOnFailure() bool {
	if o != nil && o.OnFailure.IsSet() {
		return true
	}

	return false
}

// SetOnFailure gets a reference to the given NullableString and assigns it to the OnFailure field.
func (o *WorkflowStep) SetOnFailure(v string) {
	o.OnFailure.Set(&v)
}
// SetOnFailureNil sets the value for OnFailure to be an explicit nil
func (o *WorkflowStep) SetOnFailureNil() {
	o.OnFailure.Set(nil)
}

// UnsetOnFailure ensures that no value is present for OnFailure, not even an explicit nil
func (o *WorkflowStep) UnsetOnFailure() {
	o.OnFailure.Unset()
}

func (o WorkflowStep) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["name"] = o.Name
	if o.OnFailure.IsSet() {
		toSerialize["on_failure"] = o.OnFailure.Get()
	}
	return toSerialize, nil
}

func (o *WorkflowStep) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowStep := _WorkflowStep{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowStep)

	if err != nil {
		return err
	}

	*o = WorkflowStep(varWorkflowStep)

	return err
}

type NullableWorkflowStep struct {
	value *WorkflowStep
	isSet bool
}

func (v NullableWorkflowStep) Get() *WorkflowStep {
	return v.value
}

func (v *NullableWorkflowStep) Set(val *WorkflowStep) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowStep) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowStep(val *WorkflowStep) *NullableWorkflowStep {
	return &NullableWorkflowStep{value: val, isSet: true}
}

func (v NullableWorkflowStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


