/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DeploymentStatus - Deployment lifecycle status.
type DeploymentStatus struct {
	DeploymentStatusOneOf *DeploymentStatusOneOf
	DeploymentStatusOneOf1 *DeploymentStatusOneOf1
	DeploymentStatusOneOf2 *DeploymentStatusOneOf2
	DeploymentStatusOneOf3 *DeploymentStatusOneOf3
	DeploymentStatusOneOf4 *DeploymentStatusOneOf4
}

// DeploymentStatusOneOfAsDeploymentStatus is a convenience function that returns DeploymentStatusOneOf wrapped in DeploymentStatus
func DeploymentStatusOneOfAsDeploymentStatus(v *DeploymentStatusOneOf) DeploymentStatus {
	return DeploymentStatus{
		DeploymentStatusOneOf: v,
	}
}

// DeploymentStatusOneOf1AsDeploymentStatus is a convenience function that returns DeploymentStatusOneOf1 wrapped in DeploymentStatus
func DeploymentStatusOneOf1AsDeploymentStatus(v *DeploymentStatusOneOf1) DeploymentStatus {
	return DeploymentStatus{
		DeploymentStatusOneOf1: v,
	}
}

// DeploymentStatusOneOf2AsDeploymentStatus is a convenience function that returns DeploymentStatusOneOf2 wrapped in DeploymentStatus
func DeploymentStatusOneOf2AsDeploymentStatus(v *DeploymentStatusOneOf2) DeploymentStatus {
	return DeploymentStatus{
		DeploymentStatusOneOf2: v,
	}
}

// DeploymentStatusOneOf3AsDeploymentStatus is a convenience function that returns DeploymentStatusOneOf3 wrapped in DeploymentStatus
func DeploymentStatusOneOf3AsDeploymentStatus(v *DeploymentStatusOneOf3) DeploymentStatus {
	return DeploymentStatus{
		DeploymentStatusOneOf3: v,
	}
}

// DeploymentStatusOneOf4AsDeploymentStatus is a convenience function that returns DeploymentStatusOneOf4 wrapped in DeploymentStatus
func DeploymentStatusOneOf4AsDeploymentStatus(v *DeploymentStatusOneOf4) DeploymentStatus {
	return DeploymentStatus{
		DeploymentStatusOneOf4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeploymentStatus) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeploymentStatusOneOf
	err = newStrictDecoder(data).Decode(&dst.DeploymentStatusOneOf)
	if err == nil {
		jsonDeploymentStatusOneOf, _ := json.Marshal(dst.DeploymentStatusOneOf)
		if string(jsonDeploymentStatusOneOf) == "{}" { // empty struct
			dst.DeploymentStatusOneOf = nil
		} else {
			if err = validator.Validate(dst.DeploymentStatusOneOf); err != nil {
				dst.DeploymentStatusOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentStatusOneOf = nil
	}

	// try to unmarshal data into DeploymentStatusOneOf1
	err = newStrictDecoder(data).Decode(&dst.DeploymentStatusOneOf1)
	if err == nil {
		jsonDeploymentStatusOneOf1, _ := json.Marshal(dst.DeploymentStatusOneOf1)
		if string(jsonDeploymentStatusOneOf1) == "{}" { // empty struct
			dst.DeploymentStatusOneOf1 = nil
		} else {
			if err = validator.Validate(dst.DeploymentStatusOneOf1); err != nil {
				dst.DeploymentStatusOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentStatusOneOf1 = nil
	}

	// try to unmarshal data into DeploymentStatusOneOf2
	err = newStrictDecoder(data).Decode(&dst.DeploymentStatusOneOf2)
	if err == nil {
		jsonDeploymentStatusOneOf2, _ := json.Marshal(dst.DeploymentStatusOneOf2)
		if string(jsonDeploymentStatusOneOf2) == "{}" { // empty struct
			dst.DeploymentStatusOneOf2 = nil
		} else {
			if err = validator.Validate(dst.DeploymentStatusOneOf2); err != nil {
				dst.DeploymentStatusOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentStatusOneOf2 = nil
	}

	// try to unmarshal data into DeploymentStatusOneOf3
	err = newStrictDecoder(data).Decode(&dst.DeploymentStatusOneOf3)
	if err == nil {
		jsonDeploymentStatusOneOf3, _ := json.Marshal(dst.DeploymentStatusOneOf3)
		if string(jsonDeploymentStatusOneOf3) == "{}" { // empty struct
			dst.DeploymentStatusOneOf3 = nil
		} else {
			if err = validator.Validate(dst.DeploymentStatusOneOf3); err != nil {
				dst.DeploymentStatusOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentStatusOneOf3 = nil
	}

	// try to unmarshal data into DeploymentStatusOneOf4
	err = newStrictDecoder(data).Decode(&dst.DeploymentStatusOneOf4)
	if err == nil {
		jsonDeploymentStatusOneOf4, _ := json.Marshal(dst.DeploymentStatusOneOf4)
		if string(jsonDeploymentStatusOneOf4) == "{}" { // empty struct
			dst.DeploymentStatusOneOf4 = nil
		} else {
			if err = validator.Validate(dst.DeploymentStatusOneOf4); err != nil {
				dst.DeploymentStatusOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeploymentStatusOneOf4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeploymentStatusOneOf = nil
		dst.DeploymentStatusOneOf1 = nil
		dst.DeploymentStatusOneOf2 = nil
		dst.DeploymentStatusOneOf3 = nil
		dst.DeploymentStatusOneOf4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeploymentStatus)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DeploymentStatus)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeploymentStatus) MarshalJSON() ([]byte, error) {
	if src.DeploymentStatusOneOf != nil {
		return json.Marshal(&src.DeploymentStatusOneOf)
	}

	if src.DeploymentStatusOneOf1 != nil {
		return json.Marshal(&src.DeploymentStatusOneOf1)
	}

	if src.DeploymentStatusOneOf2 != nil {
		return json.Marshal(&src.DeploymentStatusOneOf2)
	}

	if src.DeploymentStatusOneOf3 != nil {
		return json.Marshal(&src.DeploymentStatusOneOf3)
	}

	if src.DeploymentStatusOneOf4 != nil {
		return json.Marshal(&src.DeploymentStatusOneOf4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeploymentStatus) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeploymentStatusOneOf != nil {
		return obj.DeploymentStatusOneOf
	}

	if obj.DeploymentStatusOneOf1 != nil {
		return obj.DeploymentStatusOneOf1
	}

	if obj.DeploymentStatusOneOf2 != nil {
		return obj.DeploymentStatusOneOf2
	}

	if obj.DeploymentStatusOneOf3 != nil {
		return obj.DeploymentStatusOneOf3
	}

	if obj.DeploymentStatusOneOf4 != nil {
		return obj.DeploymentStatusOneOf4
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DeploymentStatus) GetActualInstanceValue() (interface{}) {
	if obj.DeploymentStatusOneOf != nil {
		return *obj.DeploymentStatusOneOf
	}

	if obj.DeploymentStatusOneOf1 != nil {
		return *obj.DeploymentStatusOneOf1
	}

	if obj.DeploymentStatusOneOf2 != nil {
		return *obj.DeploymentStatusOneOf2
	}

	if obj.DeploymentStatusOneOf3 != nil {
		return *obj.DeploymentStatusOneOf3
	}

	if obj.DeploymentStatusOneOf4 != nil {
		return *obj.DeploymentStatusOneOf4
	}

	// all schemas are nil
	return nil
}

type NullableDeploymentStatus struct {
	value *DeploymentStatus
	isSet bool
}

func (v NullableDeploymentStatus) Get() *DeploymentStatus {
	return v.value
}

func (v *NullableDeploymentStatus) Set(val *DeploymentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentStatus(val *DeploymentStatus) *NullableDeploymentStatus {
	return &NullableDeploymentStatus{value: val, isSet: true}
}

func (v NullableDeploymentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


