/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceSummary{}

// ServiceSummary Service summary
type ServiceSummary struct {
	// Deployment name
	Deployment string `json:"deployment"`
	// Desired replica count
	DesiredReplicas int32 `json:"desired_replicas"`
	// Service endpoints
	Endpoints []ServiceEndpoint `json:"endpoints"`
	// Service name
	Name string `json:"name"`
	// Current replica count
	Replicas int32 `json:"replicas"`
	// Service status
	Status string `json:"status"`
}

type _ServiceSummary ServiceSummary

// NewServiceSummary instantiates a new ServiceSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceSummary(deployment string, desiredReplicas int32, endpoints []ServiceEndpoint, name string, replicas int32, status string) *ServiceSummary {
	this := ServiceSummary{}
	this.Deployment = deployment
	this.DesiredReplicas = desiredReplicas
	this.Endpoints = endpoints
	this.Name = name
	this.Replicas = replicas
	this.Status = status
	return &this
}

// NewServiceSummaryWithDefaults instantiates a new ServiceSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceSummaryWithDefaults() *ServiceSummary {
	this := ServiceSummary{}
	return &this
}

// GetDeployment returns the Deployment field value
func (o *ServiceSummary) GetDeployment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetDeploymentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deployment, true
}

// SetDeployment sets field value
func (o *ServiceSummary) SetDeployment(v string) {
	o.Deployment = v
}

// GetDesiredReplicas returns the DesiredReplicas field value
func (o *ServiceSummary) GetDesiredReplicas() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DesiredReplicas
}

// GetDesiredReplicasOk returns a tuple with the DesiredReplicas field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetDesiredReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DesiredReplicas, true
}

// SetDesiredReplicas sets field value
func (o *ServiceSummary) SetDesiredReplicas(v int32) {
	o.DesiredReplicas = v
}

// GetEndpoints returns the Endpoints field value
func (o *ServiceSummary) GetEndpoints() []ServiceEndpoint {
	if o == nil {
		var ret []ServiceEndpoint
		return ret
	}

	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetEndpointsOk() ([]ServiceEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// SetEndpoints sets field value
func (o *ServiceSummary) SetEndpoints(v []ServiceEndpoint) {
	o.Endpoints = v
}

// GetName returns the Name field value
func (o *ServiceSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceSummary) SetName(v string) {
	o.Name = v
}

// GetReplicas returns the Replicas field value
func (o *ServiceSummary) GetReplicas() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetReplicasOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Replicas, true
}

// SetReplicas sets field value
func (o *ServiceSummary) SetReplicas(v int32) {
	o.Replicas = v
}

// GetStatus returns the Status field value
func (o *ServiceSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ServiceSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ServiceSummary) SetStatus(v string) {
	o.Status = v
}

func (o ServiceSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deployment"] = o.Deployment
	toSerialize["desired_replicas"] = o.DesiredReplicas
	toSerialize["endpoints"] = o.Endpoints
	toSerialize["name"] = o.Name
	toSerialize["replicas"] = o.Replicas
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ServiceSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deployment",
		"desired_replicas",
		"endpoints",
		"name",
		"replicas",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceSummary := _ServiceSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceSummary)

	if err != nil {
		return err
	}

	*o = ServiceSummary(varServiceSummary)

	return err
}

type NullableServiceSummary struct {
	value *ServiceSummary
	isSet bool
}

func (v NullableServiceSummary) Get() *ServiceSummary {
	return v.value
}

func (v *NullableServiceSummary) Set(val *ServiceSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceSummary(val *ServiceSummary) *NullableServiceSummary {
	return &NullableServiceSummary{value: val, isSet: true}
}

func (v NullableServiceSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


