/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VolumeSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeSummary{}

// VolumeSummary Legacy response shape kept for backwards compatibility with older SDK consumers that deserialize strictly. New consumers should use [`VolumeInfo`]. `list_volumes` now returns [`VolumeInfo`] which is a strict superset of the fields in `VolumeSummary`.
type VolumeSummary struct {
	// Volume name (directory name).
	Name string `json:"name"`
	// Host filesystem path.
	Path string `json:"path"`
	// Approximate size in bytes.
	SizeBytes NullableInt64 `json:"size_bytes,omitempty"`
}

type _VolumeSummary VolumeSummary

// NewVolumeSummary instantiates a new VolumeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeSummary(name string, path string) *VolumeSummary {
	this := VolumeSummary{}
	this.Name = name
	this.Path = path
	return &this
}

// NewVolumeSummaryWithDefaults instantiates a new VolumeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeSummaryWithDefaults() *VolumeSummary {
	this := VolumeSummary{}
	return &this
}

// GetName returns the Name field value
func (o *VolumeSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VolumeSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VolumeSummary) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *VolumeSummary) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *VolumeSummary) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *VolumeSummary) SetPath(v string) {
	o.Path = v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VolumeSummary) GetSizeBytes() int64 {
	if o == nil || IsNil(o.SizeBytes.Get()) {
		var ret int64
		return ret
	}
	return *o.SizeBytes.Get()
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeSummary) GetSizeBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SizeBytes.Get(), o.SizeBytes.IsSet()
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *VolumeSummary) HasSizeBytes() bool {
	if o != nil && o.SizeBytes.IsSet() {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given NullableInt64 and assigns it to the SizeBytes field.
func (o *VolumeSummary) SetSizeBytes(v int64) {
	o.SizeBytes.Set(&v)
}
// SetSizeBytesNil sets the value for SizeBytes to be an explicit nil
func (o *VolumeSummary) SetSizeBytesNil() {
	o.SizeBytes.Set(nil)
}

// UnsetSizeBytes ensures that no value is present for SizeBytes, not even an explicit nil
func (o *VolumeSummary) UnsetSizeBytes() {
	o.SizeBytes.Unset()
}

func (o VolumeSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	if o.SizeBytes.IsSet() {
		toSerialize["size_bytes"] = o.SizeBytes.Get()
	}
	return toSerialize, nil
}

func (o *VolumeSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeSummary := _VolumeSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVolumeSummary)

	if err != nil {
		return err
	}

	*o = VolumeSummary(varVolumeSummary)

	return err
}

type NullableVolumeSummary struct {
	value *VolumeSummary
	isSet bool
}

func (v NullableVolumeSummary) Get() *VolumeSummary {
	return v.value
}

func (v *NullableVolumeSummary) Set(val *VolumeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeSummary(val *VolumeSummary) *NullableVolumeSummary {
	return &NullableVolumeSummary{value: val, isSet: true}
}

func (v NullableVolumeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


