/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForceLeaderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForceLeaderResponse{}

// ForceLeaderResponse Response body for force-leader operation.
type ForceLeaderResponse struct {
	Message string `json:"message"`
	// Number of cluster nodes whose state was preserved
	PreservedNodes int32 `json:"preserved_nodes"`
	// Number of services whose state was preserved
	PreservedServices int32 `json:"preserved_services"`
	Success bool `json:"success"`
}

type _ForceLeaderResponse ForceLeaderResponse

// NewForceLeaderResponse instantiates a new ForceLeaderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForceLeaderResponse(message string, preservedNodes int32, preservedServices int32, success bool) *ForceLeaderResponse {
	this := ForceLeaderResponse{}
	this.Message = message
	this.PreservedNodes = preservedNodes
	this.PreservedServices = preservedServices
	this.Success = success
	return &this
}

// NewForceLeaderResponseWithDefaults instantiates a new ForceLeaderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForceLeaderResponseWithDefaults() *ForceLeaderResponse {
	this := ForceLeaderResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *ForceLeaderResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ForceLeaderResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ForceLeaderResponse) SetMessage(v string) {
	o.Message = v
}

// GetPreservedNodes returns the PreservedNodes field value
func (o *ForceLeaderResponse) GetPreservedNodes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PreservedNodes
}

// GetPreservedNodesOk returns a tuple with the PreservedNodes field value
// and a boolean to check if the value has been set.
func (o *ForceLeaderResponse) GetPreservedNodesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreservedNodes, true
}

// SetPreservedNodes sets field value
func (o *ForceLeaderResponse) SetPreservedNodes(v int32) {
	o.PreservedNodes = v
}

// GetPreservedServices returns the PreservedServices field value
func (o *ForceLeaderResponse) GetPreservedServices() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PreservedServices
}

// GetPreservedServicesOk returns a tuple with the PreservedServices field value
// and a boolean to check if the value has been set.
func (o *ForceLeaderResponse) GetPreservedServicesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreservedServices, true
}

// SetPreservedServices sets field value
func (o *ForceLeaderResponse) SetPreservedServices(v int32) {
	o.PreservedServices = v
}

// GetSuccess returns the Success field value
func (o *ForceLeaderResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ForceLeaderResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ForceLeaderResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o ForceLeaderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForceLeaderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["preserved_nodes"] = o.PreservedNodes
	toSerialize["preserved_services"] = o.PreservedServices
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *ForceLeaderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"preserved_nodes",
		"preserved_services",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForceLeaderResponse := _ForceLeaderResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForceLeaderResponse)

	if err != nil {
		return err
	}

	*o = ForceLeaderResponse(varForceLeaderResponse)

	return err
}

type NullableForceLeaderResponse struct {
	value *ForceLeaderResponse
	isSet bool
}

func (v NullableForceLeaderResponse) Get() *ForceLeaderResponse {
	return v.value
}

func (v *NullableForceLeaderResponse) Set(val *ForceLeaderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableForceLeaderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableForceLeaderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForceLeaderResponse(val *ForceLeaderResponse) *NullableForceLeaderResponse {
	return &NullableForceLeaderResponse{value: val, isSet: true}
}

func (v NullableForceLeaderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForceLeaderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


