/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateSecretRequest{}

// RotateSecretRequest Request body for secret rotation.
type RotateSecretRequest struct {
	// Optional per-secret node affinity update. `None` here means \"leave existing affinity unchanged\"; to clear affinity explicitly, pass an empty selector via a separate update endpoint (Phase 2).
	NodeAffinity NullableNodeAffinity `json:"node_affinity,omitempty"`
	// The new secret value (will be encrypted at rest).
	Value string `json:"value"`
}

type _RotateSecretRequest RotateSecretRequest

// NewRotateSecretRequest instantiates a new RotateSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateSecretRequest(value string) *RotateSecretRequest {
	this := RotateSecretRequest{}
	this.Value = value
	return &this
}

// NewRotateSecretRequestWithDefaults instantiates a new RotateSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateSecretRequestWithDefaults() *RotateSecretRequest {
	this := RotateSecretRequest{}
	return &this
}

// GetNodeAffinity returns the NodeAffinity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotateSecretRequest) GetNodeAffinity() NodeAffinity {
	if o == nil || IsNil(o.NodeAffinity.Get()) {
		var ret NodeAffinity
		return ret
	}
	return *o.NodeAffinity.Get()
}

// GetNodeAffinityOk returns a tuple with the NodeAffinity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotateSecretRequest) GetNodeAffinityOk() (*NodeAffinity, bool) {
	if o == nil {
		return nil, false
	}
	return o.NodeAffinity.Get(), o.NodeAffinity.IsSet()
}

// HasNodeAffinity returns a boolean if a field has been set.
func (o *RotateSecretRequest) HasNodeAffinity() bool {
	if o != nil && o.NodeAffinity.IsSet() {
		return true
	}

	return false
}

// SetNodeAffinity gets a reference to the given NullableNodeAffinity and assigns it to the NodeAffinity field.
func (o *RotateSecretRequest) SetNodeAffinity(v NodeAffinity) {
	o.NodeAffinity.Set(&v)
}
// SetNodeAffinityNil sets the value for NodeAffinity to be an explicit nil
func (o *RotateSecretRequest) SetNodeAffinityNil() {
	o.NodeAffinity.Set(nil)
}

// UnsetNodeAffinity ensures that no value is present for NodeAffinity, not even an explicit nil
func (o *RotateSecretRequest) UnsetNodeAffinity() {
	o.NodeAffinity.Unset()
}

// GetValue returns the Value field value
func (o *RotateSecretRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RotateSecretRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RotateSecretRequest) SetValue(v string) {
	o.Value = v
}

func (o RotateSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NodeAffinity.IsSet() {
		toSerialize["node_affinity"] = o.NodeAffinity.Get()
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *RotateSecretRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateSecretRequest := _RotateSecretRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateSecretRequest)

	if err != nil {
		return err
	}

	*o = RotateSecretRequest(varRotateSecretRequest)

	return err
}

type NullableRotateSecretRequest struct {
	value *RotateSecretRequest
	isSet bool
}

func (v NullableRotateSecretRequest) Get() *RotateSecretRequest {
	return v.value
}

func (v *NullableRotateSecretRequest) Set(val *RotateSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateSecretRequest(val *RotateSecretRequest) *NullableRotateSecretRequest {
	return &NullableRotateSecretRequest{value: val, isSet: true}
}

func (v NullableRotateSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


