/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
)

// checks if the ClusterUpgradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterUpgradeRequest{}

// ClusterUpgradeRequest Request body for `POST /api/v1/cluster/upgrade`.  Drives a leader-coordinated rolling daemon-binary upgrade across the cluster. The leader walks every follower in ascending `node_id` order (and finally upgrades itself), instructing each to download the target `zlayer` release and restart. Followers come back on the same advertise address and re-join Raft; the leader waits for each one to be healthy again before moving on.
type ClusterUpgradeRequest struct {
	// Seconds to pause between node upgrades after each follower comes back healthy.
	CooldownSecs *int64 `json:"cooldown_secs,omitempty"`
	// Abort the rollout if any follower fails to come back healthy.
	Strict *bool `json:"strict,omitempty"`
	// Target zlayer version (e.g. \"v0.12.0\"). Defaults to latest GitHub release if absent.
	Version NullableString `json:"version,omitempty"`
}

// NewClusterUpgradeRequest instantiates a new ClusterUpgradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterUpgradeRequest() *ClusterUpgradeRequest {
	this := ClusterUpgradeRequest{}
	return &this
}

// NewClusterUpgradeRequestWithDefaults instantiates a new ClusterUpgradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterUpgradeRequestWithDefaults() *ClusterUpgradeRequest {
	this := ClusterUpgradeRequest{}
	return &this
}

// GetCooldownSecs returns the CooldownSecs field value if set, zero value otherwise.
func (o *ClusterUpgradeRequest) GetCooldownSecs() int64 {
	if o == nil || IsNil(o.CooldownSecs) {
		var ret int64
		return ret
	}
	return *o.CooldownSecs
}

// GetCooldownSecsOk returns a tuple with the CooldownSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterUpgradeRequest) GetCooldownSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.CooldownSecs) {
		return nil, false
	}
	return o.CooldownSecs, true
}

// HasCooldownSecs returns a boolean if a field has been set.
func (o *ClusterUpgradeRequest) HasCooldownSecs() bool {
	if o != nil && !IsNil(o.CooldownSecs) {
		return true
	}

	return false
}

// SetCooldownSecs gets a reference to the given int64 and assigns it to the CooldownSecs field.
func (o *ClusterUpgradeRequest) SetCooldownSecs(v int64) {
	o.CooldownSecs = &v
}

// GetStrict returns the Strict field value if set, zero value otherwise.
func (o *ClusterUpgradeRequest) GetStrict() bool {
	if o == nil || IsNil(o.Strict) {
		var ret bool
		return ret
	}
	return *o.Strict
}

// GetStrictOk returns a tuple with the Strict field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterUpgradeRequest) GetStrictOk() (*bool, bool) {
	if o == nil || IsNil(o.Strict) {
		return nil, false
	}
	return o.Strict, true
}

// HasStrict returns a boolean if a field has been set.
func (o *ClusterUpgradeRequest) HasStrict() bool {
	if o != nil && !IsNil(o.Strict) {
		return true
	}

	return false
}

// SetStrict gets a reference to the given bool and assigns it to the Strict field.
func (o *ClusterUpgradeRequest) SetStrict(v bool) {
	o.Strict = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClusterUpgradeRequest) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClusterUpgradeRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *ClusterUpgradeRequest) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *ClusterUpgradeRequest) SetVersion(v string) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *ClusterUpgradeRequest) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *ClusterUpgradeRequest) UnsetVersion() {
	o.Version.Unset()
}

func (o ClusterUpgradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterUpgradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CooldownSecs) {
		toSerialize["cooldown_secs"] = o.CooldownSecs
	}
	if !IsNil(o.Strict) {
		toSerialize["strict"] = o.Strict
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

type NullableClusterUpgradeRequest struct {
	value *ClusterUpgradeRequest
	isSet bool
}

func (v NullableClusterUpgradeRequest) Get() *ClusterUpgradeRequest {
	return v.value
}

func (v *NullableClusterUpgradeRequest) Set(val *ClusterUpgradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterUpgradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterUpgradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterUpgradeRequest(val *ClusterUpgradeRequest) *NullableClusterUpgradeRequest {
	return &NullableClusterUpgradeRequest{value: val, isSet: true}
}

func (v NullableClusterUpgradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterUpgradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


