/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DaemonEventOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaemonEventOneOf2{}

// DaemonEventOneOf2 struct for DaemonEventOneOf2
type DaemonEventOneOf2 struct {
	// Wall-clock time.
	At time.Time `json:"at"`
	// Container id, populated for `Connect`/`Disconnect`.
	ContainerId *string `json:"container_id,omitempty"`
	// Network driver (e.g. `bridge`, `overlay`).
	Driver *string `json:"driver,omitempty"`
	// Network identifier (registry id).
	Id string `json:"id"`
	Kind NetworkEventKind `json:"kind"`
	// Human-readable network name.
	Name string `json:"name"`
	Resource string `json:"resource"`
}

type _DaemonEventOneOf2 DaemonEventOneOf2

// NewDaemonEventOneOf2 instantiates a new DaemonEventOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaemonEventOneOf2(at time.Time, id string, kind NetworkEventKind, name string, resource string) *DaemonEventOneOf2 {
	this := DaemonEventOneOf2{}
	this.At = at
	this.Id = id
	this.Kind = kind
	this.Name = name
	this.Resource = resource
	return &this
}

// NewDaemonEventOneOf2WithDefaults instantiates a new DaemonEventOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaemonEventOneOf2WithDefaults() *DaemonEventOneOf2 {
	this := DaemonEventOneOf2{}
	return &this
}

// GetAt returns the At field value
func (o *DaemonEventOneOf2) GetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.At
}

// GetAtOk returns a tuple with the At field value
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.At, true
}

// SetAt sets field value
func (o *DaemonEventOneOf2) SetAt(v time.Time) {
	o.At = v
}

// GetContainerId returns the ContainerId field value if set, zero value otherwise.
func (o *DaemonEventOneOf2) GetContainerId() string {
	if o == nil || IsNil(o.ContainerId) {
		var ret string
		return ret
	}
	return *o.ContainerId
}

// GetContainerIdOk returns a tuple with the ContainerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetContainerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContainerId) {
		return nil, false
	}
	return o.ContainerId, true
}

// HasContainerId returns a boolean if a field has been set.
func (o *DaemonEventOneOf2) HasContainerId() bool {
	if o != nil && !IsNil(o.ContainerId) {
		return true
	}

	return false
}

// SetContainerId gets a reference to the given string and assigns it to the ContainerId field.
func (o *DaemonEventOneOf2) SetContainerId(v string) {
	o.ContainerId = &v
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *DaemonEventOneOf2) GetDriver() string {
	if o == nil || IsNil(o.Driver) {
		var ret string
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetDriverOk() (*string, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *DaemonEventOneOf2) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given string and assigns it to the Driver field.
func (o *DaemonEventOneOf2) SetDriver(v string) {
	o.Driver = &v
}

// GetId returns the Id field value
func (o *DaemonEventOneOf2) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DaemonEventOneOf2) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *DaemonEventOneOf2) GetKind() NetworkEventKind {
	if o == nil {
		var ret NetworkEventKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetKindOk() (*NetworkEventKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *DaemonEventOneOf2) SetKind(v NetworkEventKind) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *DaemonEventOneOf2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DaemonEventOneOf2) SetName(v string) {
	o.Name = v
}

// GetResource returns the Resource field value
func (o *DaemonEventOneOf2) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *DaemonEventOneOf2) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *DaemonEventOneOf2) SetResource(v string) {
	o.Resource = v
}

func (o DaemonEventOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaemonEventOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["at"] = o.At
	if !IsNil(o.ContainerId) {
		toSerialize["container_id"] = o.ContainerId
	}
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["resource"] = o.Resource
	return toSerialize, nil
}

func (o *DaemonEventOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"at",
		"id",
		"kind",
		"name",
		"resource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDaemonEventOneOf2 := _DaemonEventOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDaemonEventOneOf2)

	if err != nil {
		return err
	}

	*o = DaemonEventOneOf2(varDaemonEventOneOf2)

	return err
}

type NullableDaemonEventOneOf2 struct {
	value *DaemonEventOneOf2
	isSet bool
}

func (v NullableDaemonEventOneOf2) Get() *DaemonEventOneOf2 {
	return v.value
}

func (v *NullableDaemonEventOneOf2) Set(val *DaemonEventOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableDaemonEventOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableDaemonEventOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaemonEventOneOf2(val *DaemonEventOneOf2) *NullableDaemonEventOneOf2 {
	return &NullableDaemonEventOneOf2{value: val, isSet: true}
}

func (v NullableDaemonEventOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaemonEventOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


