/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NatCandidateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NatCandidateDto{}

// NatCandidateDto Locally gathered NAT candidate (`Host` / `ServerReflexive` / `Relay`).
type NatCandidateDto struct {
	// Address (host:port)
	Address string `json:"address"`
	// `Host` / `ServerReflexive` / `Relay`
	Kind string `json:"kind"`
	// Priority (higher = preferred)
	Priority int32 `json:"priority"`
	// Transport (e.g. \"udp\")
	Transport string `json:"transport"`
}

type _NatCandidateDto NatCandidateDto

// NewNatCandidateDto instantiates a new NatCandidateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNatCandidateDto(address string, kind string, priority int32, transport string) *NatCandidateDto {
	this := NatCandidateDto{}
	this.Address = address
	this.Kind = kind
	this.Priority = priority
	this.Transport = transport
	return &this
}

// NewNatCandidateDtoWithDefaults instantiates a new NatCandidateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNatCandidateDtoWithDefaults() *NatCandidateDto {
	this := NatCandidateDto{}
	return &this
}

// GetAddress returns the Address field value
func (o *NatCandidateDto) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *NatCandidateDto) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *NatCandidateDto) SetAddress(v string) {
	o.Address = v
}

// GetKind returns the Kind field value
func (o *NatCandidateDto) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *NatCandidateDto) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *NatCandidateDto) SetKind(v string) {
	o.Kind = v
}

// GetPriority returns the Priority field value
func (o *NatCandidateDto) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *NatCandidateDto) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *NatCandidateDto) SetPriority(v int32) {
	o.Priority = v
}

// GetTransport returns the Transport field value
func (o *NatCandidateDto) GetTransport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transport
}

// GetTransportOk returns a tuple with the Transport field value
// and a boolean to check if the value has been set.
func (o *NatCandidateDto) GetTransportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transport, true
}

// SetTransport sets field value
func (o *NatCandidateDto) SetTransport(v string) {
	o.Transport = v
}

func (o NatCandidateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NatCandidateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["kind"] = o.Kind
	toSerialize["priority"] = o.Priority
	toSerialize["transport"] = o.Transport
	return toSerialize, nil
}

func (o *NatCandidateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"kind",
		"priority",
		"transport",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNatCandidateDto := _NatCandidateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNatCandidateDto)

	if err != nil {
		return err
	}

	*o = NatCandidateDto(varNatCandidateDto)

	return err
}

type NullableNatCandidateDto struct {
	value *NatCandidateDto
	isSet bool
}

func (v NullableNatCandidateDto) Get() *NatCandidateDto {
	return v.value
}

func (v *NullableNatCandidateDto) Set(val *NatCandidateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableNatCandidateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableNatCandidateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNatCandidateDto(val *NatCandidateDto) *NullableNatCandidateDto {
	return &NullableNatCandidateDto{value: val, isSet: true}
}

func (v NullableNatCandidateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNatCandidateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


