/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkModeOneOf1Container type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkModeOneOf1Container{}

// NetworkModeOneOf1Container Attach to another container's network namespace (Docker `--network container:<id>`).
type NetworkModeOneOf1Container struct {
	Id string `json:"id"`
}

type _NetworkModeOneOf1Container NetworkModeOneOf1Container

// NewNetworkModeOneOf1Container instantiates a new NetworkModeOneOf1Container object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkModeOneOf1Container(id string) *NetworkModeOneOf1Container {
	this := NetworkModeOneOf1Container{}
	this.Id = id
	return &this
}

// NewNetworkModeOneOf1ContainerWithDefaults instantiates a new NetworkModeOneOf1Container object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkModeOneOf1ContainerWithDefaults() *NetworkModeOneOf1Container {
	this := NetworkModeOneOf1Container{}
	return &this
}

// GetId returns the Id field value
func (o *NetworkModeOneOf1Container) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkModeOneOf1Container) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkModeOneOf1Container) SetId(v string) {
	o.Id = v
}

func (o NetworkModeOneOf1Container) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkModeOneOf1Container) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *NetworkModeOneOf1Container) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkModeOneOf1Container := _NetworkModeOneOf1Container{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkModeOneOf1Container)

	if err != nil {
		return err
	}

	*o = NetworkModeOneOf1Container(varNetworkModeOneOf1Container)

	return err
}

type NullableNetworkModeOneOf1Container struct {
	value *NetworkModeOneOf1Container
	isSet bool
}

func (v NullableNetworkModeOneOf1Container) Get() *NetworkModeOneOf1Container {
	return v.value
}

func (v *NullableNetworkModeOneOf1Container) Set(val *NetworkModeOneOf1Container) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkModeOneOf1Container) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkModeOneOf1Container) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkModeOneOf1Container(val *NetworkModeOneOf1Container) *NullableNetworkModeOneOf1Container {
	return &NullableNetworkModeOneOf1Container{value: val, isSet: true}
}

func (v NullableNetworkModeOneOf1Container) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkModeOneOf1Container) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


