/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeError{}

// UpgradeError Per-node error captured during a rolling upgrade.
type UpgradeError struct {
	Message string `json:"message"`
	NodeId int64 `json:"node_id"`
}

type _UpgradeError UpgradeError

// NewUpgradeError instantiates a new UpgradeError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeError(message string, nodeId int64) *UpgradeError {
	this := UpgradeError{}
	this.Message = message
	this.NodeId = nodeId
	return &this
}

// NewUpgradeErrorWithDefaults instantiates a new UpgradeError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeErrorWithDefaults() *UpgradeError {
	this := UpgradeError{}
	return &this
}

// GetMessage returns the Message field value
func (o *UpgradeError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UpgradeError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UpgradeError) SetMessage(v string) {
	o.Message = v
}

// GetNodeId returns the NodeId field value
func (o *UpgradeError) GetNodeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *UpgradeError) GetNodeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *UpgradeError) SetNodeId(v int64) {
	o.NodeId = v
}

func (o UpgradeError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["node_id"] = o.NodeId
	return toSerialize, nil
}

func (o *UpgradeError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeError := _UpgradeError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeError)

	if err != nil {
		return err
	}

	*o = UpgradeError(varUpgradeError)

	return err
}

type NullableUpgradeError struct {
	value *UpgradeError
	isSet bool
}

func (v NullableUpgradeError) Get() *UpgradeError {
	return v.value
}

func (v *NullableUpgradeError) Set(val *UpgradeError) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeError) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeError(val *UpgradeError) *NullableUpgradeError {
	return &NullableUpgradeError{value: val, isSet: true}
}

func (v NullableUpgradeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


