/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
)

// checks if the UpdateNotifierRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotifierRequest{}

// UpdateNotifierRequest Body for `PATCH /api/v1/notifiers/{id}`.
type UpdateNotifierRequest struct {
	// Updated configuration.
	Config NullableNotifierConfig `json:"config,omitempty"`
	// Updated enabled flag.
	Enabled NullableBool `json:"enabled,omitempty"`
	// Updated name.
	Name NullableString `json:"name,omitempty"`
}

// NewUpdateNotifierRequest instantiates a new UpdateNotifierRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotifierRequest() *UpdateNotifierRequest {
	this := UpdateNotifierRequest{}
	return &this
}

// NewUpdateNotifierRequestWithDefaults instantiates a new UpdateNotifierRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotifierRequestWithDefaults() *UpdateNotifierRequest {
	this := UpdateNotifierRequest{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotifierRequest) GetConfig() NotifierConfig {
	if o == nil || IsNil(o.Config.Get()) {
		var ret NotifierConfig
		return ret
	}
	return *o.Config.Get()
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotifierRequest) GetConfigOk() (*NotifierConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config.Get(), o.Config.IsSet()
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateNotifierRequest) HasConfig() bool {
	if o != nil && o.Config.IsSet() {
		return true
	}

	return false
}

// SetConfig gets a reference to the given NullableNotifierConfig and assigns it to the Config field.
func (o *UpdateNotifierRequest) SetConfig(v NotifierConfig) {
	o.Config.Set(&v)
}
// SetConfigNil sets the value for Config to be an explicit nil
func (o *UpdateNotifierRequest) SetConfigNil() {
	o.Config.Set(nil)
}

// UnsetConfig ensures that no value is present for Config, not even an explicit nil
func (o *UpdateNotifierRequest) UnsetConfig() {
	o.Config.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotifierRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotifierRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateNotifierRequest) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *UpdateNotifierRequest) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}
// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *UpdateNotifierRequest) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *UpdateNotifierRequest) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNotifierRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNotifierRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNotifierRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateNotifierRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateNotifierRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateNotifierRequest) UnsetName() {
	o.Name.Unset()
}

func (o UpdateNotifierRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotifierRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config.IsSet() {
		toSerialize["config"] = o.Config.Get()
	}
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableUpdateNotifierRequest struct {
	value *UpdateNotifierRequest
	isSet bool
}

func (v NullableUpdateNotifierRequest) Get() *UpdateNotifierRequest {
	return v.value
}

func (v *NullableUpdateNotifierRequest) Set(val *UpdateNotifierRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotifierRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotifierRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotifierRequest(val *UpdateNotifierRequest) *NullableUpdateNotifierRequest {
	return &NullableUpdateNotifierRequest{value: val, isSet: true}
}

func (v NullableUpdateNotifierRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotifierRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


