/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BridgeNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BridgeNetwork{}

// BridgeNetwork A user-defined bridge or overlay network that containers can attach to.
type BridgeNetwork struct {
	// Creation timestamp (UTC, RFC 3339).
	CreatedAt time.Time `json:"created_at"`
	// Driver backing the network (bridge vs. overlay).
	Driver *BridgeNetworkDriver `json:"driver,omitempty"`
	// Opaque server-generated identifier (UUID v4).
	Id string `json:"id"`
	// If true, containers attached to this network cannot reach the outside world — only other containers on the same network.
	Internal *bool `json:"internal,omitempty"`
	// Arbitrary key/value labels for filtering and grouping.
	Labels map[string]string `json:"labels,omitempty"`
	// Human-readable, unique name (must match `^[a-z0-9][a-z0-9_-]{0,63}$`).
	Name string `json:"name"`
	// IPv4/IPv6 subnet in CIDR notation (e.g. `\"10.240.0.0/24\"`).
	Subnet NullableString `json:"subnet,omitempty"`
}

type _BridgeNetwork BridgeNetwork

// NewBridgeNetwork instantiates a new BridgeNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBridgeNetwork(createdAt time.Time, id string, name string) *BridgeNetwork {
	this := BridgeNetwork{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Name = name
	return &this
}

// NewBridgeNetworkWithDefaults instantiates a new BridgeNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBridgeNetworkWithDefaults() *BridgeNetwork {
	this := BridgeNetwork{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *BridgeNetwork) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BridgeNetwork) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *BridgeNetwork) GetDriver() BridgeNetworkDriver {
	if o == nil || IsNil(o.Driver) {
		var ret BridgeNetworkDriver
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetDriverOk() (*BridgeNetworkDriver, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *BridgeNetwork) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given BridgeNetworkDriver and assigns it to the Driver field.
func (o *BridgeNetwork) SetDriver(v BridgeNetworkDriver) {
	o.Driver = &v
}

// GetId returns the Id field value
func (o *BridgeNetwork) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BridgeNetwork) SetId(v string) {
	o.Id = v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *BridgeNetwork) GetInternal() bool {
	if o == nil || IsNil(o.Internal) {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetInternalOk() (*bool, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *BridgeNetwork) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *BridgeNetwork) SetInternal(v bool) {
	o.Internal = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *BridgeNetwork) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *BridgeNetwork) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *BridgeNetwork) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetName returns the Name field value
func (o *BridgeNetwork) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BridgeNetwork) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BridgeNetwork) SetName(v string) {
	o.Name = v
}

// GetSubnet returns the Subnet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BridgeNetwork) GetSubnet() string {
	if o == nil || IsNil(o.Subnet.Get()) {
		var ret string
		return ret
	}
	return *o.Subnet.Get()
}

// GetSubnetOk returns a tuple with the Subnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BridgeNetwork) GetSubnetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnet.Get(), o.Subnet.IsSet()
}

// HasSubnet returns a boolean if a field has been set.
func (o *BridgeNetwork) HasSubnet() bool {
	if o != nil && o.Subnet.IsSet() {
		return true
	}

	return false
}

// SetSubnet gets a reference to the given NullableString and assigns it to the Subnet field.
func (o *BridgeNetwork) SetSubnet(v string) {
	o.Subnet.Set(&v)
}
// SetSubnetNil sets the value for Subnet to be an explicit nil
func (o *BridgeNetwork) SetSubnetNil() {
	o.Subnet.Set(nil)
}

// UnsetSubnet ensures that no value is present for Subnet, not even an explicit nil
func (o *BridgeNetwork) UnsetSubnet() {
	o.Subnet.Unset()
}

func (o BridgeNetwork) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BridgeNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["name"] = o.Name
	if o.Subnet.IsSet() {
		toSerialize["subnet"] = o.Subnet.Get()
	}
	return toSerialize, nil
}

func (o *BridgeNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBridgeNetwork := _BridgeNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBridgeNetwork)

	if err != nil {
		return err
	}

	*o = BridgeNetwork(varBridgeNetwork)

	return err
}

type NullableBridgeNetwork struct {
	value *BridgeNetwork
	isSet bool
}

func (v NullableBridgeNetwork) Get() *BridgeNetwork {
	return v.value
}

func (v *NullableBridgeNetwork) Set(val *BridgeNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgeNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgeNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgeNetwork(val *BridgeNetwork) *NullableBridgeNetwork {
	return &NullableBridgeNetwork{value: val, isSet: true}
}

func (v NullableBridgeNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgeNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


