/*
ZLayer API

Container orchestration API for ZLayer

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zlayer

import (
	"encoding/json"
	"fmt"
)

// OsKind Operating system a service needs to run on.  Mirrors the OS half of an OCI platform descriptor. Canonical wire strings match Go's `GOOS` values (e.g. `\"linux\"`, `\"windows\"`, `\"darwin\"`).
type OsKind string

// List of OsKind
const (
	OSKIND_LINUX OsKind = "linux"
	OSKIND_WINDOWS OsKind = "windows"
	OSKIND_MACOS OsKind = "macos"
)

// All allowed values of OsKind enum
var AllowedOsKindEnumValues = []OsKind{
	"linux",
	"windows",
	"macos",
}

func (v *OsKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OsKind(value)
	for _, existing := range AllowedOsKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OsKind", value)
}

// NewOsKindFromValue returns a pointer to a valid OsKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOsKindFromValue(v string) (*OsKind, error) {
	ev := OsKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OsKind: valid values are %v", v, AllowedOsKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OsKind) IsValid() bool {
	for _, existing := range AllowedOsKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OsKind value
func (v OsKind) Ptr() *OsKind {
	return &v
}

type NullableOsKind struct {
	value *OsKind
	isSet bool
}

func (v NullableOsKind) Get() *OsKind {
	return v.value
}

func (v *NullableOsKind) Set(val *OsKind) {
	v.value = val
	v.isSet = true
}

func (v NullableOsKind) IsSet() bool {
	return v.isSet
}

func (v *NullableOsKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOsKind(val *OsKind) *NullableOsKind {
	return &NullableOsKind{value: val, isSet: true}
}

func (v NullableOsKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOsKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

