/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BridgeNetworkDriver } from './BridgeNetworkDriver';
import {
    BridgeNetworkDriverFromJSON,
    BridgeNetworkDriverFromJSONTyped,
    BridgeNetworkDriverToJSON,
    BridgeNetworkDriverToJSONTyped,
} from './BridgeNetworkDriver';
import type { BridgeNetworkAttachment } from './BridgeNetworkAttachment';
import {
    BridgeNetworkAttachmentFromJSON,
    BridgeNetworkAttachmentFromJSONTyped,
    BridgeNetworkAttachmentToJSON,
    BridgeNetworkAttachmentToJSONTyped,
} from './BridgeNetworkAttachment';

/**
 * Response body for `GET /api/v1/container-networks/{id_or_name}`.
 * @export
 * @interface BridgeNetworkDetails
 */
export interface BridgeNetworkDetails {
    /**
     * Creation timestamp (UTC, RFC 3339).
     * @type {Date}
     * @memberof BridgeNetworkDetails
     */
    createdAt: Date;
    /**
     * Driver backing the network (bridge vs. overlay).
     * @type {BridgeNetworkDriver}
     * @memberof BridgeNetworkDetails
     */
    driver?: BridgeNetworkDriver;
    /**
     * Opaque server-generated identifier (UUID v4).
     * @type {string}
     * @memberof BridgeNetworkDetails
     */
    id: string;
    /**
     * If true, containers attached to this network cannot reach the outside
     * world — only other containers on the same network.
     * @type {boolean}
     * @memberof BridgeNetworkDetails
     */
    internal?: boolean;
    /**
     * Arbitrary key/value labels for filtering and grouping.
     * @type {{ [key: string]: string; }}
     * @memberof BridgeNetworkDetails
     */
    labels?: { [key: string]: string; };
    /**
     * Human-readable, unique name (must match `^[a-z0-9][a-z0-9_-]{0,63}$`).
     * @type {string}
     * @memberof BridgeNetworkDetails
     */
    name: string;
    /**
     * IPv4/IPv6 subnet in CIDR notation (e.g. `"10.240.0.0/24"`).
     * @type {string}
     * @memberof BridgeNetworkDetails
     */
    subnet?: string | null;
    /**
     * Containers currently attached to the network.
     * @type {Array<BridgeNetworkAttachment>}
     * @memberof BridgeNetworkDetails
     */
    attachedContainers: Array<BridgeNetworkAttachment>;
}



/**
 * Check if a given object implements the BridgeNetworkDetails interface.
 */
export function instanceOfBridgeNetworkDetails(value: object): value is BridgeNetworkDetails {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('attachedContainers' in value) || value['attachedContainers'] === undefined) return false;
    return true;
}

export function BridgeNetworkDetailsFromJSON(json: any): BridgeNetworkDetails {
    return BridgeNetworkDetailsFromJSONTyped(json, false);
}

export function BridgeNetworkDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BridgeNetworkDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'driver': json['driver'] == null ? undefined : BridgeNetworkDriverFromJSON(json['driver']),
        'id': json['id'],
        'internal': json['internal'] == null ? undefined : json['internal'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'name': json['name'],
        'subnet': json['subnet'] == null ? undefined : json['subnet'],
        'attachedContainers': ((json['attached_containers'] as Array<any>).map(BridgeNetworkAttachmentFromJSON)),
    };
}

export function BridgeNetworkDetailsToJSON(json: any): BridgeNetworkDetails {
    return BridgeNetworkDetailsToJSONTyped(json, false);
}

export function BridgeNetworkDetailsToJSONTyped(value?: BridgeNetworkDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'driver': BridgeNetworkDriverToJSON(value['driver']),
        'id': value['id'],
        'internal': value['internal'],
        'labels': value['labels'],
        'name': value['name'],
        'subnet': value['subnet'],
        'attached_containers': ((value['attachedContainers'] as Array<any>).map(BridgeNetworkAttachmentToJSON)),
    };
}

