/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Build request for JSON API
 * @export
 * @interface BuildRequest
 */
export interface BuildRequest {
    /**
     * Build arguments (ARG values)
     * @type {{ [key: string]: string; }}
     * @memberof BuildRequest
     */
    buildArgs?: { [key: string]: string; };
    /**
     * Disable cache
     * @type {boolean}
     * @memberof BuildRequest
     */
    noCache?: boolean;
    /**
     * Push to registry after build
     * @type {boolean}
     * @memberof BuildRequest
     */
    push?: boolean;
    /**
     * Use runtime template instead of Dockerfile
     * @type {string}
     * @memberof BuildRequest
     */
    runtime?: string | null;
    /**
     * Tags to apply to the image
     * @type {Array<string>}
     * @memberof BuildRequest
     */
    tags?: Array<string>;
    /**
     * Target stage for multi-stage builds
     * @type {string}
     * @memberof BuildRequest
     */
    target?: string | null;
}

/**
 * Check if a given object implements the BuildRequest interface.
 */
export function instanceOfBuildRequest(value: object): value is BuildRequest {
    return true;
}

export function BuildRequestFromJSON(json: any): BuildRequest {
    return BuildRequestFromJSONTyped(json, false);
}

export function BuildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'buildArgs': json['build_args'] == null ? undefined : json['build_args'],
        'noCache': json['no_cache'] == null ? undefined : json['no_cache'],
        'push': json['push'] == null ? undefined : json['push'],
        'runtime': json['runtime'] == null ? undefined : json['runtime'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function BuildRequestToJSON(json: any): BuildRequest {
    return BuildRequestToJSONTyped(json, false);
}

export function BuildRequestToJSONTyped(value?: BuildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_args': value['buildArgs'],
        'no_cache': value['noCache'],
        'push': value['push'],
        'runtime': value['runtime'],
        'tags': value['tags'],
        'target': value['target'],
    };
}

