/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Container resource statistics
 * @export
 * @interface ContainerStatsResponse
 */
export interface ContainerStatsResponse {
    /**
     * CPU usage in microseconds
     * @type {number}
     * @memberof ContainerStatsResponse
     */
    cpuUsageUsec: number;
    /**
     * Container identifier
     * @type {string}
     * @memberof ContainerStatsResponse
     */
    id: string;
    /**
     * Current memory usage in bytes
     * @type {number}
     * @memberof ContainerStatsResponse
     */
    memoryBytes: number;
    /**
     * Memory limit in bytes (`u64::MAX` if unlimited)
     * @type {number}
     * @memberof ContainerStatsResponse
     */
    memoryLimit: number;
    /**
     * Memory usage as percentage of limit
     * @type {number}
     * @memberof ContainerStatsResponse
     */
    memoryPercent: number;
}

/**
 * Check if a given object implements the ContainerStatsResponse interface.
 */
export function instanceOfContainerStatsResponse(value: object): value is ContainerStatsResponse {
    if (!('cpuUsageUsec' in value) || value['cpuUsageUsec'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memoryBytes' in value) || value['memoryBytes'] === undefined) return false;
    if (!('memoryLimit' in value) || value['memoryLimit'] === undefined) return false;
    if (!('memoryPercent' in value) || value['memoryPercent'] === undefined) return false;
    return true;
}

export function ContainerStatsResponseFromJSON(json: any): ContainerStatsResponse {
    return ContainerStatsResponseFromJSONTyped(json, false);
}

export function ContainerStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cpuUsageUsec': json['cpu_usage_usec'],
        'id': json['id'],
        'memoryBytes': json['memory_bytes'],
        'memoryLimit': json['memory_limit'],
        'memoryPercent': json['memory_percent'],
    };
}

export function ContainerStatsResponseToJSON(json: any): ContainerStatsResponse {
    return ContainerStatsResponseToJSONTyped(json, false);
}

export function ContainerStatsResponseToJSONTyped(value?: ContainerStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_usage_usec': value['cpuUsageUsec'],
        'id': value['id'],
        'memory_bytes': value['memoryBytes'],
        'memory_limit': value['memoryLimit'],
        'memory_percent': value['memoryPercent'],
    };
}

