/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/environments`.
 * @export
 * @interface CreateEnvironmentRequest
 */
export interface CreateEnvironmentRequest {
    /**
     * Free-form description shown in the UI.
     * @type {string}
     * @memberof CreateEnvironmentRequest
     */
    description?: string | null;
    /**
     * Display name. Must be unique within the chosen `project_id` namespace.
     * @type {string}
     * @memberof CreateEnvironmentRequest
     */
    name: string;
    /**
     * Owning project id. `None` = global environment.
     * @type {string}
     * @memberof CreateEnvironmentRequest
     */
    projectId?: string | null;
}

/**
 * Check if a given object implements the CreateEnvironmentRequest interface.
 */
export function instanceOfCreateEnvironmentRequest(value: object): value is CreateEnvironmentRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateEnvironmentRequestFromJSON(json: any): CreateEnvironmentRequest {
    return CreateEnvironmentRequestFromJSONTyped(json, false);
}

export function CreateEnvironmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEnvironmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
    };
}

export function CreateEnvironmentRequestToJSON(json: any): CreateEnvironmentRequest {
    return CreateEnvironmentRequestToJSONTyped(json, false);
}

export function CreateEnvironmentRequestToJSONTyped(value?: CreateEnvironmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'project_id': value['projectId'],
    };
}

