/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStep } from './WorkflowStep';
import {
    WorkflowStepFromJSON,
    WorkflowStepFromJSONTyped,
    WorkflowStepToJSON,
    WorkflowStepToJSONTyped,
} from './WorkflowStep';

/**
 * Body for `POST /api/v1/workflows`.
 * @export
 * @interface CreateWorkflowRequest
 */
export interface CreateWorkflowRequest {
    /**
     * Workflow name.
     * @type {string}
     * @memberof CreateWorkflowRequest
     */
    name: string;
    /**
     * Optional project scope.
     * @type {string}
     * @memberof CreateWorkflowRequest
     */
    projectId?: string | null;
    /**
     * Ordered list of steps.
     * @type {Array<WorkflowStep>}
     * @memberof CreateWorkflowRequest
     */
    steps: Array<WorkflowStep>;
}

/**
 * Check if a given object implements the CreateWorkflowRequest interface.
 */
export function instanceOfCreateWorkflowRequest(value: object): value is CreateWorkflowRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function CreateWorkflowRequestFromJSON(json: any): CreateWorkflowRequest {
    return CreateWorkflowRequestFromJSONTyped(json, false);
}

export function CreateWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'steps': ((json['steps'] as Array<any>).map(WorkflowStepFromJSON)),
    };
}

export function CreateWorkflowRequestToJSON(json: any): CreateWorkflowRequest {
    return CreateWorkflowRequestToJSONTyped(json, false);
}

export function CreateWorkflowRequestToJSONTyped(value?: CreateWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'project_id': value['projectId'],
        'steps': ((value['steps'] as Array<any>).map(WorkflowStepToJSON)),
    };
}

