/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for force-leader operation.
 * @export
 * @interface ForceLeaderResponse
 */
export interface ForceLeaderResponse {
    /**
     * 
     * @type {string}
     * @memberof ForceLeaderResponse
     */
    message: string;
    /**
     * Number of cluster nodes whose state was preserved
     * @type {number}
     * @memberof ForceLeaderResponse
     */
    preservedNodes: number;
    /**
     * Number of services whose state was preserved
     * @type {number}
     * @memberof ForceLeaderResponse
     */
    preservedServices: number;
    /**
     * 
     * @type {boolean}
     * @memberof ForceLeaderResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the ForceLeaderResponse interface.
 */
export function instanceOfForceLeaderResponse(value: object): value is ForceLeaderResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('preservedNodes' in value) || value['preservedNodes'] === undefined) return false;
    if (!('preservedServices' in value) || value['preservedServices'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ForceLeaderResponseFromJSON(json: any): ForceLeaderResponse {
    return ForceLeaderResponseFromJSONTyped(json, false);
}

export function ForceLeaderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceLeaderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'preservedNodes': json['preserved_nodes'],
        'preservedServices': json['preserved_services'],
        'success': json['success'],
    };
}

export function ForceLeaderResponseToJSON(json: any): ForceLeaderResponse {
    return ForceLeaderResponseToJSONTyped(json, false);
}

export function ForceLeaderResponseToJSONTyped(value?: ForceLeaderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'preserved_nodes': value['preservedNodes'],
        'preserved_services': value['preservedServices'],
        'success': value['success'],
    };
}

