/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-GPU utilization snapshot reported in node heartbeats
 * @export
 * @interface GpuUtilizationReport
 */
export interface GpuUtilizationReport {
    /**
     * GPU index on this node
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    index: number;
    /**
     * GPU total memory in MB
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    memoryTotalMb: number;
    /**
     * GPU memory currently used in MB
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    memoryUsedMb: number;
    /**
     * GPU power draw in Watts
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    powerDrawW?: number | null;
    /**
     * GPU temperature in Celsius
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    temperatureC?: number | null;
    /**
     * GPU compute utilization percentage (0-100)
     * @type {number}
     * @memberof GpuUtilizationReport
     */
    utilizationPercent: number;
}

/**
 * Check if a given object implements the GpuUtilizationReport interface.
 */
export function instanceOfGpuUtilizationReport(value: object): value is GpuUtilizationReport {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('memoryTotalMb' in value) || value['memoryTotalMb'] === undefined) return false;
    if (!('memoryUsedMb' in value) || value['memoryUsedMb'] === undefined) return false;
    if (!('utilizationPercent' in value) || value['utilizationPercent'] === undefined) return false;
    return true;
}

export function GpuUtilizationReportFromJSON(json: any): GpuUtilizationReport {
    return GpuUtilizationReportFromJSONTyped(json, false);
}

export function GpuUtilizationReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuUtilizationReport {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'memoryTotalMb': json['memory_total_mb'],
        'memoryUsedMb': json['memory_used_mb'],
        'powerDrawW': json['power_draw_w'] == null ? undefined : json['power_draw_w'],
        'temperatureC': json['temperature_c'] == null ? undefined : json['temperature_c'],
        'utilizationPercent': json['utilization_percent'],
    };
}

export function GpuUtilizationReportToJSON(json: any): GpuUtilizationReport {
    return GpuUtilizationReportToJSONTyped(json, false);
}

export function GpuUtilizationReportToJSONTyped(value?: GpuUtilizationReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'memory_total_mb': value['memoryTotalMb'],
        'memory_used_mb': value['memoryUsedMb'],
        'power_draw_w': value['powerDrawW'],
        'temperature_c': value['temperatureC'],
        'utilization_percent': value['utilizationPercent'],
    };
}

