/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for `POST /api/v1/projects/{id}/deployments`.
 * @export
 * @interface LinkDeploymentRequest
 */
export interface LinkDeploymentRequest {
    /**
     * Name of the deployment to link.
     * @type {string}
     * @memberof LinkDeploymentRequest
     */
    deploymentName: string;
}

/**
 * Check if a given object implements the LinkDeploymentRequest interface.
 */
export function instanceOfLinkDeploymentRequest(value: object): value is LinkDeploymentRequest {
    if (!('deploymentName' in value) || value['deploymentName'] === undefined) return false;
    return true;
}

export function LinkDeploymentRequestFromJSON(json: any): LinkDeploymentRequest {
    return LinkDeploymentRequestFromJSONTyped(json, false);
}

export function LinkDeploymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDeploymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deploymentName': json['deployment_name'],
    };
}

export function LinkDeploymentRequestToJSON(json: any): LinkDeploymentRequest {
    return LinkDeploymentRequestToJSONTyped(json, false);
}

export function LinkDeploymentRequestToJSONTyped(value?: LinkDeploymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deployment_name': value['deploymentName'],
    };
}

