/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary returned when listing networks.
 * @export
 * @interface NetworkSummary
 */
export interface NetworkSummary {
    /**
     * 
     * @type {number}
     * @memberof NetworkSummary
     */
    cidrCount: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkSummary
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NetworkSummary
     */
    memberCount: number;
    /**
     * 
     * @type {string}
     * @memberof NetworkSummary
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NetworkSummary
     */
    ruleCount: number;
}

/**
 * Check if a given object implements the NetworkSummary interface.
 */
export function instanceOfNetworkSummary(value: object): value is NetworkSummary {
    if (!('cidrCount' in value) || value['cidrCount'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ruleCount' in value) || value['ruleCount'] === undefined) return false;
    return true;
}

export function NetworkSummaryFromJSON(json: any): NetworkSummary {
    return NetworkSummaryFromJSONTyped(json, false);
}

export function NetworkSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'cidrCount': json['cidr_count'],
        'description': json['description'] == null ? undefined : json['description'],
        'memberCount': json['member_count'],
        'name': json['name'],
        'ruleCount': json['rule_count'],
    };
}

export function NetworkSummaryToJSON(json: any): NetworkSummary {
    return NetworkSummaryToJSONTyped(json, false);
}

export function NetworkSummaryToJSONTyped(value?: NetworkSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cidr_count': value['cidrCount'],
        'description': value['description'],
        'member_count': value['memberCount'],
        'name': value['name'],
        'rule_count': value['ruleCount'],
    };
}

