/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generic HTTP webhook configuration.
 * @export
 * @interface NotifierConfigOneOf2
 */
export interface NotifierConfigOneOf2 {
    /**
     * Extra headers to send with the request.
     * @type {{ [key: string]: string; }}
     * @memberof NotifierConfigOneOf2
     */
    headers?: { [key: string]: string; };
    /**
     * HTTP method (defaults to `"POST"`).
     * @type {string}
     * @memberof NotifierConfigOneOf2
     */
    method?: string | null;
    /**
     * 
     * @type {NotifierConfigOneOf2TypeEnum}
     * @memberof NotifierConfigOneOf2
     */
    type: NotifierConfigOneOf2TypeEnum;
    /**
     * Target URL.
     * @type {string}
     * @memberof NotifierConfigOneOf2
     */
    url: string;
}


/**
 * @export
 */
export const NotifierConfigOneOf2TypeEnum = {
    Webhook: 'webhook'
} as const;
export type NotifierConfigOneOf2TypeEnum = typeof NotifierConfigOneOf2TypeEnum[keyof typeof NotifierConfigOneOf2TypeEnum];


/**
 * Check if a given object implements the NotifierConfigOneOf2 interface.
 */
export function instanceOfNotifierConfigOneOf2(value: object): value is NotifierConfigOneOf2 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NotifierConfigOneOf2FromJSON(json: any): NotifierConfigOneOf2 {
    return NotifierConfigOneOf2FromJSONTyped(json, false);
}

export function NotifierConfigOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NotifierConfigOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'] == null ? undefined : json['headers'],
        'method': json['method'] == null ? undefined : json['method'],
        'type': json['type'],
        'url': json['url'],
    };
}

export function NotifierConfigOneOf2ToJSON(json: any): NotifierConfigOneOf2 {
    return NotifierConfigOneOf2ToJSONTyped(json, false);
}

export function NotifierConfigOneOf2ToJSONTyped(value?: NotifierConfigOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
        'method': value['method'],
        'type': value['type'],
        'url': value['url'],
    };
}

