/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserView } from './UserView';
import {
    UserViewFromJSON,
    UserViewFromJSONTyped,
    UserViewToJSON,
    UserViewToJSONTyped,
} from './UserView';

/**
 * Callback response body (returned as JSON unless the operator prefers a
 * redirect; initial integration keeps JSON so the Manager UI can show a
 * welcome screen post-exchange).
 * @export
 * @interface OidcCallbackResponse
 */
export interface OidcCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof OidcCallbackResponse
     */
    csrfToken: string;
    /**
     * 
     * @type {string}
     * @memberof OidcCallbackResponse
     */
    provider: string;
    /**
     * 
     * @type {UserView}
     * @memberof OidcCallbackResponse
     */
    user: UserView;
}

/**
 * Check if a given object implements the OidcCallbackResponse interface.
 */
export function instanceOfOidcCallbackResponse(value: object): value is OidcCallbackResponse {
    if (!('csrfToken' in value) || value['csrfToken'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function OidcCallbackResponseFromJSON(json: any): OidcCallbackResponse {
    return OidcCallbackResponseFromJSONTyped(json, false);
}

export function OidcCallbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OidcCallbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'csrfToken': json['csrf_token'],
        'provider': json['provider'],
        'user': UserViewFromJSON(json['user']),
    };
}

export function OidcCallbackResponseToJSON(json: any): OidcCallbackResponse {
    return OidcCallbackResponseToJSONTyped(json, false);
}

export function OidcCallbackResponseToJSONTyped(value?: OidcCallbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csrf_token': value['csrfToken'],
        'provider': value['provider'],
        'user': UserViewToJSON(value['user']),
    };
}

