/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Access level for a resource permission, ordered from least to most
 * privilege.
 * @export
 */
export const PermissionLevel = {
    None: 'none',
    Read: 'read',
    Execute: 'execute',
    Write: 'write'
} as const;
export type PermissionLevel = typeof PermissionLevel[keyof typeof PermissionLevel];


export function instanceOfPermissionLevel(value: any): boolean {
    for (const key in PermissionLevel) {
        if (Object.prototype.hasOwnProperty.call(PermissionLevel, key)) {
            if (PermissionLevel[key as keyof typeof PermissionLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PermissionLevelFromJSON(json: any): PermissionLevel {
    return PermissionLevelFromJSONTyped(json, false);
}

export function PermissionLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionLevel {
    return json as PermissionLevel;
}

export function PermissionLevelToJSON(value?: PermissionLevel | null): any {
    return value as any;
}

export function PermissionLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): PermissionLevel {
    return value as PermissionLevel;
}

