/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializable wrapper for [`PruneResult`].
 * @export
 * @interface PruneResultDto
 */
export interface PruneResultDto {
    /**
     * Image references or digests that were removed.
     * @type {Array<string>}
     * @memberof PruneResultDto
     */
    deleted: Array<string>;
    /**
     * Bytes reclaimed from the cache.
     * @type {number}
     * @memberof PruneResultDto
     */
    spaceReclaimed: number;
}

/**
 * Check if a given object implements the PruneResultDto interface.
 */
export function instanceOfPruneResultDto(value: object): value is PruneResultDto {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('spaceReclaimed' in value) || value['spaceReclaimed'] === undefined) return false;
    return true;
}

export function PruneResultDtoFromJSON(json: any): PruneResultDto {
    return PruneResultDtoFromJSONTyped(json, false);
}

export function PruneResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PruneResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
        'spaceReclaimed': json['space_reclaimed'],
    };
}

export function PruneResultDtoToJSON(json: any): PruneResultDto {
    return PruneResultDtoToJSONTyped(json, false);
}

export function PruneResultDtoToJSONTyped(value?: PruneResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
        'space_reclaimed': value['spaceReclaimed'],
    };
}

