/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for [`pull_image_handler`]. Blocking pull of an OCI image.
 * @export
 * @interface PullImageRequest
 */
export interface PullImageRequest {
    /**
     * Pull policy override. Accepts `"always"`, `"if_not_present"`, or
     * `"never"`. Defaults to `"always"` when omitted.
     * @type {string}
     * @memberof PullImageRequest
     */
    pullPolicy?: string | null;
    /**
     * OCI image reference to pull, e.g. `docker.io/library/nginx:latest`.
     * @type {string}
     * @memberof PullImageRequest
     */
    reference: string;
}

/**
 * Check if a given object implements the PullImageRequest interface.
 */
export function instanceOfPullImageRequest(value: object): value is PullImageRequest {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function PullImageRequestFromJSON(json: any): PullImageRequest {
    return PullImageRequestFromJSONTyped(json, false);
}

export function PullImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pullPolicy': json['pull_policy'] == null ? undefined : json['pull_policy'],
        'reference': json['reference'],
    };
}

export function PullImageRequestToJSON(json: any): PullImageRequest {
    return PullImageRequestToJSONTyped(json, false);
}

export function PullImageRequestToJSONTyped(value?: PullImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pull_policy': value['pullPolicy'],
        'reference': value['reference'],
    };
}

