/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response returned by the rotate endpoint.
 * @export
 * @interface RotateSecretResponse
 */
export interface RotateSecretResponse {
    /**
     * The secret name.
     * @type {string}
     * @memberof RotateSecretResponse
     */
    name: string;
    /**
     * Version after rotation.
     * @type {number}
     * @memberof RotateSecretResponse
     */
    newVersion: number;
    /**
     * Version prior to rotation. `None` if the secret did not exist (won't
     * happen today — rotate rejects missing secrets — but preserved for
     * forward compatibility).
     * @type {number}
     * @memberof RotateSecretResponse
     */
    previousVersion?: number | null;
}

/**
 * Check if a given object implements the RotateSecretResponse interface.
 */
export function instanceOfRotateSecretResponse(value: object): value is RotateSecretResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('newVersion' in value) || value['newVersion'] === undefined) return false;
    return true;
}

export function RotateSecretResponseFromJSON(json: any): RotateSecretResponse {
    return RotateSecretResponseFromJSONTyped(json, false);
}

export function RotateSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'newVersion': json['new_version'],
        'previousVersion': json['previous_version'] == null ? undefined : json['previous_version'],
    };
}

export function RotateSecretResponseToJSON(json: any): RotateSecretResponse {
    return RotateSecretResponseToJSONTyped(json, false);
}

export function RotateSecretResponseToJSONTyped(value?: RotateSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'new_version': value['newVersion'],
        'previous_version': value['previousVersion'],
    };
}

