/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StreamInfo } from './StreamInfo';
import {
    StreamInfoFromJSON,
    StreamInfoFromJSONTyped,
    StreamInfoToJSON,
    StreamInfoToJSONTyped,
} from './StreamInfo';

/**
 * Response for `GET /api/v1/proxy/streams`.
 * @export
 * @interface StreamsResponse
 */
export interface StreamsResponse {
    /**
     * Stream details.
     * @type {Array<StreamInfo>}
     * @memberof StreamsResponse
     */
    streams: Array<StreamInfo>;
    /**
     * TCP stream count.
     * @type {number}
     * @memberof StreamsResponse
     */
    tcpCount: number;
    /**
     * Total number of stream proxies.
     * @type {number}
     * @memberof StreamsResponse
     */
    total: number;
    /**
     * UDP stream count.
     * @type {number}
     * @memberof StreamsResponse
     */
    udpCount: number;
}

/**
 * Check if a given object implements the StreamsResponse interface.
 */
export function instanceOfStreamsResponse(value: object): value is StreamsResponse {
    if (!('streams' in value) || value['streams'] === undefined) return false;
    if (!('tcpCount' in value) || value['tcpCount'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('udpCount' in value) || value['udpCount'] === undefined) return false;
    return true;
}

export function StreamsResponseFromJSON(json: any): StreamsResponse {
    return StreamsResponseFromJSONTyped(json, false);
}

export function StreamsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'streams': ((json['streams'] as Array<any>).map(StreamInfoFromJSON)),
        'tcpCount': json['tcp_count'],
        'total': json['total'],
        'udpCount': json['udp_count'],
    };
}

export function StreamsResponseToJSON(json: any): StreamsResponse {
    return StreamsResponseToJSONTyped(json, false);
}

export function StreamsResponseToJSONTyped(value?: StreamsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'streams': ((value['streams'] as Array<any>).map(StreamInfoToJSON)),
        'tcp_count': value['tcpCount'],
        'total': value['total'],
        'udp_count': value['udpCount'],
    };
}

