/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncResourceResponse } from './SyncResourceResponse';
import {
    SyncResourceResponseFromJSON,
    SyncResourceResponseFromJSONTyped,
    SyncResourceResponseToJSON,
    SyncResourceResponseToJSONTyped,
} from './SyncResourceResponse';

/**
 * JSON-friendly wrapper around [`SyncDiff`].
 * @export
 * @interface SyncDiffResponse
 */
export interface SyncDiffResponse {
    /**
     * Resources to create.
     * @type {Array<SyncResourceResponse>}
     * @memberof SyncDiffResponse
     */
    toCreate: Array<SyncResourceResponse>;
    /**
     * Resource names to delete.
     * @type {Array<string>}
     * @memberof SyncDiffResponse
     */
    toDelete: Array<string>;
    /**
     * Resources to update.
     * @type {Array<SyncResourceResponse>}
     * @memberof SyncDiffResponse
     */
    toUpdate: Array<SyncResourceResponse>;
}

/**
 * Check if a given object implements the SyncDiffResponse interface.
 */
export function instanceOfSyncDiffResponse(value: object): value is SyncDiffResponse {
    if (!('toCreate' in value) || value['toCreate'] === undefined) return false;
    if (!('toDelete' in value) || value['toDelete'] === undefined) return false;
    if (!('toUpdate' in value) || value['toUpdate'] === undefined) return false;
    return true;
}

export function SyncDiffResponseFromJSON(json: any): SyncDiffResponse {
    return SyncDiffResponseFromJSONTyped(json, false);
}

export function SyncDiffResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncDiffResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'toCreate': ((json['to_create'] as Array<any>).map(SyncResourceResponseFromJSON)),
        'toDelete': json['to_delete'],
        'toUpdate': ((json['to_update'] as Array<any>).map(SyncResourceResponseFromJSON)),
    };
}

export function SyncDiffResponseToJSON(json: any): SyncDiffResponse {
    return SyncDiffResponseToJSONTyped(json, false);
}

export function SyncDiffResponseToJSONTyped(value?: SyncDiffResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to_create': ((value['toCreate'] as Array<any>).map(SyncResourceResponseToJSON)),
        'to_delete': value['toDelete'],
        'to_update': ((value['toUpdate'] as Array<any>).map(SyncResourceResponseToJSON)),
    };
}

