/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A recorded execution of a task.
 * @export
 * @interface TaskRun
 */
export interface TaskRun {
    /**
     * Process exit code (`None` if the task could not be started).
     * @type {number}
     * @memberof TaskRun
     */
    exitCode?: number | null;
    /**
     * When the run finished (`None` if it has not finished yet).
     * @type {string}
     * @memberof TaskRun
     */
    finishedAt?: string | null;
    /**
     * UUID identifier of this run.
     * @type {string}
     * @memberof TaskRun
     */
    id: string;
    /**
     * When the run started.
     * @type {string}
     * @memberof TaskRun
     */
    startedAt: string;
    /**
     * Captured standard error.
     * @type {string}
     * @memberof TaskRun
     */
    stderr: string;
    /**
     * Captured standard output.
     * @type {string}
     * @memberof TaskRun
     */
    stdout: string;
    /**
     * The task that was executed.
     * @type {string}
     * @memberof TaskRun
     */
    taskId: string;
}

/**
 * Check if a given object implements the TaskRun interface.
 */
export function instanceOfTaskRun(value: object): value is TaskRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('stderr' in value) || value['stderr'] === undefined) return false;
    if (!('stdout' in value) || value['stdout'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    return true;
}

export function TaskRunFromJSON(json: any): TaskRun {
    return TaskRunFromJSONTyped(json, false);
}

export function TaskRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskRun {
    if (json == null) {
        return json;
    }
    return {
        
        'exitCode': json['exit_code'] == null ? undefined : json['exit_code'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'id': json['id'],
        'startedAt': json['started_at'],
        'stderr': json['stderr'],
        'stdout': json['stdout'],
        'taskId': json['task_id'],
    };
}

export function TaskRunToJSON(json: any): TaskRun {
    return TaskRunToJSONTyped(json, false);
}

export function TaskRunToJSONTyped(value?: TaskRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exit_code': value['exitCode'],
        'finished_at': value['finishedAt'],
        'id': value['id'],
        'started_at': value['startedAt'],
        'stderr': value['stderr'],
        'stdout': value['stdout'],
        'task_id': value['taskId'],
    };
}

