/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotifierConfig } from './NotifierConfig';
import {
    NotifierConfigFromJSON,
    NotifierConfigFromJSONTyped,
    NotifierConfigToJSON,
    NotifierConfigToJSONTyped,
} from './NotifierConfig';

/**
 * Body for `PATCH /api/v1/notifiers/{id}`.
 * @export
 * @interface UpdateNotifierRequest
 */
export interface UpdateNotifierRequest {
    /**
     * Updated configuration.
     * @type {NotifierConfig}
     * @memberof UpdateNotifierRequest
     */
    config?: NotifierConfig | null;
    /**
     * Updated enabled flag.
     * @type {boolean}
     * @memberof UpdateNotifierRequest
     */
    enabled?: boolean | null;
    /**
     * Updated name.
     * @type {string}
     * @memberof UpdateNotifierRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the UpdateNotifierRequest interface.
 */
export function instanceOfUpdateNotifierRequest(value: object): value is UpdateNotifierRequest {
    return true;
}

export function UpdateNotifierRequestFromJSON(json: any): UpdateNotifierRequest {
    return UpdateNotifierRequestFromJSONTyped(json, false);
}

export function UpdateNotifierRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotifierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : NotifierConfigFromJSON(json['config']),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateNotifierRequestToJSON(json: any): UpdateNotifierRequest {
    return UpdateNotifierRequestToJSONTyped(json, false);
}

export function UpdateNotifierRequestToJSONTyped(value?: UpdateNotifierRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': NotifierConfigToJSON(value['config']),
        'enabled': value['enabled'],
        'name': value['name'],
    };
}

