/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for the public webhook receiver.
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * HEAD commit SHA after the pull.
     * @type {string}
     * @memberof WebhookResponse
     */
    sha: string;
    /**
     * Operation result -- always `"ok"` on success.
     * @type {string}
     * @memberof WebhookResponse
     */
    status: string;
}

/**
 * Check if a given object implements the WebhookResponse interface.
 */
export function instanceOfWebhookResponse(value: object): value is WebhookResponse {
    if (!('sha' in value) || value['sha'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WebhookResponseFromJSON(json: any): WebhookResponse {
    return WebhookResponseFromJSONTyped(json, false);
}

export function WebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sha': json['sha'],
        'status': json['status'],
    };
}

export function WebhookResponseToJSON(json: any): WebhookResponse {
    return WebhookResponseToJSONTyped(json, false);
}

export function WebhookResponseToJSONTyped(value?: WebhookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sha': value['sha'],
        'status': value['status'],
    };
}

