/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Apply a sync resource by id.
 * @export
 * @interface WorkflowActionOneOf3
 */
export interface WorkflowActionOneOf3 {
    /**
     * The sync id to apply.
     * @type {string}
     * @memberof WorkflowActionOneOf3
     */
    syncId: string;
    /**
     * 
     * @type {WorkflowActionOneOf3TypeEnum}
     * @memberof WorkflowActionOneOf3
     */
    type: WorkflowActionOneOf3TypeEnum;
}


/**
 * @export
 */
export const WorkflowActionOneOf3TypeEnum = {
    ApplySync: 'apply_sync'
} as const;
export type WorkflowActionOneOf3TypeEnum = typeof WorkflowActionOneOf3TypeEnum[keyof typeof WorkflowActionOneOf3TypeEnum];


/**
 * Check if a given object implements the WorkflowActionOneOf3 interface.
 */
export function instanceOfWorkflowActionOneOf3(value: object): value is WorkflowActionOneOf3 {
    if (!('syncId' in value) || value['syncId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WorkflowActionOneOf3FromJSON(json: any): WorkflowActionOneOf3 {
    return WorkflowActionOneOf3FromJSONTyped(json, false);
}

export function WorkflowActionOneOf3FromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowActionOneOf3 {
    if (json == null) {
        return json;
    }
    return {
        
        'syncId': json['sync_id'],
        'type': json['type'],
    };
}

export function WorkflowActionOneOf3ToJSON(json: any): WorkflowActionOneOf3 {
    return WorkflowActionOneOf3ToJSONTyped(json, false);
}

export function WorkflowActionOneOf3ToJSONTyped(value?: WorkflowActionOneOf3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sync_id': value['syncId'],
        'type': value['type'],
    };
}

