version: v1
deployment: my-simple-app

services:
  web:
    rtype: service
    image:
      name: nginx:alpine
      pull_policy: if_not_present

    endpoints:
      - name: http
        protocol: http
        port: 80
        expose: public

    scale:
      mode: fixed
      replicas: 2
