/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDeploymentRequest,
  DeploymentDetails,
  DeploymentSummary,
} from '../models/index';
import {
    CreateDeploymentRequestFromJSON,
    CreateDeploymentRequestToJSON,
    DeploymentDetailsFromJSON,
    DeploymentDetailsToJSON,
    DeploymentSummaryFromJSON,
    DeploymentSummaryToJSON,
} from '../models/index';

export interface CreateDeploymentOperationRequest {
    createDeploymentRequest: CreateDeploymentRequest;
}

export interface DeleteDeploymentRequest {
    name: string;
}

export interface GetDeploymentRequest {
    name: string;
}

/**
 * 
 */
export class DeploymentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDeployment without sending the request
     */
    async createDeploymentRequestOpts(requestParameters: CreateDeploymentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createDeploymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createDeploymentRequest',
                'Required parameter "createDeploymentRequest" was null or undefined when calling createDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deployments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDeploymentRequestToJSON(requestParameters['createDeploymentRequest']),
        };
    }

    /**
     * When the daemon has orchestration wired (service manager, proxy, overlay), this handler:  1. Parses and validates the spec YAML  2. Stores the deployment with status `Deploying`  3. Spawns an async task that registers services, sets up overlays,     configures the proxy, and scales services  4. Returns immediately with `Deploying` status  5. The async task updates the stored status to `Running` or `Failed`  Without orchestration wired, it stores the spec with `Pending` status.  # Errors  Returns an error if the spec is invalid or storage fails.
     * Create a new deployment.
     */
    async createDeploymentRaw(requestParameters: CreateDeploymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentDetails>> {
        const requestOptions = await this.createDeploymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentDetailsFromJSON(jsonValue));
    }

    /**
     * When the daemon has orchestration wired (service manager, proxy, overlay), this handler:  1. Parses and validates the spec YAML  2. Stores the deployment with status `Deploying`  3. Spawns an async task that registers services, sets up overlays,     configures the proxy, and scales services  4. Returns immediately with `Deploying` status  5. The async task updates the stored status to `Running` or `Failed`  Without orchestration wired, it stores the spec with `Pending` status.  # Errors  Returns an error if the spec is invalid or storage fails.
     * Create a new deployment.
     */
    async createDeployment(requestParameters: CreateDeploymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentDetails> {
        const response = await this.createDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDeployment without sending the request
     */
    async deleteDeploymentRequestOpts(requestParameters: DeleteDeploymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deployments/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns an error if the deployment is not found, storage access fails, or teardown encounters critical failures.
     * Delete a deployment.
     */
    async deleteDeploymentRaw(requestParameters: DeleteDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDeploymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * # Errors  Returns an error if the deployment is not found, storage access fails, or teardown encounters critical failures.
     * Delete a deployment.
     */
    async deleteDeployment(requestParameters: DeleteDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDeploymentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getDeployment without sending the request
     */
    async getDeploymentRequestOpts(requestParameters: GetDeploymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getDeployment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deployments/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns an error if the deployment is not found or storage access fails.
     * Get deployment details (with live per-service health when available).
     */
    async getDeploymentRaw(requestParameters: GetDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentDetails>> {
        const requestOptions = await this.getDeploymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentDetailsFromJSON(jsonValue));
    }

    /**
     * # Errors  Returns an error if the deployment is not found or storage access fails.
     * Get deployment details (with live per-service health when available).
     */
    async getDeployment(requestParameters: GetDeploymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentDetails> {
        const response = await this.getDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDeployments without sending the request
     */
    async listDeploymentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/deployments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns an error if storage access fails.
     * List all deployments.
     */
    async listDeploymentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeploymentSummary>>> {
        const requestOptions = await this.listDeploymentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeploymentSummaryFromJSON));
    }

    /**
     * # Errors  Returns an error if storage access fails.
     * List all deployments.
     */
    async listDeployments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeploymentSummary>> {
        const response = await this.listDeploymentsRaw(initOverrides);
        return await response.value();
    }

}
