/* tslint:disable */
/* eslint-disable */
/**
 * ZLayer API
 * Container orchestration API for ZLayer
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWorkflowRequest,
  StoredWorkflow,
  WorkflowRun,
} from '../models/index';
import {
    CreateWorkflowRequestFromJSON,
    CreateWorkflowRequestToJSON,
    StoredWorkflowFromJSON,
    StoredWorkflowToJSON,
    WorkflowRunFromJSON,
    WorkflowRunToJSON,
} from '../models/index';

export interface CreateWorkflowOperationRequest {
    createWorkflowRequest: CreateWorkflowRequest;
}

export interface DeleteWorkflowRequest {
    id: string;
}

export interface GetWorkflowRequest {
    id: string;
}

export interface ListWorkflowRunsRequest {
    id: string;
}

export interface RunWorkflowRequest {
    id: string;
}

/**
 * 
 */
export class WorkflowsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWorkflow without sending the request
     */
    async createWorkflowRequestOpts(requestParameters: CreateWorkflowOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWorkflowRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkflowRequest',
                'Required parameter "createWorkflowRequest" was null or undefined when calling createWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkflowRequestToJSON(requestParameters['createWorkflowRequest']),
        };
    }

    /**
     * # Errors  Returns [`ApiError::Forbidden`] when the caller is not an admin, [`ApiError::BadRequest`] for an empty name or empty steps list, or [`ApiError::Internal`] when the workflow store fails.
     * Create a new workflow. Admin only.
     */
    async createWorkflowRaw(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredWorkflow>> {
        const requestOptions = await this.createWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoredWorkflowFromJSON(jsonValue));
    }

    /**
     * # Errors  Returns [`ApiError::Forbidden`] when the caller is not an admin, [`ApiError::BadRequest`] for an empty name or empty steps list, or [`ApiError::Internal`] when the workflow store fails.
     * Create a new workflow. Admin only.
     */
    async createWorkflow(requestParameters: CreateWorkflowOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredWorkflow> {
        const response = await this.createWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWorkflow without sending the request
     */
    async deleteWorkflowRequestOpts(requestParameters: DeleteWorkflowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns [`ApiError::Forbidden`] for non-admins, [`ApiError::NotFound`] when the workflow does not exist, or [`ApiError::Internal`] when the store fails.
     * Delete a workflow. Admin only.
     */
    async deleteWorkflowRaw(requestParameters: DeleteWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * # Errors  Returns [`ApiError::Forbidden`] for non-admins, [`ApiError::NotFound`] when the workflow does not exist, or [`ApiError::Internal`] when the store fails.
     * Delete a workflow. Admin only.
     */
    async deleteWorkflow(requestParameters: DeleteWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkflowRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getWorkflow without sending the request
     */
    async getWorkflowRequestOpts(requestParameters: GetWorkflowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns [`ApiError::NotFound`] if no workflow with the given id exists, or [`ApiError::Internal`] when the store fails.
     * Fetch a single workflow by id.
     */
    async getWorkflowRaw(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoredWorkflow>> {
        const requestOptions = await this.getWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoredWorkflowFromJSON(jsonValue));
    }

    /**
     * # Errors  Returns [`ApiError::NotFound`] if no workflow with the given id exists, or [`ApiError::Internal`] when the store fails.
     * Fetch a single workflow by id.
     */
    async getWorkflow(requestParameters: GetWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoredWorkflow> {
        const response = await this.getWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWorkflowRuns without sending the request
     */
    async listWorkflowRunsRequestOpts(requestParameters: ListWorkflowRunsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listWorkflowRuns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows/{id}/runs`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns [`ApiError::NotFound`] if the workflow does not exist, or [`ApiError::Internal`] when the store fails.
     * List past runs for a workflow, most recent first.
     */
    async listWorkflowRunsRaw(requestParameters: ListWorkflowRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkflowRun>>> {
        const requestOptions = await this.listWorkflowRunsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkflowRunFromJSON));
    }

    /**
     * # Errors  Returns [`ApiError::NotFound`] if the workflow does not exist, or [`ApiError::Internal`] when the store fails.
     * List past runs for a workflow, most recent first.
     */
    async listWorkflowRuns(requestParameters: ListWorkflowRunsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkflowRun>> {
        const response = await this.listWorkflowRunsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWorkflows without sending the request
     */
    async listWorkflowsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * # Errors  Returns [`ApiError::Internal`] if the workflow store fails.
     * List workflows.
     */
    async listWorkflowsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StoredWorkflow>>> {
        const requestOptions = await this.listWorkflowsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StoredWorkflowFromJSON));
    }

    /**
     * # Errors  Returns [`ApiError::Internal`] if the workflow store fails.
     * List workflows.
     */
    async listWorkflows(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StoredWorkflow>> {
        const response = await this.listWorkflowsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runWorkflow without sending the request
     */
    async runWorkflowRequestOpts(requestParameters: RunWorkflowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling runWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/workflows/{id}/run`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iterates steps sequentially: - `RunTask` — looks up the task and executes its `body` via `sh -c`. - `BuildProject` — clones / fast-forwards the project\'s git repo, then   registers and awaits a real buildah build. - `DeployProject` — reads the project\'s `deploy_spec_path` from its   checked-out working copy, parses it as a `DeploymentSpec`, and upserts   it into the deployment store. - `ApplySync` — delegates to [`apply_sync_inner`] for the real reconcile.  If a step fails and has an `on_failure` handler, that handler runs before the workflow aborts. Subsequent steps are marked `\"skipped\"`.  # Errors  Returns [`ApiError::Forbidden`] for non-admins, [`ApiError::NotFound`] when the workflow does not exist, or [`ApiError::Internal`] when execution or recording fails.
     * Execute a workflow synchronously. Admin only.
     */
    async runWorkflowRaw(requestParameters: RunWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowRun>> {
        const requestOptions = await this.runWorkflowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowRunFromJSON(jsonValue));
    }

    /**
     * Iterates steps sequentially: - `RunTask` — looks up the task and executes its `body` via `sh -c`. - `BuildProject` — clones / fast-forwards the project\'s git repo, then   registers and awaits a real buildah build. - `DeployProject` — reads the project\'s `deploy_spec_path` from its   checked-out working copy, parses it as a `DeploymentSpec`, and upserts   it into the deployment store. - `ApplySync` — delegates to [`apply_sync_inner`] for the real reconcile.  If a step fails and has an `on_failure` handler, that handler runs before the workflow aborts. Subsequent steps are marked `\"skipped\"`.  # Errors  Returns [`ApiError::Forbidden`] for non-admins, [`ApiError::NotFound`] when the workflow does not exist, or [`ApiError::Internal`] when execution or recording fails.
     * Execute a workflow synchronously. Admin only.
     */
    async runWorkflow(requestParameters: RunWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowRun> {
        const response = await this.runWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
